Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2018-05, with the labels that each got.

#2583 ADIOS: 1.13.1
  INSTALL.rst
  buildsystem/CompileSuite/autoTests/new_commits.sh
  etc/picongpu/hydra-hzdr/default_picongpu.profile.example
  etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example
  etc/picongpu/hypnos-hzdr/k80_picongpu.profile.example
  etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example
  etc/picongpu/pizdaint-cscs/picongpu.profile.example
  etc/picongpu/titan-ornl/picongpu.profile.example
  etc/picongpu/titan-ornl/pythonOnRhea.profile.example
  include/picongpu/CMakeLists.txt
  include/picongpu/plugins/adios/ADIOSWriter.hpp
  src/tools/splash2txt/CMakeLists.txt
Labels: affects latest release, bug, component: plugin, component: third party

#2592 fix error message: missing restart step
  include/picongpu/simulationControl/MySimulation.hpp
Labels: bug, component: plugin

#2590 updata alpaka to release 0.3.0
  thirdParty/alpaka/README.md
  thirdParty/alpaka/appveyor.yml
  thirdParty/alpaka/include/alpaka/version.hpp
Labels: component: third party

#2593 precision.param: file doxygen
  include/picongpu/param/precision.param
  include/picongpu/unitless/precision.unitless
  share/picongpu/examples/LaserWakefield/include/picongpu/param/precision.param
Labels: component: user input, documentation

#2596 Syntax Highlighting: Fix RTD Theme
  docs/requirements.txt
  docs/source/conf.py
Labels: affects latest release, bug, component: third party, documentation

#2594 mallocMC.param: file doxygen
  include/picongpu/param/mallocMC.param
Labels: component: user input, documentation

#2591 memory.param: GUARD_SIZE docs
  include/picongpu/param/memory.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/memory.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/memory.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/memory.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/memory.param
Labels: component: user input, documentation

#2595 CompileSuite: Update Plugins
  buildsystem/CompileSuite/autoTests/new_commits.sh
Labels: component: tests

#2598 PMAcc functor: const on device functor factory
  include/picongpu/particles/filter/All.hpp
  include/picongpu/particles/filter/RelativeGlobalDomainPosition.hpp
  include/picongpu/particles/filter/generic/Free.hpp
  include/picongpu/particles/filter/generic/FreeRng.hpp
  include/picongpu/particles/filter/generic/FreeTotalCellOffset.hpp
  include/picongpu/particles/functor/misc/Rng.hpp
  include/picongpu/particles/functor/misc/TotalCellOffset.hpp
  include/picongpu/particles/manipulators/generic/Free.hpp
  include/picongpu/particles/manipulators/generic/FreeRng.hpp
  include/picongpu/particles/manipulators/unary/FreeTotalCellOffset.hpp
  include/picongpu/particles/startPosition/generic/Free.hpp
  include/picongpu/particles/startPosition/generic/FreeRng.hpp
  include/pmacc/functor/Filtered.hpp
  include/pmacc/functor/Interface.hpp
Labels: backend: omp2b, bug, component: PMacc, component: core

#2600 fix V100 deadlock
  include/pmacc/nvidia/atomic.hpp
  include/pmacc/nvidia/warp.hpp
Labels: affects latest release, backend: cuda, bug, component: PMacc

#2603 add support for more cpu alpaka accelerators
  bin/pic-configure
  include/pmacc/traits/GetNumWorkers.hpp
Labels: backend: serial, backend: tbb, component: PMacc

#2604 PMacc: refactor RNG method interface
  include/pmacc/random/distributions/distributions.hpp
  include/pmacc/random/methods/AlpakaRand.hpp
  include/pmacc/random/methods/MRG32k3aMin.hpp
  include/pmacc/random/methods/XorMin.hpp
  include/pmacc/random/methods/methods.hpp
Labels: component: PMacc, refactoring

#2606 remove usage of pure `float` with `float_X`
  include/picongpu/particles/bremsstrahlung/Bremsstrahlung.hpp
  include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
  include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp
  include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp
  include/picongpu/particles/synchrotronPhotons/PhotonCreator.hpp
Labels: affects latest release, bug, component: core

#2608 fix missing include
  include/pmacc/mappings/simulation/EnvironmentController.hpp
Labels: affects latest release, bug, component: PMacc

#2605 expose random number method to the user
  docs/source/usage/param/misc.rst
  include/picongpu/_defaultParam.loader
  include/picongpu/param/random.param
  include/picongpu/particles/bremsstrahlung/Bremsstrahlung.hpp
  include/picongpu/particles/functor/misc/Rng.hpp
  include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
  include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp
  include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp
  include/picongpu/particles/synchrotronPhotons/PhotonCreator.hpp
  include/picongpu/simulationControl/MySimulation.hpp
Labels: component: core, component: user input

#2609 PMacc: Vector sumOfComponents
  include/pmacc/math/vector/Vector.hpp
Labels: component: PMacc

#2607 seed generator for RNG
  include/picongpu/param/random.param
  include/picongpu/random/seed/ISeed.hpp
  include/picongpu/random/seed/Seed.cpp
  include/picongpu/random/seed/Seed.hpp
  include/picongpu/simulationControl/MySimulation.hpp
Labels: component: core

#2610 (compile issue) fix random seed
  include/picongpu/random/seed/Seed.cpp
Labels: bug, component: core

#2614 fix that guard size must be one
  include/picongpu/fields/FieldManipulator.kernel
  include/picongpu/plugins/IntensityPlugin.hpp
  include/picongpu/simulationControl/MySimulation.hpp
  include/pmacc/fields/operations/AddExchangeToBorder.hpp
  include/pmacc/fields/operations/CopyGuardToExchange.hpp
  include/pmacc/particles/ParticlesBase.hpp
Labels: affects latest release, bug, component: PMacc, component: core

#2611 ISAAC 1.3.3+
  INSTALL.rst
  buildsystem/CompileSuite/autoTests/new_commits.sh
  include/picongpu/CMakeLists.txt
Labels: bug, component: plugin

#2615 optimize stride size for update FieldJ
  include/picongpu/fields/FieldJ.tpp
Labels: component: core, refactoring
