Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2018-03, with the labels that each got.

#2542 remove modulo in 1D to ND index transformation
  include/pmacc/dimensions/DataSpaceOperations.hpp
Labels: component: PMacc, refactoring

#2543 Refactor .cfg files: devices
  docs/TBG_macros.cfg
  share/picongpu/dockerfiles/ubuntu-1604/start_lwfa.sh
  share/picongpu/examples/Bremsstrahlung/etc/picongpu/8.cfg
  share/picongpu/examples/Bunch/etc/picongpu/32.cfg
  share/picongpu/examples/Empty/etc/picongpu/1.cfg
  share/picongpu/examples/FoilLCT/etc/picongpu/4.cfg
  share/picongpu/examples/KelvinHelmholtz/etc/picongpu/16.cfg
  share/picongpu/examples/KelvinHelmholtz/etc/picongpu/4.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/1.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/16.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/1_isaac.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/32.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/4_gui.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/8.cfg
  share/picongpu/examples/SingleParticleTest/etc/picongpu/1.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/1.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/32.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/4.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/64.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/8.cfg
  share/picongpu/examples/WarmCopper/etc/picongpu/1.cfg
  share/picongpu/examples/WeibelTransverse/etc/picongpu/4.cfg
  share/pmacc/examples/gameOfLife2D/submit/1.cfg
  share/pmacc/examples/gameOfLife2D/submit/2.cfg
  share/pmacc/examples/gameOfLife2D/submit/4.cfg
Labels: refactoring, user input

#2546 DGX Docker
  etc/picongpu/bash/mpiexec.tpl
  etc/picongpu/bash/mpirun.tpl
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
Labels: bug, install

#2544 Doc: Fix HDF5 Release Link
  INSTALL.rst
Labels: component: third party, documentation

#2547 cupla: no .gitmodules
  thirdParty/cupla/.gitmodules
Labels: bug, component: third party, install

#2552 Docs: Fix Cmd Help
  USAGE.rst
  docs/source/usage/param.rst
  docs/source/usage/tbg.rst
Labels: bug, component: tools, documentation

#2553 Docs: Minor Formatting
  docs/source/usage/plugins/positionsParticles.rst
  share/picongpu/examples/Empty/README.rst
  share/picongpu/examples/WarmCopper/README.rst
Labels: documentation

#2558 Fixed excess 5p shell entry in gold effective Z
  include/picongpu/param/ionizer.param
Labels: bug, component: user input

#2555 Free Density: Fix float_X
  include/picongpu/param/density.param
Labels: component: user input, refactoring

#2561 fix zero size transform writes
  include/picongpu/plugins/adios/ADIOSWriter.hpp
Labels: affects latest release, bug, component: plugin

#2550 Simpler Python Parameter class
  lib/python/picongpu/input/parameters.py
  lib/python/picongpu/input/requirements.txt
  share/picongpu/examples/LaserWakefield/lib/python/picongpu/params.py
Labels: component: tools

#2560 Docs: PIC Model
  docs/source/_static/hide_chapter_titles.css
  docs/source/models/pic.rst
Labels: documentation
