Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2018-02, with the labels that each got.

#2525 Backports for 0.3.2-rc2
  INSTALL.rst
  docs/source/conf.py
  src/libPMacc/PMaccConfig.cmake
  src/libPMacc/examples/gameOfLife2D/CMakeLists.txt
  src/libPMacc/include/dataManagement/DataConnector.hpp
  src/libPMacc/include/eventSystem/Manager.hpp
  src/libPMacc/include/eventSystem/events/EventPool.hpp
  src/libPMacc/include/eventSystem/streams/StreamController.hpp
  src/libPMacc/include/eventSystem/tasks/Factory.hpp
  src/libPMacc/include/eventSystem/transactions/TransactionManager.hpp
  src/libPMacc/include/mappings/simulation/EnvironmentController.hpp
  src/libPMacc/include/math/vector/Vector.hpp
  src/libPMacc/include/nvidia/memory/MemoryInfo.hpp
  src/libPMacc/include/particles/tasks/ParticleFactory.hpp
  src/libPMacc/include/pluginSystem/PluginConnector.hpp
  src/libPMacc/include/simulationControl/SimulationDescription.hpp
  src/picongpu/CMakeLists.txt
  src/picongpu/include/fields/background/cellwiseOperation.hpp
  src/picongpu/include/plugins/adios/ADIOSWriter.hpp
  src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeter.hpp
  src/picongpu/include/simulationControl/MySimulation.hpp
  src/picongpu/include/version.hpp
  src/picongpu/submit/hypnos-hzdr/picongpu.profile.example
  src/tools/png2gas/CMakeLists.txt
  src/tools/splash2txt/CMakeLists.txt
Labels: bug, core, documentation, libPMacc, plugin, warning

#2526 pic-configure: fix old structure check
  pic-configure
Labels: bug, tools

#2527 Changelog in Manual
  CHANGELOG.md
  USAGE.rst
  docs/source/index.rst
  docs/source/install/changelog.md
  docs/source/install/profile.rst
Labels: documentation

#2530 visualization -> png.param
  docs/source/usage/param/plugins.rst
  docs/source/usage/plugins/png.rst
  include/picongpu/_defaultParam.loader
  include/picongpu/_defaultUnitless.loader
  include/picongpu/param/png.param
  include/picongpu/param/pngColorScales.param
  include/picongpu/plugins/output/images/PngCreator.tpp
  include/picongpu/unitless/png.unitless
  share/picongpu/examples/Bunch/include/picongpu/param/png.param
  share/picongpu/examples/Bunch/include/picongpu/param/visColorScales.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/png.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/visColorScales.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/png.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/visColorScales.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/png.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/visColorScales.param
Labels: user input

#2531 Changelog: 0.3.2
  CHANGELOG.md
  docs/source/conf.py
  src/picongpu/include/version.hpp
Labels: documentation

#2533 Release 0.3.2: Phase Space Momentum, ADIOS One-Particle Dumps & Field Names
  CHANGELOG.md
  INSTALL.rst
  docs/source/conf.py
  pic-configure
  src/libPMacc/PMaccConfig.cmake
  src/libPMacc/examples/gameOfLife2D/CMakeLists.txt
  src/libPMacc/include/cuSTL/algorithm/kernel/detail/ForeachKernel.hpp
  src/libPMacc/include/dataManagement/DataConnector.hpp
  src/libPMacc/include/eventSystem/Manager.hpp
  src/libPMacc/include/eventSystem/events/EventPool.hpp
  src/libPMacc/include/eventSystem/streams/StreamController.hpp
  src/libPMacc/include/eventSystem/tasks/Factory.hpp
  src/libPMacc/include/eventSystem/transactions/TransactionManager.hpp
  src/libPMacc/include/mappings/simulation/EnvironmentController.hpp
  src/libPMacc/include/math/vector/Vector.hpp
  src/libPMacc/include/nvidia/memory/MemoryInfo.hpp
  src/libPMacc/include/particles/tasks/ParticleFactory.hpp
  src/libPMacc/include/pluginSystem/PluginConnector.hpp
  src/libPMacc/include/simulationControl/SimulationDescription.hpp
  src/picongpu/CMakeLists.txt
  src/picongpu/include/fields/background/cellwiseOperation.hpp
  src/picongpu/include/plugins/PhaseSpace/PhaseSpace.tpp
  src/picongpu/include/plugins/PhaseSpace/PhaseSpaceFunctors.hpp
  src/picongpu/include/plugins/PhaseSpace/PhaseSpaceMulti.tpp
  src/picongpu/include/plugins/adios/ADIOSWriter.hpp
  src/picongpu/include/plugins/particleCalorimeter/ParticleCalorimeter.hpp
  src/picongpu/include/simulationControl/MySimulation.hpp
  src/picongpu/include/version.hpp
  src/picongpu/submit/hypnos-hzdr/picongpu.profile.example
  src/tools/bin/tbg
  src/tools/png2gas/CMakeLists.txt
  src/tools/splash2txt/CMakeLists.txt
Labels: affects latest release, bug, core, documentation, libPMacc, plugin, tools

#2532 compile time string
  docs/source/usage/workflows/probeParticles.rst
  include/picongpu/param/speciesDefinition.param
  include/pmacc/compileTime/String.hpp
  include/pmacc/particles/memory/frames/Frame.hpp
  include/pmacc/particles/traits/ResolveAliasFromSpecies.hpp
  include/pmacc/traits/GetCTName.hpp
  share/picongpu/examples/Bremsstrahlung/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/Bunch/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/WarmCopper/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/speciesDefinition.param
Labels: examples, libPMacc, user input

#2535 DOIs with (): URLencode
  README.md
Labels: bug, documentation

#2537 Move TBG to bin/
  INSTALL.rst
  bin/egetopt
  bin/tbg
  etc/picongpu/draco-mpcdf/picongpu.profile.example
  etc/picongpu/hydra-hzdr/default_picongpu.profile.example
  etc/picongpu/hypnos-hzdr/k20_picongpu.profile.example
  etc/picongpu/hypnos-hzdr/k80_picongpu.profile.example
  etc/picongpu/hypnos-hzdr/laser_picongpu.profile.example
  etc/picongpu/lawrencium-lbnl/picongpu.profile.example
  etc/picongpu/pizdaint-cscs/picongpu.profile.example
  etc/picongpu/taurus-tud/k20x_picongpu.profile.example
  etc/picongpu/taurus-tud/k80_picongpu.profile.example
  etc/picongpu/taurus-tud/knl_picongpu.profile.example
  etc/picongpu/titan-ornl/picongpu.profile.example
Labels: documentation, install, tools

#2538 CMake: Project Vars & Fix Memtest
  include/mpiInfo/CMakeLists.txt
  include/mpiInfo/mpiInfo.cpp
  include/picongpu/CMakeLists.txt
Labels: install, refactoring

#2539 Tools: Move pic-* to bin/
  bin/pic-build
  bin/pic-compile
  bin/pic-configure
  bin/pic-create
  bin/pic-edit
  buildsystem/CompileSuite/autoTests/new_commits.sh
  buildsystem/CompileSuite/compileSet.sh
Labels: install, tools

#2484 Python MPL Visualization modules
  docs/source/usage/plugins/phaseSpace.rst
  lib/python/picongpu/plugins/energy_histogram.py
  lib/python/picongpu/plugins/phase_space.py
  lib/python/picongpu/plugins/plot_mpl/__init__.py
  lib/python/picongpu/plugins/plot_mpl/base_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/png_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/requirements.txt
  lib/python/picongpu/plugins/png.py
  lib/python/picongpu/plugins/requirements.txt
Labels: component: plugin, component: tools

#2536 Piz Daint: Module Update
  etc/picongpu/pizdaint-cscs/picongpu.profile.example
Labels: documentation, machine/system

#2541 Piz Daint: Fix Detection Modern CMake
  etc/picongpu/pizdaint-cscs/picongpu.profile.example
Labels: bug, documentation, machine/system
