Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2018-11, with the labels that each got.

#2745 Use _X syntax in OnceIonized manipulator
  share/picongpu/examples/FoilLCT/include/picongpu/param/particle.param
Labels: component: examples, refactoring

#2773 Spack: Improve Bootstrap
  docs/source/install/instructions/spack.rst
Labels: affects latest release, bug, component: third party, documentation, install

#2781 Fix style issues with particlePusherAcceleration
  include/picongpu/param/pusher.param
  include/picongpu/particles/pusher/particlePusherAcceleration.hpp
Labels: refactoring

#2754 PhaseSpaceData: allow multiple iterations
  docs/source/usage/plugins/phaseSpace.rst
  lib/python/picongpu/plugins/data/phase_space.py
  lib/python/picongpu/plugins/data/png.py
Labels: component: plugin, component: tools

#2785 Update cuda_memtest: NVML Noise
  thirdParty/cuda_memtest/cuda_memtest.h
Labels: affects latest release, component: third party, component: tools, warning

#2784 Release 0.4.1
  .zenodo.json
  CHANGELOG.md
  LICENSE.md
  README.md
  docs/source/conf.py
  docs/source/install/instructions/spack.rst
  docs/source/models/field_ionization_comparison_c_ii_ionization.py
  docs/source/models/field_ionization_effective_potentials.py
  docs/source/usage/plugins/adios.rst
  docs/source/usage/plugins/hdf5.rst
  docs/source/usage/plugins/radiation.rst
  docs/source/usage/workflows/probeParticles.rst
  docs/source/usage/workflows/quasiNeutrality.rst
  include/picongpu/param/fileOutput.param
  include/picongpu/param/speciesDefinition.param
  include/picongpu/param/speciesInitialization.param
  include/picongpu/particles/densityProfiles/EveryNthCellImpl.hpp
  include/picongpu/plugins/particleMerging/ParticleMerger.kernel
  include/picongpu/simulationControl/MovingWindow.hpp
  include/picongpu/version.hpp
  lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
  lib/python/picongpu/utils/find_time.py
  share/picongpu/dockerfiles/README.rst
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
  share/picongpu/dockerfiles/ubuntu-1604/Singularity
  share/picongpu/examples/Bremsstrahlung/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/Bremsstrahlung/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/Bunch/include/picongpu/param/density.param
  share/picongpu/examples/Bunch/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/Bunch/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/fileOutput.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/WarmCopper/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/WarmCopper/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/speciesInitialization.param
  src/tools/bin/plot_chargeConservation.py
  src/tools/bin/plot_chargeConservation_overTime.py
  thirdParty/cuda_memtest/cuda_memtest.h
Labels: affects latest release, bug, component: core, component: plugin, component: third party, component: tools, documentation

#2789 Release 0.4.1
  .zenodo.json
  CHANGELOG.md
  LICENSE.md
  README.md
  docs/source/conf.py
  docs/source/install/instructions/spack.rst
  docs/source/models/field_ionization_comparison_c_ii_ionization.py
  docs/source/models/field_ionization_effective_potentials.py
  docs/source/usage/plugins/adios.rst
  docs/source/usage/plugins/hdf5.rst
  docs/source/usage/plugins/radiation.rst
  docs/source/usage/workflows/probeParticles.rst
  docs/source/usage/workflows/quasiNeutrality.rst
  include/picongpu/param/fileOutput.param
  include/picongpu/param/speciesDefinition.param
  include/picongpu/param/speciesInitialization.param
  include/picongpu/particles/densityProfiles/EveryNthCellImpl.hpp
  include/picongpu/plugins/particleMerging/ParticleMerger.kernel
  include/picongpu/simulationControl/MovingWindow.hpp
  include/picongpu/version.hpp
  lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
  lib/python/picongpu/utils/find_time.py
  share/picongpu/dockerfiles/README.rst
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
  share/picongpu/dockerfiles/ubuntu-1604/Singularity
  share/picongpu/examples/Bremsstrahlung/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/Bremsstrahlung/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/Bunch/include/picongpu/param/density.param
  share/picongpu/examples/Bunch/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/Bunch/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/fileOutput.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/WarmCopper/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/WarmCopper/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/speciesInitialization.param
  src/tools/bin/plot_chargeConservation.py
  src/tools/bin/plot_chargeConservation_overTime.py
  thirdParty/cuda_memtest/cuda_memtest.h
Labels: affects latest release, bug, component: core, component: examples, component: plugin, component: third party, component: tools, documentation

#2793 Fix species.param example doc and grammar
  include/picongpu/param/species.param
Labels: documentation

#2795 Fix species.param docu (in all examples too)
  include/picongpu/param/species.param
  share/picongpu/examples/Bunch/include/picongpu/param/species.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/species.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/species.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param
Labels: component: examples, component: user input, documentation

#2799 Fix Python EnergyHistogramData: skip of first iteration
  lib/python/picongpu/plugins/data/energy_histogram.py
Labels: affects latest release, bug, component: tools

#2710 Further improve wording in docs
  INSTALL.rst
  docs/source/index.rst
  docs/source/install/instructions/source.rst
  docs/source/install/instructions/spack.rst
  docs/source/install/path.rst
  docs/source/usage/reference.rst
Labels: documentation

#2804 CFL Static Assert: new grid.param
  include/picongpu/fields/MaxwellSolver/DirSplitting/DirSplitting.hpp
  include/picongpu/fields/MaxwellSolver/None/None.hpp
  include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
Labels: affects latest release, bug, documentation

#2805 Merge 0.4.1 Changelog
  CHANGELOG.md
Labels: documentation

#2811 Release 0.4.2
  CHANGELOG.md
  INSTALL.rst
  docs/source/conf.py
  docs/source/install/instructions/spack.rst
  docs/source/models/field_ionization.rst
  docs/source/usage/plugins/particleCalorimeter.rst
  include/picongpu/fields/MaxwellSolver/DirSplitting/DirSplitting.hpp
  include/picongpu/fields/MaxwellSolver/None/None.hpp
  include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
  include/picongpu/version.hpp
  lib/python/picongpu/plugins/data/energy_histogram.py
  thirdParty/alpaka/.travis.yml
  thirdParty/alpaka/include/alpaka/acc/AccCpuOmp2Blocks.hpp
  thirdParty/alpaka/include/alpaka/acc/AccCpuOmp2Threads.hpp
  thirdParty/alpaka/include/alpaka/acc/AccCpuOmp4.hpp
  thirdParty/alpaka/include/alpaka/alpaka.hpp
  thirdParty/alpaka/include/alpaka/atomic/AtomicOmpBuiltIn.hpp
  thirdParty/alpaka/include/alpaka/atomic/AtomicOmpCritSec.hpp
Labels: backend: omp2b, component: plugin, component: tools, documentation

#2813 Merge 0.4.2 Changelog
  CHANGELOG.md
Labels: documentation

#2814 Change link to CRP group @ HZDR
  README.md
Labels: component: tools, documentation

#2817 Plugins: ADIOS & PhaseSpace Wterminate
  include/picongpu/plugins/PhaseSpace/PhaseSpace.tpp
  include/picongpu/plugins/adios/ADIOSWriter.hpp
Labels: component: plugin, warning

#2818 Doc: Add System Links
  docs/source/install/profile.rst
Labels: documentation

#2792 stop moving window after N steps
  docs/TBG_macros.cfg
  include/picongpu/fields/FieldManipulator.hpp
  include/picongpu/plugins/IsaacPlugin.hpp
  include/picongpu/plugins/PngPlugin.hpp
  include/picongpu/plugins/adios/WriteSpecies.hpp
  include/picongpu/plugins/hdf5/WriteSpecies.hpp
  include/picongpu/simulationControl/MovingWindow.hpp
  include/picongpu/simulationControl/MySimulation.hpp
Labels: component: core, component: user input

#2819 Taurus Profile: Project
  etc/picongpu/taurus-tud/k20x_picongpu.profile.example
  etc/picongpu/taurus-tud/k80_picongpu.profile.example
  etc/picongpu/taurus-tud/knl_picongpu.profile.example
Labels: documentation, machine/system

#2822 MemoryCalculator: fix example output for documentation
  docs/source/usage/python/utils.rst
  docs/source/usage/workflows/memoryPerDevice.rst
Labels: documentation

#2820 Manual: Plugin & Particle Sections, Map
  docs/source/index.rst
  docs/source/usage/param/core.rst
  docs/source/usage/param/particles/init.rst
  docs/source/usage/plugins.rst
  docs/source/usage/plugins/energyHistogram.rst
  docs/source/usage/reference.rst
  docs/source/usage/workflows/particleFilters.rst
  include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/Bremsstrahlung/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/Bunch/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/WarmCopper/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/speciesInitialization.param
Labels: documentation

#2825 Update FreeRng.def
  include/picongpu/particles/filter/generic/FreeRng.def
Labels: bug, documentation

#2826 Examples: Unify .cfg
  share/picongpu/examples/Bremsstrahlung/etc/picongpu/8.cfg
  share/picongpu/examples/Bunch/etc/picongpu/32.cfg
  share/picongpu/examples/Empty/etc/picongpu/1.cfg
  share/picongpu/examples/FoilLCT/etc/picongpu/4.cfg
  share/picongpu/examples/FoilLCT/etc/picongpu/4_isaac.cfg
  share/picongpu/examples/FoilLCT/etc/picongpu/8.cfg
  share/picongpu/examples/FoilLCT/etc/picongpu/8_isaac.cfg
  share/picongpu/examples/KelvinHelmholtz/etc/picongpu/16.cfg
  share/picongpu/examples/KelvinHelmholtz/etc/picongpu/1_bench.cfg
  share/picongpu/examples/KelvinHelmholtz/etc/picongpu/4.cfg
  share/picongpu/examples/KelvinHelmholtz/etc/picongpu/4_bench.cfg
  share/picongpu/examples/KelvinHelmholtz/etc/picongpu/8_bench.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/1.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/1_isaac.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/32.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/4.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/4_gui.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/4_isaac.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/8.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/8_isaac.cfg
  share/picongpu/examples/SingleParticleTest/etc/picongpu/1.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/1.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/32.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/4.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/64.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/8.cfg
  share/picongpu/examples/WarmCopper/etc/picongpu/1.cfg
  share/picongpu/examples/WeibelTransverse/etc/picongpu/4.cfg
Labels: component: examples
