Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2018-10, with the labels that each got.

#2705 fix misspelled words in plugin documentation
  docs/source/usage/plugins/countParticles.rst
  docs/source/usage/plugins/countPerSupercell.rst
  docs/source/usage/plugins/energyHistogram.rst
  docs/source/usage/plugins/hdf5.rst
  docs/source/usage/plugins/intensity.rst
  docs/source/usage/plugins/particleCalorimeter.rst
  docs/source/usage/plugins/phaseSpace.rst
  docs/source/usage/plugins/png.rst
  docs/source/usage/plugins/radiation.rst
  share/picongpu/examples/Bunch/include/picongpu/param/radiation.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/radiation.param
Labels: component: plugin, documentation

#2712 fix tbg error message
  bin/tbg
Labels: component: tools, warning

#2699 Release 0.4.0-rc3
  bin/pic-configure
  bin/tbg
  docs/source/conf.py
  etc/picongpu/titan-ornl/gpu_picongpu.profile.example
  include/picongpu/version.hpp
  include/pmacc/PMaccConfig.cmake
  include/pmacc/cuSTL/algorithm/kernel/run-time/Foreach.hpp
  include/pmacc/cuSTL/container/assigner/DeviceMemAssigner.hpp
  include/pmacc/mappings/kernel/MappingDescription.hpp
  share/pmacc/examples/gameOfLife2D/include/Evolution.hpp
  share/pmacc/examples/gameOfLife2D/include/Simulation.hpp
  src/tools/bin/plotNumericalHeating
Labels: bug, component: tools

#2719 Python: param_parser for JSON parameter files
  lib/python/picongpu/utils/param_parser.py
Labels: component: tools

#2718 Fix sliceFieldReader
  lib/python/picongpu/plugins/sliceFieldReader.py
Labels: component: plugin, component: tools

#2720 Docs: Spack GCC Compiler CUDA
  docs/source/install/instructions/spack.rst
Labels: component: third party, documentation

#2725 RTD: Sphinx 1.7
  docs/requirements.txt
Labels: bug, component: third party, documentation

#2722 cuda_memtest usage on hypnos
  etc/picongpu/hypnos-hzdr/fermi.tpl
  etc/picongpu/hypnos-hzdr/k20.tpl
  etc/picongpu/hypnos-hzdr/k20_autoWait.tpl
  etc/picongpu/hypnos-hzdr/k20_restart.tpl
  etc/picongpu/hypnos-hzdr/k20_vampir.tpl
  etc/picongpu/hypnos-hzdr/k20_wait.tpl
  etc/picongpu/hypnos-hzdr/k80.tpl
  etc/picongpu/hypnos-hzdr/k80_restart.tpl
  etc/picongpu/hypnos-hzdr/laser.tpl
Labels: component: tools, refactoring

#2724 Update cuda_memtest: NVML Error Handling
  thirdParty/cuda_memtest/misc.cpp
  thirdParty/cuda_memtest/misc.h
Labels: affects latest release, bug, component: third party, component: tools

#2723 hemera tbg templates
  docs/source/install/profile.rst
  etc/picongpu/hemera-hzdr/defq.tpl
  etc/picongpu/hemera-hzdr/defq_picongpu.profile.example
  etc/picongpu/hemera-hzdr/gpu.tpl
  etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example
Labels: component: tools

#2711 add MPI linking info in install documentation
  INSTALL.rst
Labels: component: third party, documentation, install

#2727 Shorter python imports for postprocessing tools
  lib/python/picongpu/plugins/__init__.py
  lib/python/picongpu/plugins/plot_mpl/__init__.py
Labels: component: tools

#2728 Visualizers: axes passed on startup
  lib/python/picongpu/plugins/plot_mpl/base_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/png_visualizer.py
Labels: component: tools

#2730 Python: base class for data readers
  docs/source/usage/plugins/energyHistogram.rst
  docs/source/usage/plugins/phaseSpace.rst
  lib/python/picongpu/plugins/data/__init__.py
  lib/python/picongpu/plugins/data/base_reader.py
  lib/python/picongpu/plugins/data/energy_histogram.py
  lib/python/picongpu/plugins/data/phase_space.py
  lib/python/picongpu/plugins/data/png.py
  lib/python/picongpu/plugins/data/radiation.py
  lib/python/picongpu/plugins/data/requirements.txt
  lib/python/picongpu/plugins/data/sliceFieldReader.py
  lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/png_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/requirements.txt
  lib/python/picongpu/plugins/requirements.txt
Labels: component: tools

#2726 Plugin Docs: Python Tools & Matplotlib
  docs/requirements.txt
  docs/source/conf.py
  docs/source/dev/py_postprocessing.rst
  docs/source/usage/plugins.rst
  docs/source/usage/plugins/energyHistogram.rst
  docs/source/usage/plugins/phaseSpace.rst
  docs/source/usage/plugins/png.rst
Labels: component: plugin, component: tools, documentation

#2733 Docs: openPMD Update
  docs/requirements.txt
  docs/source/postprocessing/openPMD.rst
  docs/source/postprocessing/python.rst
Labels: documentation

#2734 Docs: New Subtitle
  README.md
  docs/source/index.rst
Labels: documentation

#2735 fix typo in libSplash in install documentation
  INSTALL.rst
Labels: component: plugin, component: third party, documentation, install

#2738 Python Docs: Fix Paths
  docs/source/index.rst
  lib/python/picongpu/plugins/__init__.py
Labels: bug, component: tools, documentation

#2667 Taurus: SCS5 Update
  etc/picongpu/taurus-tud/k20x_picongpu.profile.example
  etc/picongpu/taurus-tud/k80_picongpu.profile.example
  etc/picongpu/taurus-tud/knl_picongpu.profile.example
Labels: documentation

#2739 RTD: Mock Sphinx Imports
  docs/source/conf.py
  lib/python/picongpu/plugins/data/requirements.txt
Labels: bug, documentation

#2740 Boost 1.68.0 Predef
  include/pmacc/types.hpp
Labels: backend: cuda, bug, component: third party

#2741 Docs: Alpaka 0.3.4
  INSTALL.rst
Labels: component: third party, documentation

#2767 Python Regex: r Literals
  docs/source/models/field_ionization_comparison_c_ii_ionization.py
  docs/source/models/field_ionization_effective_potentials.py
  lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
  lib/python/picongpu/utils/find_time.py
  src/tools/bin/plot_chargeConservation.py
  src/tools/bin/plot_chargeConservation_overTime.py
Labels: affects latest release, bug, component: tests, component: tools

#2756 fix outdated derive species
  share/picongpu/examples/LaserWakefield/include/picongpu/param/speciesInitialization.param
Labels: affects latest release, component: examples

#2758 remove current deposition in bunch example
  share/picongpu/examples/Bunch/include/picongpu/param/speciesDefinition.param
Labels: affects latest release, bug, component: examples, component: user input

#2768 fix EveryNthCellImpl
  include/picongpu/particles/densityProfiles/EveryNthCellImpl.hpp
Labels: affects latest release, bug, component: core

#2772 Fix docs for radiation in 2D
  docs/source/usage/plugins/radiation.rst
Labels: component: plugin, documentation

#2750 Containers: Update 0.4.0
  share/picongpu/dockerfiles/README.rst
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
  share/picongpu/dockerfiles/ubuntu-1604/Singularity
Labels: component: third party, documentation

#2748 Merge 0.4.0 Changelog
  CHANGELOG.md
  docs/source/conf.py
  include/picongpu/version.hpp
Labels: documentation

#2731 Particle pusher acceleration
  include/picongpu/param/pusher.param
  include/picongpu/param/species.param
  include/picongpu/particles/pusher/particlePusherAcceleration.hpp
  include/picongpu/unitless/pusher.unitless
Labels: component: core, component: user input

#2776 Add getter for omega and n to python module
  lib/python/picongpu/plugins/data/radiation.py
Labels: component: tools

#2747 Add .zenodo.json
  .zenodo.json
Labels: component: third party, documentation

#2749 Update Readme & License: People
  LICENSE.md
  README.md
Labels: documentation

#2779 Python Tools: Incorporate sim_time into readers and visualizers
  docs/source/dev/py_postprocessing.rst
  lib/python/picongpu/plugins/data/base_reader.py
  lib/python/picongpu/plugins/data/energy_histogram.py
  lib/python/picongpu/plugins/data/phase_space.py
  lib/python/picongpu/plugins/data/png.py
  lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/png_visualizer.py
Labels: component: tools

#2774 avoid two slides
  include/picongpu/simulationControl/MovingWindow.hpp
Labels: affects latest release, bug, component: core
