Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2018-12, with the labels that each got.

#2762 Python MPL Visualizer: plot for several simulations
  lib/python/picongpu/plugins/data/base_reader.py
  lib/python/picongpu/plugins/data/phase_space.py
  lib/python/picongpu/plugins/plot_mpl/base_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/png_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/utils.py
Labels: component: plugin, component: tools

#2833 Eliminate M_PI (again)
  include/picongpu/fields/MaxwellSolver/Lehe/Curl.hpp
Labels: component: core, refactoring

#2835 Fix MappingDesc name hiding
  include/picongpu/particles/Particles.tpp
Labels: affects latest release, bug, component: core

#2834 More fixes for MSVC capturing constexpr in lambdas
  include/picongpu/fields/LaserPhysics.hpp
  include/picongpu/particles/ParticlesInit.kernel
Labels: component: core, refactoring

#2829 Docs: Install Blosc
  INSTALL.rst
Labels: component: third party, documentation, install

#2831 fix particle creation if density zero
  include/picongpu/particles/ParticlesInit.kernel
Labels: affects latest release, bug, component: core

#2839 Slurm: Link stdout live
  etc/picongpu/draco-mpcdf/general.tpl
  etc/picongpu/hemera-hzdr/defq.tpl
  etc/picongpu/hemera-hzdr/gpu.tpl
  etc/picongpu/lawrencium-lbnl/fermi.tpl
  etc/picongpu/lawrencium-lbnl/k20.tpl
  etc/picongpu/pizdaint-cscs/large.tpl
  etc/picongpu/pizdaint-cscs/normal.tpl
  etc/picongpu/taurus-tud/k20x.tpl
  etc/picongpu/taurus-tud/k80.tpl
  etc/picongpu/taurus-tud/knl.tpl
Labels: component: tools, documentation

#2837 remove ZigZag current deposition
  include/picongpu/fields/currentDeposition/EmZ/EmZ.def
  include/picongpu/fields/currentDeposition/Solver.def
  include/picongpu/fields/currentDeposition/Solver.hpp
  include/picongpu/fields/currentDeposition/ZigZag/EvalAssignmentFunction.hpp
  include/picongpu/fields/currentDeposition/ZigZag/ZigZag.def
  include/picongpu/fields/currentDeposition/ZigZag/ZigZag.hpp
  include/picongpu/param/species.param
  include/picongpu/particles/Particles.kernel
  share/picongpu/examples/Bunch/include/picongpu/param/species.param
  share/picongpu/examples/KelvinHelmholtz/cmakeFlags
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/species.param
  share/picongpu/examples/LaserWakefield/cmakeFlags
  share/picongpu/examples/LaserWakefield/include/picongpu/param/species.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param
Labels: refactoring

#2588 Emittance Plugin
  docs/source/usage/plugins.rst
  docs/source/usage/plugins/sliceEmittance.rst
  include/picongpu/plugins/Emittance.hpp
  include/picongpu/plugins/PluginController.hpp
Labels: component: plugin

#2840 auto domain adjustment
  docs/TBG_macros.cfg
  docs/source/usage/workflows/numberOfCells.rst
  include/picongpu/simulationControl/DomainAdjuster.hpp
  include/picongpu/simulationControl/MySimulation.hpp
Labels: component: core
