Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2019-01, with the labels that each got.

#2842 Radiation Plugin: Update Options in Docs
  docs/source/usage/plugins/radiation.rst
Labels: affects latest release, component: plugin, documentation

#2848 Calorimeter: Fix unitSI
  docs/source/usage/plugins/particleCalorimeter.rst
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
Labels: affects latest release, bug, component: plugin

#2852 PlotMPL: fix run_directory arg into run_directories
  lib/python/picongpu/plugins/plot_mpl/phase_space_visualizer.py
  lib/python/picongpu/plugins/plot_mpl/png_visualizer.py
Labels: component: tools, refactoring

#2838 Fix binomial current interpolation
  include/picongpu/fields/currentInterpolation/Binomial/Binomial.hpp
Labels: affects latest release, bug, component: core

#2691 Python visualizers as jupyter widgets
  docs/source/dev/py_postprocessing.rst
  docs/source/usage/plugins.rst
  docs/source/usage/plugins/energyHistogram.rst
  docs/source/usage/plugins/phaseSpace.rst
  docs/source/usage/plugins/png.rst
  lib/python/picongpu/plugins/jupyter_widgets/__init__.py
  lib/python/picongpu/plugins/jupyter_widgets/base_widget.py
  lib/python/picongpu/plugins/jupyter_widgets/energy_histogram_widget.py
  lib/python/picongpu/plugins/jupyter_widgets/phase_space_widget.py
  lib/python/picongpu/plugins/jupyter_widgets/png_widget.py
  lib/python/picongpu/plugins/jupyter_widgets/requirements.txt
  lib/python/picongpu/plugins/jupyter_widgets/utils.py
Labels: component: tools

#2857 OpenMPI: Use ROMIO for IO
  etc/picongpu/bash/mpiexec.tpl
  etc/picongpu/bash/mpirun.tpl
  etc/picongpu/davide-cineca/gpu.tpl
  etc/picongpu/davinci-rice/picongpu.tpl
  etc/picongpu/hemera-hzdr/defq.tpl
  etc/picongpu/hemera-hzdr/gpu.tpl
  etc/picongpu/hydra-hzdr/default.tpl
  etc/picongpu/hypnos-hzdr/fermi.tpl
  etc/picongpu/hypnos-hzdr/k20.tpl
  etc/picongpu/hypnos-hzdr/k20_autoWait.tpl
  etc/picongpu/hypnos-hzdr/k20_restart.tpl
  etc/picongpu/hypnos-hzdr/k20_vampir.tpl
  etc/picongpu/hypnos-hzdr/k20_wait.tpl
  etc/picongpu/hypnos-hzdr/k80.tpl
  etc/picongpu/hypnos-hzdr/k80_restart.tpl
  etc/picongpu/hypnos-hzdr/laser.tpl
  etc/picongpu/lawrencium-lbnl/fermi.tpl
  etc/picongpu/lawrencium-lbnl/k20.tpl
  etc/picongpu/taurus-tud/k20x.tpl
  etc/picongpu/taurus-tud/k80.tpl
Labels: affects latest release, bug, component: plugin, component: third party, documentation

#2859 Core Particles: C++11 Using for Typedef
  include/picongpu/algorithms/FieldToParticleInterpolation.hpp
  include/picongpu/algorithms/FieldToParticleInterpolationNative.hpp
  include/picongpu/algorithms/LinearInterpolateWithUpper.hpp
  include/picongpu/algorithms/ShiftCoordinateSystem.hpp
  include/picongpu/initialization/ParserGridDistribution.hpp
  include/picongpu/particles/InitFunctors.hpp
  include/picongpu/particles/Particles.hpp
  include/picongpu/particles/ParticlesFunctors.hpp
  include/picongpu/particles/access/Cell2Particle.tpp
  include/picongpu/particles/boundary/CallPluginsAndDeleteParticles.hpp
  include/picongpu/particles/bremsstrahlung/Bremsstrahlung.hpp
  include/picongpu/particles/bremsstrahlung/PhotonEmissionAngle.hpp
  include/picongpu/particles/bremsstrahlung/ScaledSpectrum.hpp
  include/picongpu/particles/bremsstrahlung/ScaledSpectrum.tpp
  include/picongpu/particles/creation/creation.hpp
  include/picongpu/particles/densityProfiles/FromHDF5Impl.hpp
  include/picongpu/particles/densityProfiles/HomogenousImpl.hpp
  include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp
  include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp
  include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp
  include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.def
  include/picongpu/particles/pusher/particlePusherAxel.hpp
  include/picongpu/particles/pusher/particlePusherBoris.hpp
  include/picongpu/particles/pusher/particlePusherFree.hpp
  include/picongpu/particles/pusher/particlePusherPhoton.hpp
  include/picongpu/particles/pusher/particlePusherReducedLandauLifshitz.hpp
  include/picongpu/particles/pusher/particlePusherVay.hpp
  include/picongpu/particles/synchrotronPhotons/PhotonCreator.hpp
  include/picongpu/particles/synchrotronPhotons/SynchrotronFunctions.hpp
  include/picongpu/particles/synchrotronPhotons/SynchrotronFunctions.tpp
  include/picongpu/particles/traits/GetAtomicNumbers.hpp
  include/picongpu/particles/traits/GetCurrentSolver.hpp
  include/picongpu/particles/traits/GetInterpolation.hpp
  include/picongpu/particles/traits/GetIonizationEnergies.hpp
  include/picongpu/particles/traits/GetMarginPusher.hpp
  include/picongpu/particles/traits/GetPusher.hpp
  include/picongpu/particles/traits/GetShape.hpp
  include/picongpu/particles/traits/GetSpeciesFlagName.hpp
  include/picongpu/simulationControl/MySimulation.hpp
  include/picongpu/simulationControl/SimulationStarter.hpp
Labels: component: core, refactoring

#2866 Fix pyflakes str/bytes/int compares
  lib/python/picongpu/plugins/jupyter_widgets/base_widget.py
  src/tools/bin/smooth.py
Labels: component: tools, refactoring, warning

#2865 Fix Typo: Aluminium in ionizer.param
  include/picongpu/param/ionizer.param
Labels: component: examples, component: user input

#2847 Docker & Singularity Updates
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
  share/picongpu/dockerfiles/ubuntu-1604/modules.yaml
  share/picongpu/dockerfiles/ubuntu-1604/packages.yaml
Labels: affects latest release, bug, component: third party, component: tools, install

#2856 Taurus: Power9 V100 Templates
  docs/source/install/profile.rst
  etc/picongpu/taurus-tud/V100.tpl
  etc/picongpu/taurus-tud/V100_picongpu.profile.example
  etc/picongpu/taurus-tud/V100_restart.tpl
Labels: documentation, machine/system

#2868 Docs: Memory per Device Spelling
  docs/source/usage/workflows/memoryPerDevice.py
Labels: documentation
