Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2019-10, with the labels that each got.

#3078 added silicon element to ioniser
  include/picongpu/param/ionizationEnergies.param
  include/picongpu/param/ionizer.param
Labels: component: user input

#3076 Make dependency between boundElectrons and atomicNumbers more explicit
  include/picongpu/param/speciesAttributes.param
  include/picongpu/traits/attribute/GetCharge.hpp
  include/picongpu/traits/attribute/GetChargeState.hpp
Labels: component: core, component: user input

#3080 Docs: add missing checkpoint options
  docs/source/usage/plugins/checkpoint.rst
Labels: documentation

#3083 Update the form factor documentation
  docs/source/usage/plugins/radiation.rst
  docs/source/usage/plugins/transitionRadiation.rst
Labels: documentation

#3061 SpeciesEligibleForSolver for radiation plugin
  include/picongpu/plugins/radiation/Radiation.hpp
  include/picongpu/plugins/radiation/Radiation.kernel
Labels: component: plugin, refactoring

#3052 Add output and python module doc for radiation plugin
  docs/source/usage/plugins/radiation.rst
Labels: component: plugin, documentation

#3086 remove titan ornl setup and doc
  docs/source/install/profile.rst
  etc/picongpu/titan-ornl/batch_scorep.tpl
  etc/picongpu/titan-ornl/cpu_batch.tpl
  etc/picongpu/titan-ornl/cpu_picongpu.profile.example
  etc/picongpu/titan-ornl/gpu_batch.tpl
  etc/picongpu/titan-ornl/gpu_picongpu.profile.example
  etc/picongpu/titan-ornl/pythonOnComp.profile.example
  etc/picongpu/titan-ornl/pythonOnRhea.profile.example
  include/pmacc/PMaccConfig.cmake
Labels: documentation, machine/system

#3084 fix CUDA device selection
  include/pmacc/Environment.hpp
Labels: affects latest release, backend: cuda, bug

#3007 Summit: Profile & Templates
  docs/source/install/profile.rst
  docs/source/usage/tbg.rst
  etc/picongpu/summit-ornl/LSF_Tutorial.rst
  etc/picongpu/summit-ornl/gpu_batch.tpl
  etc/picongpu/summit-ornl/gpu_picongpu.profile.example
Labels: documentation, machine/system

#3094 fix optional install instructions in the Summit profile
  etc/picongpu/summit-ornl/gpu_picongpu.profile.example
Labels: documentation, machine/system
