Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2019-06, with the labels that each got.

#2970 Dockerfile: No SSH Deamon & Keys, Fix Flex Build
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
  share/picongpu/dockerfiles/ubuntu-1604/packages.yaml
Labels: affects latest release, bug, component: tools, install

#2964 Separate the code processing currents from MySimulation
  include/picongpu/fields/FieldJ.hpp
  include/picongpu/simulation/stage/CurrentBackground.hpp
  include/picongpu/simulation/stage/CurrentDeposition.hpp
  include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp
  include/picongpu/simulation/stage/CurrentReset.hpp
  include/picongpu/simulationControl/MySimulation.hpp
Labels: component: core, refactoring

#2941 Add const getters to ParticleBox
  include/pmacc/particles/memory/boxes/ParticlesBox.hpp
Labels: component: PMacc, refactoring

#2951 Add DataConnector::consume(), which shares and consumes the input
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
  include/picongpu/particles/ParticlesFunctors.hpp
  include/picongpu/particles/flylite/NonLTE.tpp
  include/picongpu/simulationControl/MySimulation.hpp
  include/pmacc/dataManagement/DataConnector.hpp
Labels: component: PMacc, component: core, refactoring

#2967 Enable checkpoints for the PML fields
  include/picongpu/fields/MaxwellSolver/YeePML/Field.hpp
  include/picongpu/fields/MaxwellSolver/YeePML/Field.tpp
  include/picongpu/plugins/adios/ADIOSWriter.hpp
  include/picongpu/plugins/adios/restart/RestartFieldLoader.hpp
  include/picongpu/plugins/hdf5/HDF5Writer.hpp
  include/picongpu/plugins/hdf5/restart/RestartFieldLoader.hpp
  include/picongpu/unitless/checkpoints.unitless
  include/pmacc/memory/buffers/HostDeviceBuffer.hpp
Labels: component: core

#2971 Move picongpu/simulationControl to picongpu/simulation/control
  include/picongpu/fields/FieldManipulator.hpp
  include/picongpu/fields/background/cellwiseOperation.hpp
  include/picongpu/particles/Particles.tpp
  include/picongpu/particles/creation/creation.kernel
  include/picongpu/particles/densityProfiles/FreeFormulaImpl.hpp
  include/picongpu/particles/densityProfiles/FromHDF5Impl.hpp
  include/picongpu/particles/densityProfiles/GaussianCloudImpl.hpp
  include/picongpu/particles/densityProfiles/GaussianImpl.hpp
  include/picongpu/particles/densityProfiles/SphereFlanksImpl.hpp
  include/picongpu/plugins/Emittance.hpp
  include/picongpu/plugins/PngPlugin.hpp
  include/picongpu/plugins/adios/ADIOSWriter.def
  include/picongpu/plugins/adios/ADIOSWriter.hpp
  include/picongpu/plugins/adios/restart/RestartFieldLoader.hpp
  include/picongpu/plugins/hdf5/HDF5Writer.def
  include/picongpu/plugins/hdf5/HDF5Writer.hpp
  include/picongpu/plugins/hdf5/restart/RestartFieldLoader.hpp
  include/picongpu/plugins/output/header/MessageHeader.hpp
  include/picongpu/plugins/output/images/Visualisation.hpp
  include/picongpu/simulation/control/DomainAdjuster.hpp
  include/picongpu/simulation/control/ISimulationStarter.hpp
  include/picongpu/simulation/control/MovingWindow.hpp
  include/picongpu/simulation/control/MySimulation.hpp
  include/picongpu/simulation/control/SimulationStarter.hpp
  include/picongpu/simulation/control/Window.hpp
  include/picongpu/unitless/starter.unitless
  share/picongpu/examples/ThermalTest/include/picongpu/ThermalTestSimulation.hpp
  share/picongpu/examples/ThermalTest/include/picongpu/unitless/starter.unitless
Labels: component: core, refactoring

#2975 CMake: CUDA 9.2-10.1, Boost <= 1.70.0
  INSTALL.rst
  buildsystem/CompileSuite/autoTests/new_commits.sh
  docs/source/install/instructions/spack.rst
  include/pmacc/PMaccConfig.cmake
  share/picongpu/dockerfiles/README.rst
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
  share/picongpu/dockerfiles/ubuntu-1604/packages.yaml
Labels: backend: cuda, component: third party, documentation

#2976 Remove unused pmacc::traits::GetEmptyDefaultConstructibleType
  include/pmacc/particles/memory/dataTypes/FramePointer.hpp
  include/pmacc/particles/memory/dataTypes/Pointer.hpp
  include/pmacc/traits/GetEmptyDefaultConstructibleType.hpp
Labels: component: PMacc, refactoring

#2974 Separate the code processing particles from MySimulation
  include/picongpu/simulation/control/MySimulation.hpp
  include/picongpu/simulation/stage/Bremsstrahlung.hpp
  include/picongpu/simulation/stage/FieldBackground.hpp
  include/picongpu/simulation/stage/MomentumBackup.hpp
  include/picongpu/simulation/stage/ParticleIonization.hpp
  include/picongpu/simulation/stage/ParticlePush.hpp
  include/picongpu/simulation/stage/PopulationKinetics.hpp
  include/picongpu/simulation/stage/SynchrotronRadiation.hpp
Labels: component: core, refactoring

#2979 Remove pmacc::traits::IsSameType which is no longer used
  include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.hpp
  include/pmacc/traits/IsSameType.hpp
Labels: component: PMacc, refactoring

#2972 Refactor cell types
  include/picongpu/fields/CellType.hpp
  include/picongpu/fields/FieldB.tpp
  include/picongpu/fields/FieldE.tpp
  include/picongpu/fields/FieldJ.tpp
  include/picongpu/fields/FieldTmp.tpp
  include/picongpu/fields/MaxwellSolver/DirSplitting/DirSplitting.hpp
  include/picongpu/fields/MaxwellSolver/None/None.hpp
  include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
  include/picongpu/fields/MaxwellSolver/YeePML/Field.hpp
  include/picongpu/fields/MaxwellSolver/YeePML/Field.tpp
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
  include/picongpu/fields/background/templates/TWTS/BField.tpp
  include/picongpu/fields/background/templates/TWTS/EField.tpp
  include/picongpu/fields/background/templates/TWTS/getFieldPositions_SI.tpp
  include/picongpu/fields/cellType/Centered.hpp
  include/picongpu/fields/cellType/Yee.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/EsirkepovNative.hpp
  include/picongpu/fields/currentDeposition/Solver.hpp
  include/picongpu/particles/Particles.kernel
  include/picongpu/particles/Particles.tpp
  include/picongpu/particles/bremsstrahlung/Bremsstrahlung.tpp
  include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
  include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp
  include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp
  include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp
  include/picongpu/particles/synchrotronPhotons/PhotonCreator.hpp
  include/picongpu/plugins/adios/ADIOSWriter.hpp
  include/picongpu/plugins/hdf5/WriteFields.hpp
Labels: component: core, refactoring

#2980 Badge: Commits Since Release & Good First
  README.md
Labels: documentation

#2977 Remove template parameter for initialization method of Pointer and FramePointer
  include/pmacc/particles/memory/boxes/ParticlesBox.hpp
  include/pmacc/particles/memory/dataTypes/FramePointer.hpp
  include/pmacc/particles/memory/dataTypes/Pointer.hpp
Labels: component: PMacc, refactoring

#2984 Update info on maintainers in README.md
  README.md
Labels: documentation

#2985 Fix a compilation issue with ForEach lookup
  include/pmacc/particles/memory/dataTypes/Particle.hpp
Labels: component: PMacc, machine/system

#2978 Remove pmacc::expressions which is no longer used
  include/pmacc/expressions/DoNothing.hpp
  include/pmacc/expressions/SetToNull.hpp
Labels: component: PMacc, refactoring

#2986 SimulationFieldHelper: getter method to access cell description
  include/pmacc/fields/SimulationFieldHelper.hpp
Labels: component: PMacc

#2987 fix warning: comparison of unsigned integer
  include/picongpu/fields/LaserPhysics.hpp
Labels: component: core, warning

#2981 Singularity: Avoid Dotfiles in Home
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
  share/picongpu/dockerfiles/ubuntu-1604/compilers.yaml
Labels: backend: cuda, component: third party, install
