Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2019-08, with the labels that each got.

#3013 Resource Monitor Plugin: Warnings
  include/picongpu/plugins/ResourceLog.cpp
  include/picongpu/plugins/ResourceLog.hpp
Labels: backend: cuda, component: plugin, component: third party, warning

#3014 Pass mapping description by value instead of pointer from simulation stages
  include/picongpu/particles/ParticlesFunctors.hpp
  include/picongpu/particles/creation/creation.hpp
  include/picongpu/simulation/stage/Bremsstrahlung.hpp
  include/picongpu/simulation/stage/ParticleIonization.hpp
  include/picongpu/simulation/stage/SynchrotronRadiation.hpp
Labels: component: core

#3016 hemera-hzdr: remove project definition
  etc/picongpu/hemera-hzdr/k20.tpl
  etc/picongpu/hemera-hzdr/k20_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k20_restart.tpl
  etc/picongpu/hemera-hzdr/k80.tpl
  etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k80_restart.tpl
Labels: bug, machine/system

#3017 Singularity: Workaround Chmod Issue, No UCX
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
  share/picongpu/dockerfiles/ubuntu-1604/packages.yaml
Labels: affects latest release, bug, component: third party, install

#3015 Fix code causing cudaErrorInvalidDeviceFunction
  include/picongpu/particles/flylite/helperFields/LocalDensityFunctors.hpp
  include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
Labels: backend: cuda, bug

#3019 Fix radiation plugin misleading filename
  include/picongpu/param/radiation.param
  include/picongpu/plugins/PluginController.hpp
  include/picongpu/plugins/radiation/Radiation.kernel
  include/picongpu/plugins/radiation/VectorTypes.hpp
  include/picongpu/plugins/radiation/amplitude.hpp
  include/picongpu/plugins/radiation/check_consistency.hpp
  include/picongpu/plugins/radiation/nyquist_low_pass.hpp
  include/picongpu/plugins/radiation/taylor.hpp
  share/picongpu/examples/Bunch/include/picongpu/param/radiation.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/radiation.param
Labels: component: plugin

#3018 Fix old file name in radiation doc
  docs/source/usage/plugins/radiation.rst
Labels: documentation

#3005 Refactor and modernize implementation of fields
  include/picongpu/fields/EMFieldBase.hpp
  include/picongpu/fields/EMFieldBase.tpp
  include/picongpu/fields/FieldB.hpp
  include/picongpu/fields/FieldB.tpp
  include/picongpu/fields/FieldE.hpp
  include/picongpu/fields/FieldE.tpp
  include/picongpu/fields/FieldJ.hpp
  include/picongpu/fields/FieldJ.tpp
  include/picongpu/fields/FieldTmp.hpp
  include/picongpu/fields/FieldTmp.tpp
  include/picongpu/fields/Fields.tpp
  include/picongpu/fields/MaxwellSolver/YeePML/Field.hpp
  include/picongpu/fields/MaxwellSolver/YeePML/Field.tpp
Labels: component: core, refactoring

#3023 Modernize ArgsParser::ArgsErrorCode
  include/picongpu/ArgsParser.cpp
  include/picongpu/ArgsParser.hpp
  include/picongpu/main.cpp
  include/picongpu/simulation/control/ISimulationStarter.hpp
  include/picongpu/simulation/control/SimulationStarter.hpp
Labels: component: core, refactoring

#3021 Radiation Plugin: fix bool conditions for hdf5 output
  include/picongpu/plugins/radiation/Radiation.hpp
Labels: affects latest release, bug, component: plugin

#3028 Fix field solver initialization order
  include/picongpu/simulation/control/MySimulation.hpp
Labels: bug, component: core

#3029 Add an option to account for PML in the memory calculator
  lib/python/picongpu/utils/memory_calculator.py
Labels: component: tools

#3030 Remove unused pmacc::IDataSorter
  include/picongpu/initialization/SimStartInitialiser.hpp
  include/pmacc/dataManagement/AbstractInitialiser.hpp
  include/pmacc/dataManagement/IDataSorter.hpp
Labels: component: PMacc, refactoring

#3022 Add a runtime parameter for window move point
  include/picongpu/ArgsParser.cpp
  include/picongpu/simulation/control/MovingWindow.hpp
  include/picongpu/simulation/control/MySimulation.hpp
Labels: component: user input

#3035 Fix a crash in reporting deprecated parameters
  include/picongpu/ArgsParser.cpp
Labels: bug, component: user input

#3031 add reset PML fields in MySimulation::resetAll()
  include/picongpu/simulation/control/MySimulation.hpp
Labels: bug, component: core

#3036 Fix multiple definitions of PMacc identifiers and aliases
  include/pmacc/identifier/alias.hpp
  include/pmacc/identifier/identifier.hpp
Labels: component: PMacc

#3040 Remove unused includes of pthread
  include/picongpu/plugins/adios/ADIOSWriter.hpp
  include/picongpu/plugins/hdf5/HDF5Writer.hpp
Labels: component: plugin, refactoring

#3038 Proper Constructor in unitDimension std::vector
  include/picongpu/fields/FieldB.tpp
  include/picongpu/fields/FieldE.tpp
Labels: bug, component: core

#3042 Add YeePML to comments for field solver selection
  include/picongpu/param/fieldSolver.param
  share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/fieldSolver.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/fieldSolver.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/fieldSolver.param
Labels: component: examples

#3039 System: ARIS
  docs/source/install/profile.rst
  etc/picongpu/aris-grnet/gpu.tpl
  etc/picongpu/aris-grnet/gpu_picongpu.profile.example
Labels: documentation, machine/system
