Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2020-04, with the labels that each got.

#3195 MPI direct support
  etc/picongpu/summit-ornl/gpu_batch.tpl
  include/pmacc/Environment.hpp
  include/pmacc/eventSystem/tasks/TaskReceive.hpp
  include/pmacc/eventSystem/tasks/TaskReceiveMPI.hpp
  include/pmacc/eventSystem/tasks/TaskSend.hpp
  include/pmacc/eventSystem/tasks/TaskSendMPI.hpp
  include/pmacc/memory/buffers/Exchange.hpp
  include/pmacc/memory/buffers/ExchangeIntern.hpp
  include/pmacc/particles/ParticlesBase.tpp
  include/pmacc/particles/memory/buffers/StackExchangeBuffer.hpp
  include/pmacc/simulationControl/SimulationHelper.hpp
Labels: component: PMacc

#3224 Fix a bug with wrong exponential absorber strength
  include/picongpu/fields/absorber/ExponentialDamping.hpp
Labels: bug, component: core

#3225 fix docker container
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
Labels: backend: cuda, bug, component: third party, install

#3221 strategy for current deposition algorithm
  docs/source/usage/param/core.rst
  docs/source/usage/param/particles/current.rst
  include/picongpu/fields/FieldJ.kernel
  include/picongpu/fields/FieldJ.tpp
  include/picongpu/fields/currentDeposition/Cache.hpp
  include/picongpu/fields/currentDeposition/Deposit.hpp
  include/picongpu/fields/currentDeposition/EmZ/DepositCurrent.hpp
  include/picongpu/fields/currentDeposition/EmZ/EmZ.def
  include/picongpu/fields/currentDeposition/EmZ/EmZ.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.def
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/EsirkepovNative.hpp
  include/picongpu/fields/currentDeposition/Solver.def
  include/picongpu/fields/currentDeposition/Strategy.def
  include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.def
  include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.hpp
  include/picongpu/param/species.param
  include/pmacc/nvidia/functors/Atomic.hpp
  share/picongpu/examples/Bunch/include/picongpu/param/species.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/species.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/species.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param
  share/picongpu/examples/TransitionRadiation/include/picongpu/param/species.param
Labels: component: core, component: user input

#3229 Breathe: <4.15.0
  docs/requirements.txt
Labels: affects latest release, bug, component: third party, documentation

#3230 Backport: Breathe: <4.15.0
  docs/requirements.txt
Labels: bug, documentation

#3232 fix manual and automatic field specification
  lib/python/picongpu/plugins/plot_mpl/utils.py
Labels: bug, component: tools

#3228 Add profiles for the new GV100 GPUs on Hemera
  docs/source/install/profile.rst
  etc/picongpu/hemera-hzdr/fwkt_v100.tpl
  etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example
Labels: component: tools, machine/system

#3236 backport: fix manual and automatic field specification
  lib/python/picongpu/plugins/plot_mpl/utils.py
Labels: bug, component: tools

#3235 backport to 0.5.0-rc1
  docs/source/install/profile.rst
  etc/picongpu/hemera-hzdr/fwkt_v100.tpl
  etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example
  share/picongpu/dockerfiles/ubuntu-1604/Dockerfile
Labels: backend: cuda, bug, component: third party, machine/system
