Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2020-11, with the labels that each got.

#3408 Use Iteration::close() in openPMD plugin
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: component: plugin

#3398 Fix Ionization Current
  include/picongpu/particles/ionization/byField/IonizationCurrent/IonizationCurrent.hpp
  include/picongpu/particles/ionization/byField/IonizationCurrent/JIonizationCalc.hpp
Labels: bug, component: core

#3414 Improve clarity of comments concerning density calculation and profile interface
  include/picongpu/particles/ParticlesInit.kernel
  include/picongpu/particles/densityProfiles/IProfile.hpp
Labels: component: core, refactoring

#3415 Modify FreeFormulaImpl density profile to evalute a functor in centers of cells
  include/picongpu/particles/densityProfiles/FreeFormulaImpl.hpp
Labels: component: core

#3422 CI test with openpmd-api 0.12.0
  share/ci/bash.profile
Labels: component: tests

#3423 Clarify comments for generating momentums based on temperature
  include/picongpu/particles/manipulators/unary/Temperature.def
  include/picongpu/particles/manipulators/unary/Temperature.hpp
Labels: component: core, refactoring

#3419 Remove unused ParticlePatches class
  include/picongpu/plugins/common/particlePatches.cpp
  include/picongpu/plugins/common/particlePatches.hpp
Labels: component: plugin, refactoring

#3425 changes to support HIP
  include/picongpu/CMakeLists.txt
  include/picongpu/fields/FieldJ.tpp
  include/pmacc/nvidia/memory/MemoryInfo.hpp
Labels: refactoring

#3417 Add PML support to arbitrary-order FDTD field solver
  include/picongpu/fields/MaxwellSolver/ArbitraryOrderFDTDPML/ArbitraryOrderFDTDPML.def
  include/picongpu/fields/MaxwellSolver/ArbitraryOrderFDTDPML/ArbitraryOrderFDTDPML.hpp
  include/picongpu/fields/MaxwellSolver/Solvers.def
  include/picongpu/fields/MaxwellSolver/Solvers.hpp
  include/picongpu/param/fieldSolver.param
  share/picongpu/examples/FieldAbsorberTest/cmakeFlags
  share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/fieldSolver.param
  share/picongpu/examples/TransitionRadiation/include/picongpu/param/fieldSolver.param
Labels: component: core

#3386 Add a new compile-time test suite to test all particle pushers
  share/picongpu/tests/compileParticlePusher/README.rst
  share/picongpu/tests/compileParticlePusher/cmakeFlags
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/density.param
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/dimension.param
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/fileOutput.param
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/isaac.param
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/particle.param
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/precision.param
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/species.param
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/speciesDefinition.param
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/speciesInitialization.param
Labels: component: tests

#3427 Use openPMD::getVersion() function
  include/picongpu/versionFormat.cpp
Labels: component: core

#3431 Refactoring and cleanup of `species.param`
  README.md
  docs/source/index.rst
  docs/source/models/pic.rst
  docs/source/models/shapes.rst
  include/picongpu/algorithms/FieldToParticleInterpolationNative.hpp
  include/picongpu/param/species.param
  include/picongpu/particles/shapes.hpp
  include/picongpu/particles/shapes/P4S.hpp
  include/picongpu/particles/shapes/PCS.hpp
  include/picongpu/particles/shapes/PQS.hpp
  share/picongpu/examples/Bunch/include/picongpu/param/species.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/species.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/species.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param
  share/picongpu/examples/TransitionRadiation/include/picongpu/param/species.param
  share/picongpu/tests/XrayScattering/include/picongpu/param/species.param
  share/picongpu/tests/compileCurrentSolver/cmakeFlags
  share/picongpu/tests/compileCurrentSolver/include/picongpu/param/species.param
  share/picongpu/tests/compileParticlePusher/cmakeFlags
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/species.param
Labels: component: core, refactoring

#3435 Fix two typos in pic-create output
  bin/pic-create
Labels: component: tools

#3444 fix documentation
  docs/source/dev/styleguide.rst
Labels: bug, documentation

#3443 CI: more test on HZDR CI
  .gitlab-ci.yml
  .travis.yml
  docs/source/usage/workflows/memoryPerDevice.py
  include/pmacc/preprocessor/size.hpp
  share/ci/check_cpp_code_style.sh
  share/ci/run_clang-format.sh
  share/ci/run_pmacc_test.sh
Labels: component: tests

#3447 switch from Boost tests to Catch2
  .travis.yml
  include/picongpu/main.cpp
  include/picongpu/versionFormat.cpp
  include/pmacc/CMakeLists.txt
  include/pmacc/boost_workaround.hpp
  include/pmacc/test/TemplateUT.cpp
  include/pmacc/test/main.cpp
  include/pmacc/test/memory/HostBufferIntern/copyFrom.hpp
  include/pmacc/test/memory/HostBufferIntern/reset.hpp
  include/pmacc/test/memory/HostBufferIntern/setValue.hpp
  include/pmacc/test/memory/memoryUT.cpp
  include/pmacc/test/particles/IdProvider.hpp
  include/pmacc/test/particles/memory/SuperCell.hpp
  include/pmacc/test/particles/particlesUT.cpp
  include/pmacc/test/random/2DDistribution.cpp
  share/ci/compiler_clang.yml
  share/ci/compiler_clang_cuda.yml
  share/ci/compiler_gcc.yml
  share/ci/compiler_nvcc_cuda.yml
  share/ci/run_picongpu_tests.sh
  share/ci/run_pmacc_tests.sh
  thirdParty/catch2/catch_main/CMakeLists.txt
  thirdParty/catch2/catch_main/src/CatchMain.cpp
  thirdParty/catch2/include/catch2/catch.hpp
Labels: component: tests, refactoring

#3451 gitlab pipeline badges
  README.md
Labels: documentation

#3445 fix documentation for `git clang-format`
  docs/COMMIT.md
  docs/source/dev/styleguide.rst
Labels: bug, documentation

#3455 HIP: fix RNG method XorMin
  include/pmacc/random/methods/XorMin.hpp
Labels: backend: hip, bug, component: PMacc

#3456 expose HIP backend
  bin/pic-configure
Labels: backend: hip, component: tools

#3450 CI: auto adjust parallelism
  share/ci/run_picongpu_tests.sh
Labels: component: tests

#3453 fix pic-compile
  bin/pic-compile
Labels: bug, component: tools
