Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2020-01, with the labels that each got.

#3141 Fix a typo in exchange communication tag status output
  include/pmacc/memory/buffers/GridBuffer.hpp
Labels: documentation

#3113 Fix doc rad plugin units and factors
  docs/source/usage/plugins/radiation.rst
Labels: component: plugin, documentation

#3151 add PhD thesis reference in radiation plugin
  README.md
  docs/source/usage/plugins/radiation.rst
Labels: documentation

#3154 Add missing const to some GridController getters
  include/pmacc/mappings/simulation/GridController.hpp
Labels: refactoring

#3152 fix taurus profile
  etc/picongpu/taurus-tud/V100.tpl
  etc/picongpu/taurus-tud/V100_picongpu.profile.example
  etc/picongpu/taurus-tud/V100_restart.tpl
Labels: affects latest release, bug
