Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2020-12, with the labels that each got.

#3457 Optimize atomic functor for HIP
  include/pmacc/nvidia/atomic.hpp
  include/pmacc/nvidia/functors/Atomic.hpp
Labels: backend: hip, component: PMacc

#3458 Update supported CUDA versions
  INSTALL.rst
  include/pmacc/PMaccConfig.cmake
Labels: documentation

#3452 CI: skip compile
  share/ci/generate_reduced_matrix.sh
  share/ci/pr_has_label.sh
Labels: component: tests

#3462 Extend user documentation with a warning about tools being Linux-only
  USAGE.rst
Labels: CI:no-compile, component: tools, documentation

#3459 [JUWELS] Update modules in PIConGPU profiles.
  etc/picongpu/juwels-jsc/batch_picongpu.profile.example
  etc/picongpu/juwels-jsc/gpus_picongpu.profile.example
Labels: machine/system

#3467 fix deprecation warnings
  include/picongpu/plugins/output/GatherSlice.hpp
  include/picongpu/plugins/output/header/MessageHeader.hpp
  include/pmacc/dimensions/DataSpace.hpp
  include/pmacc/eventSystem/events/EventTask.hpp
  include/pmacc/mappings/simulation/Selection.hpp
  include/pmacc/mappings/simulation/SubGrid.hpp
  include/pmacc/math/complex/Complex.hpp
  include/pmacc/math/vector/Vector.hpp
  include/pmacc/memory/buffers/DeviceBufferIntern.hpp
  include/pmacc/memory/buffers/HostBufferIntern.hpp
Labels: component: PMacc, component: core, warning

#3465 Scale particle exchange buf
  include/picongpu/_defaultParam.loader
  include/picongpu/param/memory.param
  include/picongpu/param/speciesAttributes.param
  include/picongpu/particles/Particles.hpp
  include/picongpu/particles/Particles.tpp
  share/picongpu/examples/FoilLCT/include/picongpu/param/memory.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/memory.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/memory.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/memory.param
Labels: component: user input, refactoring

#3469 CI: new compiler and CUDA
  share/ci/compiler_clang.yml
  share/ci/compiler_clang_cuda.yml
  share/ci/compiler_gcc.yml
  share/ci/compiler_nvcc_cuda.yml
  share/ci/n_wise_generator.py
Labels: component: tests

#3472 CI: latest container v1.1
  share/ci/bash.profile
  share/ci/compiler_clang.yml
  share/ci/compiler_clang_cuda.yml
  share/ci/compiler_gcc.yml
  share/ci/compiler_nvcc_cuda.yml
Labels: component: tests

#3471 disable async device streams for CPU backends
  bin/pic-configure
Labels: backend: omp2b, backend: serial, backend: tbb

#3466 add SPEC benchmark example
  .gitlab-ci.yml
  share/ci/generate_reduced_matrix.sh
  share/ci/run_picongpu_tests.sh
  share/picongpu/benchmarks/SPEC/etc/picongpu/1.cfg
  share/picongpu/benchmarks/SPEC/include/picongpu/param/density.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/fileOutput.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/grid.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/isaac.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/memory.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/particle.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/species.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/speciesDefinition.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/speciesInitialization.param
Labels: component: examples

#3477 Fix return value of main() in mpiInfo
  include/mpiInfo/mpiInfo.cpp
Labels: component: tools, warning

#3476 Rename picongpu::MySimulation to picongpu::Simulation
  docs/source/dev/picongpu.rst
  include/picongpu/param/components.param
  include/picongpu/particles/bremsstrahlung/ScaledSpectrum.hpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/unitless/starter.unitless
  share/picongpu/examples/ThermalTest/include/picongpu/ThermalTestSimulation.hpp
Labels: refactoring

#3478 Extend reminder to load environment in the docs with instructions for spack
  USAGE.rst
Labels: CI:no-compile, documentation, install: spack

#3474 update to latest cupla with alpaka0.6.0rc4
  thirdParty/cupla/.gitlab-ci.yml
  thirdParty/cupla/alpaka/.github/workflows/ci.yml
  thirdParty/cupla/alpaka/CONTRIBUTING.md
  thirdParty/cupla/alpaka/README.md
  thirdParty/cupla/alpaka/docs/source/dev/style.rst
  thirdParty/cupla/alpaka/example/CMakeLists.txt
  thirdParty/cupla/alpaka/example/openMPSchedule/CMakeLists.txt
  thirdParty/cupla/alpaka/example/openMPSchedule/src/openMPSchedule.cpp
  thirdParty/cupla/alpaka/include/alpaka/alpaka.hpp
  thirdParty/cupla/alpaka/include/alpaka/core/Omp5.hpp
  thirdParty/cupla/alpaka/include/alpaka/core/OmpSchedule.hpp
  thirdParty/cupla/alpaka/include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
  thirdParty/cupla/alpaka/include/alpaka/kernel/Traits.hpp
  thirdParty/cupla/alpaka/include/alpaka/meta/Void.hpp
  thirdParty/cupla/alpaka/script/push_doc.sh
  thirdParty/cupla/alpaka/test/CMakeLists.txt
  thirdParty/cupla/alpaka/test/catch_main/CMakeLists.txt
  thirdParty/cupla/alpaka/test/common/CMakeLists.txt
  thirdParty/cupla/alpaka/test/common/src/Dummy.cpp
  thirdParty/cupla/alpaka/test/unit/core/src/BoostPredefTest.cpp
  thirdParty/cupla/alpaka/test/unit/core/src/ConceptsTest.cpp
  thirdParty/cupla/alpaka/test/unit/core/src/OmpScheduleTest.cpp
  thirdParty/cupla/alpaka/test/unit/kernel/src/KernelWithOmpSchedule.cpp
  thirdParty/cupla/alpaka/test/unit/meta/src/VoidTest.cpp
  thirdParty/cupla/script/compiler_base.yml
Labels: component: third party

#3475 Fix the scheme of updating convolutional B in PML by half time step
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.kernel
Labels: affects latest release, component: core

#3480 remove openPMD 0.11.0 module for defq
  etc/picongpu/hemera-hzdr/defq_picongpu.profile.example
Labels: CI:no-compile, machine/system
