Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2020-03, with the labels that each got.

#3191 Correct jupyter widget example
  docs/source/usage/plugins/phaseSpace.rst
Labels: documentation

#3143 EnergyHistogram: allow non-keyword arguments
  docs/source/usage/plugins/energyHistogram.rst
  lib/python/picongpu/plugins/data/base_reader.py
Labels: bug, component: plugin, component: tools, documentation

#3194 fix typo: `UNIT_LENGHT` to `UNIT_LENGTH`
  include/picongpu/particles/ParticlesInit.kernel
Labels: documentation

#3192 Change imread import from scipy.misc to imageio
  lib/python/picongpu/plugins/data/png.py
  lib/python/picongpu/plugins/data/requirements.txt
Labels: component: tools

#3197 Python: fix set rundir options for widgets, EnergyHistogram all zeros
  lib/python/picongpu/plugins/jupyter_widgets/base_widget.py
  lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py
Labels: component: tools

#3209 Add forgotten CFL check for YeePML
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
Labels: bug, component: core

#3208 Create a new absorber description interface
  include/picongpu/fields/LaserPhysics.hpp
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
  include/picongpu/fields/absorber/Absorber.hpp
  include/picongpu/fields/absorber/ExponentialDamping.hpp
  include/picongpu/fields/absorber/NumCells.hpp
  include/picongpu/plugins/adios/WriteMeta.hpp
  include/picongpu/plugins/hdf5/WriteMeta.hpp
  include/picongpu/simulation/control/DomainAdjuster.hpp
Labels: bug, component: core

#3216 backport for 0.5.0 release rc1
  include/picongpu/fields/LaserPhysics.hpp
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
  include/picongpu/fields/absorber/Absorber.hpp
  include/picongpu/fields/absorber/ExponentialDamping.hpp
  include/picongpu/fields/absorber/NumCells.hpp
  include/picongpu/plugins/adios/WriteMeta.hpp
  include/picongpu/plugins/hdf5/WriteMeta.hpp
  include/picongpu/simulation/control/DomainAdjuster.hpp
Labels: bug

#3214 Fix a typo in the reference to [Pausch2018]
  docs/source/usage/plugins.rst
Labels: documentation

#3218 Fix wrong exponential absorber strength
  include/picongpu/fields/absorber/ExponentialDamping.hpp
Labels: bug, component: core

#3215 Replace remaining cupla renamings with calls to cupla API
  docs/source/prgpatterns/lockstep.rst
  include/picongpu/fields/FieldJ.kernel
  include/picongpu/fields/FieldTmp.kernel
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.kernel
  include/picongpu/particles/Particles.kernel
  include/picongpu/particles/creation/creation.kernel
  include/picongpu/plugins/Emittance.hpp
  include/picongpu/plugins/EnergyParticles.hpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.kernel
  include/pmacc/nvidia/reduce/Reduce.hpp
  include/pmacc/particles/ParticlesBase.kernel
  include/pmacc/particles/operations/CountParticles.hpp
Labels: bug, component: PMacc, component: core, documentation

#3198 changelog for 0.5.0
  CHANGELOG.md
Labels: documentation
