Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2020-06, with the labels that each got.

#3265 Add JetBrains project dir to .gitignore.
  .gitignore
Labels: component: tools, warning

#3268 Doc: C++14
  README.md
  include/mpiInfo/CMakeLists.txt
  include/picongpu/CMakeLists.txt
  include/pmacc/CMakeLists.txt
  include/pmacc/PMaccConfig.cmake
  share/pmacc/examples/gameOfLife2D/CMakeLists.txt
  src/tools/png2gas/CMakeLists.txt
  src/tools/splash2txt/CMakeLists.txt
Labels: documentation

#3190 tbg pathlist
  bin/tbg
Labels: component: tools

#2966 openPMD Plugin
  INSTALL.rst
  docs/TBG_macros.cfg
  docs/source/usage/plugins.rst
  docs/source/usage/plugins/checkpoint.rst
  docs/source/usage/plugins/openPMD.cfg
  docs/source/usage/plugins/openPMD.rst
  include/picongpu/CMakeLists.txt
  include/picongpu/plugins/Checkpoint.hpp
  include/picongpu/plugins/PluginController.hpp
  include/picongpu/plugins/openPMD/NDScalars.hpp
  include/picongpu/plugins/openPMD/WriteMeta.hpp
  include/picongpu/plugins/openPMD/WriteSpecies.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.def
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/picongpu/plugins/openPMD/restart/LoadParticleAttributesFromOpenPMD.hpp
  include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp
  include/picongpu/plugins/openPMD/restart/RestartFieldLoader.hpp
  include/picongpu/plugins/openPMD/writer/ParticleAttribute.hpp
  include/picongpu/versionFormat.cpp
  share/picongpu/examples/FoilLCT/etc/picongpu/4.cfg
  share/picongpu/examples/FoilLCT/etc/picongpu/8.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/1.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/4.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/8.cfg
  share/picongpu/examples/SingleParticleTest/etc/picongpu/1.cfg
  share/picongpu/examples/WarmCopper/etc/picongpu/1.cfg
Labels: component: plugin, refactoring

#3272 refactor pmacc identifier and alias
  include/picongpu/param/speciesAttributes.param
  include/pmacc/identifier/alias.hpp
  include/pmacc/identifier/identifier.hpp
Labels: bug, refactoring

#3271 fix openPMD plugin doc
  docs/source/usage/plugins/openPMD.rst
Labels: bug, documentation

#3274 refactor `ConstVector`
  include/pmacc/math/ConstVector.hpp
  include/pmacc/math/vector/Vector.hpp
Labels: backend: C++ threads, backend: omp2b, backend: serial, backend: tbb, component: PMacc
