Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2021-05, with the labels that each got.

#3610 Updated defq profile for hemera/defq
  etc/picongpu/hemera-hzdr/defq_picongpu.profile.example
Labels: machine/system

#3608 Rename picongpu::particles::CallFunctor to pmacc::functor::Call
  include/picongpu/particles/InitFunctors.hpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/simulation/stage/IterationStart.hpp
  include/pmacc/functor/Call.hpp
  include/pmacc/functor/Interface.hpp
Labels: component: PMacc, component: core, refactoring

#3612 Add option for hemera low (gpu) partitions
  etc/picongpu/hemera-hzdr/fwkt_v100.tpl
  etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example
  etc/picongpu/hemera-hzdr/gpu.tpl
  etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k20.tpl
  etc/picongpu/hemera-hzdr/k20_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k20_restart.tpl
  etc/picongpu/hemera-hzdr/k80.tpl
  etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k80_restart.tpl
Labels: machine/system

#3611 Refactor common field absorber implementation
  include/picongpu/fields/LaserPhysics.hpp
  include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
  include/picongpu/fields/absorber/Absorber.hpp
  include/picongpu/fields/absorber/Absorber.tpp
  include/picongpu/fields/absorber/ExponentialDamping.hpp
  include/picongpu/fields/absorber/Pml.hpp
  include/picongpu/plugins/adios/WriteMeta.hpp
  include/picongpu/plugins/common/openPMDWriteMeta.hpp
  include/picongpu/simulation/control/DomainAdjuster.hpp
Labels: component: core, refactoring

#3592 Incident field generation (aka laser antenna)
  docs/source/usage/param/core.rst
  include/picongpu/_defaultParam.loader
  include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
  include/picongpu/fields/incidentField/Profiles.def
  include/picongpu/fields/incidentField/Profiles.hpp
  include/picongpu/fields/incidentField/Solver.hpp
  include/picongpu/fields/incidentField/Solver.kernel
  include/picongpu/fields/incidentField/Traits.hpp
  include/picongpu/param/incidentField.param
  share/picongpu/examples/IncidentField/cmakeFlags
  share/picongpu/examples/IncidentField/etc/picongpu/1.cfg
  share/picongpu/examples/IncidentField/etc/picongpu/4.cfg
  share/picongpu/examples/IncidentField/include/picongpu/param/dimension.param
  share/picongpu/examples/IncidentField/include/picongpu/param/fieldSolver.param
  share/picongpu/examples/IncidentField/include/picongpu/param/grid.param
  share/picongpu/examples/IncidentField/include/picongpu/param/incidentField.param
  share/picongpu/examples/IncidentField/include/picongpu/param/pml.param
  share/picongpu/examples/IncidentField/include/picongpu/param/png.param
Labels: component: core, component: examples, component: user input

#3615 fix broken compile
  include/picongpu/fields/incidentField/Solver.hpp
Labels: bug, component: core

#3614 CMake: fix lib splash selection
  include/picongpu/CMakeLists.txt
Labels: bug, component: tools

#3617 Move PML implementation
  include/picongpu/fields/MaxwellSolver/YeePML/YeePML.hpp
  include/picongpu/fields/absorber/Absorber.hpp
  include/picongpu/fields/absorber/pml/Field.hpp
  include/picongpu/fields/absorber/pml/Field.tpp
  include/picongpu/fields/absorber/pml/Parameters.hpp
  include/picongpu/fields/absorber/pml/Solver.hpp
  include/picongpu/fields/absorber/pml/Solver.kernel
  include/picongpu/plugins/adios/ADIOSWriter.hpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/unitless/checkpoints.unitless
Labels: component: core, refactoring

#3621 Fix syntax error in SingleParticleTest configuration file.
  share/picongpu/examples/SingleParticleTest/etc/picongpu/1.cfg
Labels: bug, component: examples

#3619 fix processing of outgoing particles by multi plugins
  include/picongpu/plugins/multi/ISlave.hpp
  include/picongpu/plugins/multi/Master.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
Labels: affects latest release, bug

#3626 fix broken OpenPMD IO plugin
  include/picongpu/plugins/openPMD/WriteSpecies.hpp
Labels: bug, component: plugin

#3627 Profile for spock at ORNL
  etc/picongpu/spock-ornl/caar.tpl
  etc/picongpu/spock-ornl/caar_picongpu.profile.example
Labels: CI:no-compile, machine/system

#3632 device oversubscription
  docs/TBG_macros.cfg
  docs/source/expert/deviceOversubscription.rst
  docs/source/index.rst
  include/picongpu/simulation/control/Simulation.hpp
  include/pmacc/device/MemoryInfo.hpp
Labels: component: PMacc, component: core, documentation
