Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2021-04, with the labels that each got.

#3575 fix warning: unreachable code
  include/picongpu/simulation/stage/CurrentBackground.hpp
  include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp
Labels: component: core, warning

#3578 Updatet documentation of AOFDTD
  docs/source/models/AOFDTD.rst
Labels: documentation

#3577 Fix Particles<>::exchangeMemorySize
  include/picongpu/particles/Particles.tpp
Labels: bug, component: core

#3580 Fix openPMD plugin for non-GPU builds
  include/picongpu/plugins/openPMD/WriteSpecies.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: bug, component: plugin

#3574 introduce filtered particleToGrid algorithm
  include/picongpu/fields/FieldTmp.hpp
  include/picongpu/fields/FieldTmp.kernel
  include/picongpu/fields/FieldTmp.tpp
  include/picongpu/fields/Fields.def
  include/picongpu/param/fileOutput.param
  include/picongpu/param/isaac.param
  include/picongpu/particles/filter/RelativeGlobalDomainPosition.def
  include/picongpu/particles/filter/RelativeGlobalDomainPosition.hpp
  include/picongpu/particles/manipulators/binary/DensityWeighting.def
  include/picongpu/particles/manipulators/binary/ProtonTimesWeighting.def
  include/picongpu/particles/manipulators/binary/UnboundElectronsTimesWeighting.def
  include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.def
  include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.hpp
  include/picongpu/particles/particleToGrid/FilteredDerivedAttribute.hpp
  include/picongpu/plugins/IsaacPlugin.hpp
  include/picongpu/plugins/adios/ADIOSWriter.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  share/picongpu/examples/LaserWakefield/include/picongpu/param/particle.param
Labels: component: core, component: user input

#3341 JUWELS booster profile
  etc/picongpu/juwels-jsc/booster.tpl
  etc/picongpu/juwels-jsc/booster_picongpu.profile.example
Labels: CI:no-compile, component: tools, machine/system

#3583 documentation: add support for boost 1.74.0
  INSTALL.rst
Labels: CI:no-compile, documentation

#3582 remove interface `DataConnector::releaseData()`
  include/picongpu/fields/FieldJ.tpp
  include/picongpu/particles/InitFunctors.hpp
  include/picongpu/particles/Particles.tpp
  include/picongpu/particles/ParticlesFunctors.hpp
  include/picongpu/particles/bremsstrahlung/Bremsstrahlung.tpp
  include/picongpu/particles/collision/InterCollision.hpp
  include/picongpu/particles/collision/IntraCollision.hpp
  include/picongpu/particles/flylite/helperFields/LocalDensityFunctors.hpp
  include/picongpu/particles/flylite/helperFields/LocalEnergyHistogramFunctors.hpp
  include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
  include/picongpu/plugins/BinEnergyParticles.hpp
  include/picongpu/plugins/ChargeConservation.tpp
  include/picongpu/plugins/CountParticles.hpp
  include/picongpu/plugins/Emittance.hpp
  include/picongpu/plugins/EnergyParticles.hpp
  include/picongpu/plugins/IntensityPlugin.hpp
  include/picongpu/plugins/IsaacPlugin.hpp
  include/picongpu/plugins/PhaseSpace/PhaseSpace.tpp
  include/picongpu/plugins/PositionsParticles.hpp
  include/picongpu/plugins/SumCurrents.hpp
  include/picongpu/plugins/adios/ADIOSWriter.hpp
  include/picongpu/plugins/adios/WriteSpecies.hpp
  include/picongpu/plugins/adios/restart/RestartFieldLoader.hpp
  include/picongpu/plugins/makroParticleCounter/PerSuperCell.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/picongpu/plugins/openPMD/restart/RestartFieldLoader.hpp
  include/picongpu/plugins/output/WriteSpeciesCommon.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
  include/picongpu/plugins/radiation/Radiation.hpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.hpp
  include/picongpu/plugins/xrayScattering/XrayScattering.hpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/simulation/stage/CurrentBackground.hpp
  include/picongpu/simulation/stage/CurrentDeposition.hpp
  include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp
  include/picongpu/simulation/stage/CurrentReset.hpp
  include/picongpu/simulation/stage/FieldBackground.hpp
  include/pmacc/dataManagement/DataConnector.hpp
  include/pmacc/particles/algorithm/CallForEach.hpp
  include/pmacc/random/RNGProvider.tpp
  share/picongpu/examples/ThermalTest/include/picongpu/ThermalTestSimulation.hpp
Labels: component: PMacc, component: core, refactoring

#3585 fix collision compile error
  include/picongpu/unitless/collision.unitless
  share/picongpu/tests/CollisionsThermalisation/cmakeFlags
  share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/collision.param
Labels: bug, component: core

#3570 Reimplement MacroParticleCounter in openPMD
  include/picongpu/plugins/PluginController.hpp
  include/picongpu/plugins/common/openPMDAttributes.hpp
  include/picongpu/plugins/common/openPMDVersion.def
  include/picongpu/plugins/common/openPMDWriteMeta.hpp
  include/picongpu/plugins/makroParticleCounter/PerSuperCell.hpp
  include/picongpu/plugins/openPMD/NDScalars.hpp
  include/picongpu/plugins/openPMD/WriteSpecies.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: component: plugin, refactoring

#3545 Compatibility to new unified ISAAC naming scheme
  include/picongpu/CMakeLists.txt
  include/picongpu/plugins/IsaacPlugin.hpp
  share/ci/bash.profile
  share/ci/compiler_clang.yml
  share/ci/compiler_gcc.yml
  share/ci/compiler_nvcc_cuda.yml
  share/ci/install/isaac.sh
Labels: component: plugin, component: tests

#3589 Fix wrong ifdef guard in enabling the macroparticle counter plugin
  include/picongpu/plugins/PluginController.hpp
Labels: bug, component: plugin

#3590 Update juwels-booster profile to include all dependencies
  etc/picongpu/juwels-jsc/booster_picongpu.profile.example
Labels: CI:no-compile, component: user input, install, machine/system

#3586 CMake: add option to enforce dependencies
  include/picongpu/CMakeLists.txt
  share/ci/run_picongpu_tests.sh
  share/picongpu/examples/WarmCopper/cmakeFlags
Labels: component: tools, refactoring

#3599 set current solver EmZ as default
  include/picongpu/param/species.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param
  share/picongpu/tests/XrayScattering/include/picongpu/param/species.param
  share/picongpu/tests/compileCurrentSolver/include/picongpu/param/species.param
Labels: component: examples, component: user input

#3597 SPEC bechmark: add new configurations
  share/picongpu/benchmarks/SPEC/cmakeFlags
  share/picongpu/benchmarks/SPEC/include/picongpu/param/memory.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/precision.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/species.param
Labels: component: tests

#3600 Add brief user documentation for boundary conditions
  docs/source/usage/workflows.rst
  docs/source/usage/workflows/boundaryConditions.rst
Labels: documentation

#3446 Add a check for Debye length resolution
  include/picongpu/param/grid.param
  include/picongpu/particles/debyeLength/Check.hpp
  include/picongpu/particles/debyeLength/Estimate.hpp
  include/picongpu/particles/debyeLength/Estimate.kernel
  include/picongpu/particles/manipulators/unary/Temperature.def
  include/picongpu/simulation/control/Simulation.hpp
  share/picongpu/examples/FoilLCT/include/picongpu/param/grid.param
  share/picongpu/tests/XrayScattering/include/picongpu/param/grid.param
Labels: component: core

#3603 fix compile: debye length
  include/picongpu/particles/debyeLength/Estimate.hpp
Labels: bug, component: core

#3602 Update AOFDTD manual section
  docs/source/models/AOFDTD.rst
Labels: CI:no-compile, documentation

#3601 update grid.param file doxygen string
  include/picongpu/param/grid.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/grid.param
  share/picongpu/examples/Bremsstrahlung/include/picongpu/param/grid.param
  share/picongpu/examples/Bunch/include/picongpu/param/grid.param
  share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/grid.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/grid.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/grid.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/grid.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/grid.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/grid.param
  share/picongpu/examples/TransitionRadiation/include/picongpu/param/grid.param
  share/picongpu/examples/WarmCopper/include/picongpu/param/grid.param
  share/picongpu/examples/WeibelTransverse/include/picongpu/param/grid.param
  share/picongpu/tests/CollisionsBeamRelaxation/include/picongpu/param/grid.param
  share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/grid.param
  share/picongpu/tests/XrayScattering/include/picongpu/param/grid.param
  share/picongpu/tests/compileFieldSolver/include/picongpu/param/grid.param
Labels: documentation

#3606 screen output: print milliseconds
  include/pmacc/simulationControl/SimulationHelper.hpp
Labels: component: PMacc
