Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2021-07, with the labels that each got.

#3665 Fix kernelName in kernelEvents.hpp
  include/pmacc/eventSystem/events/kernelEvents.hpp
Labels: bug, component: PMacc

#3669 Update documentation of memory calculator
  lib/python/picongpu/utils/memory_calculator.py
Labels: CI:no-compile, component: tools

#3655 Replace FromHDF5Impl density with FromOpenPMDImpl
  include/picongpu/param/density.param
  include/picongpu/particles/densityProfiles/FromHDF5Impl.hpp
  include/picongpu/particles/densityProfiles/FromOpenPMDImpl.def
  include/picongpu/particles/densityProfiles/FromOpenPMDImpl.hpp
  include/picongpu/particles/densityProfiles/profiles.def
  include/picongpu/particles/densityProfiles/profiles.hpp
Labels: component: core

#3560 ParticleCalorimeter in openPMD
  docs/source/usage/plugins/particleCalorimeter.rst
  include/picongpu/plugins/PluginController.hpp
  include/picongpu/plugins/common/openPMDWriteMeta.hpp
  include/picongpu/plugins/makroParticleCounter/PerSuperCell.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
  share/picongpu/examples/Bremsstrahlung/bin/plot_energy_histogram.py
  share/picongpu/examples/Bremsstrahlung/bin/plot_particle_calorimeter.py
Labels: component: plugin, refactoring

#3671 spock-ornl: compile for MI100 architecture only
  etc/picongpu/spock-ornl/caar_picongpu.profile.example
Labels: CI:no-compile, machine/system

#3670 spock-ornl: fix compile warning
  etc/picongpu/spock-ornl/caar_picongpu.profile.example
Labels: CI:no-compile, machine/system, warning

#3668 Extend the basic usage with beginner tips for making an own simulation
  USAGE.rst
Labels: CI:no-compile, documentation

#3667 Extend docs for the openPMD plugin regarding --openPMD.source
  docs/source/usage/plugins/openPMD.rst
Labels: CI:no-compile, component: user input, documentation

#3672 Make PML default field absorber
  docs/source/usage/workflows/boundaryConditions.rst
  include/picongpu/fields/absorber/Absorber.hpp
  include/picongpu/fields/absorber/Absorber.tpp
  include/picongpu/fields/absorber/none/None.hpp
  include/picongpu/param/fieldAbsorber.param
  include/picongpu/simulation/stage/FieldAbsorber.hpp
  share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/fieldAbsorber.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/fieldAbsorber.param
Labels: component: core, component: examples, component: user input

#3678 OpenPMD plugin: fix attribute charge/mass
  include/picongpu/plugins/openPMD/WriteSpecies.hpp
Labels: bug, component: plugin

#3680 Update summit profile
  etc/picongpu/summit-ornl/gpu_picongpu.profile.example
Labels: CI:no-compile, component: tools, machine/system

#3682 change how QuietImpl positions reduced number of particles
  include/picongpu/particles/startPosition/QuietImpl.hpp
Labels: bug, component: core

#3638 fix observation direction precision to float_X
  include/picongpu/param/radiationObserver.param
  share/picongpu/examples/Bunch/include/picongpu/param/radiationObserver.param
  share/picongpu/examples/KelvinHelmholtz/include/picongpu/param/radiationObserver.param
Labels: affects latest release, bug, component: examples, component: plugin

#3683 add radiation cases to SPEC benchmark
  share/picongpu/benchmarks/SPEC/cmakeFlags
  share/picongpu/benchmarks/SPEC/etc/picongpu/1_radiation.cfg
  share/picongpu/benchmarks/SPEC/include/picongpu/param/radiation.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/radiationObserver.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/speciesDefinition.param
Labels: component: tests

#3675 openPMD plugin: do not use JSON configurations when restarting #3674
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: bug, component: plugin

#3687 use IUnary with filters in collisions and FieldTmp
  include/picongpu/fields/FieldTmp.tpp
  include/picongpu/particles/collision/InterCollision.hpp
  include/picongpu/particles/collision/IntraCollision.hpp
Labels: component: core, refactoring

#3648 refactor field update functor
  include/picongpu/fields/MaxwellSolver/FDTD/FDTD.hpp
  include/picongpu/fields/MaxwellSolver/FDTD/FDTD.kernel
  include/picongpu/fields/MaxwellSolver/Yee/StencilFunctor.hpp
  include/picongpu/fields/absorber/pml/Pml.kernel
Labels: component: core, refactoring

#3688 fix getting unitSI for amplitude
  lib/python/picongpu/plugins/data/radiation.py
Labels: CI:no-compile, component: plugin, component: tools

#3693 Fix: RTD Docutils Build
  docs/requirements.txt
Labels: CI:no-compile, bug, component: third party, documentation

#3695 update h5py data-getter syntax in radiation python module
  lib/python/picongpu/plugins/data/radiation.py
Labels: CI:no-compile, affects latest release, bug, component: plugin, component: tools

#3697 Ascent (ORNL) setup
  docs/source/install/profile.rst
  etc/picongpu/ascent-ornl/gpu_batch.tpl
  etc/picongpu/ascent-ornl/gpu_picongpu.profile.example
Labels: CI:no-compile, machine/system

#3691 remove ADIOS1 IO plugin
  INSTALL.rst
  README.md
  docs/TBG_macros.cfg
  docs/source/install/libraryDependencies.dot
  docs/source/install/profile.rst
  docs/source/postprocessing/openPMD.rst
  docs/source/postprocessing/python.rst
  docs/source/usage/plugins.rst
  docs/source/usage/plugins/adios.rst
  docs/source/usage/plugins/checkpoint.rst
  docs/source/usage/plugins/openPMD.rst
  docs/source/usage/plugins/positionsParticles.rst
  etc/picongpu/cori-nersc/knl_picongpu.profile.example
  etc/picongpu/davide-cineca/gpu_picongpu.profile.example
  etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example
  etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k20_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k20_restart.tpl
  etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
  etc/picongpu/jureca-jsc/batch_picongpu.profile.example
  etc/picongpu/jureca-jsc/booster_picongpu.profile.example
  etc/picongpu/jureca-jsc/gpus_picongpu.profile.example
  etc/picongpu/juwels-jsc/batch_picongpu.profile.example
  etc/picongpu/juwels-jsc/booster_picongpu.profile.example
  etc/picongpu/juwels-jsc/gpus_picongpu.profile.example
  etc/picongpu/pizdaint-cscs/picongpu.profile.example
  etc/picongpu/taurus-tud/V100_picongpu.profile.example
  etc/picongpu/taurus-tud/V100_restart.tpl
  include/picongpu/CMakeLists.txt
  include/picongpu/plugins/Checkpoint.hpp
  include/picongpu/plugins/PluginController.hpp
  include/picongpu/plugins/adios/ADIOSCountParticles.hpp
  include/picongpu/plugins/adios/ADIOSWriter.def
  include/picongpu/plugins/adios/ADIOSWriter.hpp
  include/picongpu/plugins/adios/NDScalars.hpp
  include/picongpu/plugins/adios/WriteMeta.hpp
  include/picongpu/plugins/adios/WriteSpecies.hpp
  include/picongpu/plugins/adios/restart/LoadParticleAttributesFromADIOS.hpp
  include/picongpu/plugins/adios/restart/LoadSpecies.hpp
  include/picongpu/plugins/adios/restart/ReadAttribute.hpp
  include/picongpu/plugins/adios/restart/RestartFieldLoader.hpp
  include/picongpu/plugins/adios/writer/ParticleAttribute.hpp
  include/picongpu/plugins/adios/writer/ParticleAttributeSize.hpp
  include/picongpu/plugins/common/stringHelpers.cpp
  include/picongpu/plugins/common/stringHelpers.hpp
  include/picongpu/plugins/makroParticleCounter/PerSuperCell.hpp
  include/picongpu/plugins/xrayScattering/XrayScattering.hpp
  include/picongpu/traits/AdiosToPIC.hpp
  include/picongpu/traits/AdiosToPIC.tpp
  include/picongpu/traits/PICToAdios.hpp
  include/picongpu/traits/PICToAdios.tpp
  include/picongpu/versionFormat.cpp
  libraryDependencies.png
  share/ci/bash.profile
  share/ci/run_picongpu_tests.sh
  share/picongpu/examples/FoilLCT/etc/picongpu/4_isaac.cfg
  share/picongpu/examples/FoilLCT/etc/picongpu/8_isaac.cfg
Labels: component: tests, component: user input, documentation, refactoring

#3704 Fix TWTS implementations
  include/picongpu/fields/background/templates/TWTS/BField.hpp
  include/picongpu/fields/background/templates/TWTS/BField.tpp
  include/picongpu/fields/background/templates/TWTS/EField.hpp
  include/picongpu/fields/background/templates/twtsfast/BField.hpp
  include/picongpu/fields/background/templates/twtsfast/BField.tpp
  include/picongpu/fields/background/templates/twtsfast/EField.hpp
Labels: CI:no-compile, affects latest release, bug, component: core

#3694 Cori: Add DGX (A100) Profile
  docs/source/install/profile.rst
  etc/picongpu/cori-nersc/a100.tpl
  etc/picongpu/cori-nersc/a100_picongpu.profile.example
Labels: CI:no-compile, documentation, machine/system

#3703 Fix inaccurate supercell loop stop condition in the radiation kernel
  include/picongpu/plugins/radiation/Radiation.kernel
Labels: bug, component: plugin

#3698 Summit template and documentation for asynchronous writing via ADIOS2 SST
  docs/source/usage/plugins/openPMD.rst
  etc/picongpu/summit-ornl/gpu_batch_pipe.tpl
  share/picongpu/examples/KelvinHelmholtz/etc/picongpu/6_pipe.cfg
Labels: CI:no-compile, documentation

#3706 Fix broken includes of doxygen into readthedocs
  docs/source/dev/pmacc.rst
  docs/source/prgpatterns/lockstep.rst
Labels: CI:no-compile, bug, documentation

#3699 Fix FromOpenPMD density and make it account for axisLabels attribute
  include/picongpu/param/density.param
  include/picongpu/particles/densityProfiles/FromOpenPMDImpl.hpp
Labels: bug, component: core, component: user input, refactoring
