Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2021-08, with the labels that each got.

#3715 CI: fix clang-format and ROCm
  .gitlab-ci.yml
  share/ci/compiler_hipcc.yml
  share/ci/n_wise_generator.py
Labels: bug, component: tests

#3710 clang-format included in suggested contribution pipeline
  CONTRIBUTING.md
Labels: documentation, CI:no-compile

#3718 pmacc ExchangeTypeToRank changed from protected to public
  include/pmacc/communication/CommunicatorMPI.hpp
Labels: component: PMacc, refactoring

#3721 change wrong default
  docs/TBG_macros.cfg
Labels: bug, documentation, CI:no-compile

#3725 switch to new 'chdir' SLURM command
  etc/picongpu/taurus-tud/k80.tpl
Labels: bug, machine/system, CI:no-compile

#3730 Fix outdated exception message for openPMD plugin with ADIOS1
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: component: plugin

#3719 Isaac plugin vector field vis compatility and benchmarking
  docs/TBG_macros.cfg
  docs/source/usage/plugins/isaac.rst
  include/picongpu/param/isaac.param
  include/picongpu/plugins/IsaacPlugin.hpp
  share/ci/install/isaac.sh
  share/picongpu/benchmarks/SPEC/include/picongpu/param/isaac.param
  share/picongpu/tests/compileCurrentSolver/include/picongpu/param/isaac.param
  share/picongpu/tests/compileFieldSolver/include/picongpu/param/isaac.param
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/isaac.param
Labels: component: plugin, refactoring

#3729 Fix taurus-tud k80 profile
  etc/picongpu/taurus-tud/k80_picongpu.profile.example
Labels: machine/system, CI:no-compile

#3731 Fix warning: Attribute /date cannot be overwritten (openPMD plugin)
  include/picongpu/plugins/common/openPMDWriteMeta.hpp
Labels: bug, component: plugin

#3733 ISAAC fix for particle vis and vector field vis in moving window simulation
  include/picongpu/plugins/IsaacPlugin.hpp
  share/ci/install/isaac.sh
Labels: bug, component: plugin

#3739 Add a brief doc page on ways of adding a laser to a simulation
  docs/source/usage/workflows.rst
  docs/source/usage/workflows/addLaser.rst
Labels: documentation, component: user input, CI:no-compile

#3711 Optimize radiation plugin math
  include/picongpu/plugins/radiation/Radiation.kernel
  include/picongpu/plugins/radiation/amplitude.hpp
  include/picongpu/plugins/radiation/nyquist_low_pass.hpp
  include/picongpu/plugins/radiation/radFormFactor.hpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.kernel
Labels: component: plugin

#3741 Fix mistakes in documentation of FDTD equations
  docs/source/models/AOFDTD.rst
Labels: bug, documentation
