Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2021-10, with the labels that each got.

#3830 Remove boost::result_of
  include/picongpu/fields/cellType/Centered.hpp
  include/picongpu/fields/cellType/Yee.hpp
  include/pmacc/math/MapTuple.hpp
  include/pmacc/math/vector/Vector.hpp
  include/pmacc/particles/memory/boxes/TileDataBox.hpp
  include/pmacc/particles/memory/dataTypes/Particle.hpp
  include/pmacc/particles/memory/dataTypes/StaticArray.hpp
  include/pmacc/particles/memory/frames/Frame.hpp
  include/pmacc/particles/operations/Deselect.hpp
  include/pmacc/random/Random.hpp
Labels: refactoring

#3832 Add a new particle manipulator combining total cell offset and rng
  include/picongpu/particles/manipulators/manipulators.def
  include/picongpu/particles/manipulators/manipulators.hpp
  include/picongpu/particles/manipulators/unary/FreeTotalCellOffsetRng.def
  include/picongpu/particles/manipulators/unary/FreeTotalCellOffsetRng.hpp
Labels: component: core

#3831 Document intention of Pointer
  include/pmacc/particles/memory/dataTypes/Pointer.hpp
Labels: component: PMacc

#3840 fix -d in 1.cfg in SingleParticleExample
  share/picongpu/examples/SingleParticleTest/etc/picongpu/1.cfg
Labels: bug, component: examples

#3839 Remove macro __deleteArray()
  include/picongpu/plugins/BinEnergyParticles.hpp
  include/picongpu/plugins/IntensityPlugin.hpp
  include/picongpu/plugins/output/GatherSlice.hpp
  include/picongpu/plugins/output/WriteSpeciesCommon.hpp
  include/picongpu/plugins/output/header/MessageHeader.hpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.hpp
  include/pmacc/memory/Delete.hpp
  include/pmacc/memory/buffers/MappedBufferIntern.hpp
  include/pmacc/particles/memory/buffers/MallocMCBuffer.tpp
Labels: refactoring

#3837 Extent comments of CreateDensity
  include/picongpu/particles/InitFunctors.hpp
Labels: component: core, documentation

#3835 Fix cell range in calorimeter plugin processing leaving particles
  include/picongpu/particles/boundary/Utility.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.kernel
Labels: bug, component: plugin

#3827 Rename type to Reference in Cursor
  include/picongpu/algorithms/AssignedTrilinearInterpolation.hpp
  include/picongpu/particles/synchrotronPhotons/SynchrotronFunctions.hpp
  include/pmacc/cuSTL/cursor/Cursor.hpp
  include/pmacc/cuSTL/cursor/FunctorCursor.hpp
  include/pmacc/cuSTL/cursor/accessor/CursorAccessor.hpp
  include/pmacc/cuSTL/cursor/accessor/FunctorAccessor.hpp
  include/pmacc/cuSTL/cursor/accessor/LinearInterpAccessor.hpp
  include/pmacc/cuSTL/cursor/accessor/MarkerAccessor.hpp
  include/pmacc/cuSTL/cursor/accessor/PointerAccessor.hpp
  include/pmacc/cuSTL/cursor/accessor/TwistAxesAccessor.hpp
Labels: component: PMacc, refactoring

#3273 add reference list
  docs/source/models/collisional_ionization.rst
  docs/source/usage/plugins/radiation.rst
  docs/source/usage/reference.rst
Labels: documentation, CI:no-compile

#3843 Fix compile error in the accelerating pusher
  include/picongpu/particles/pusher/particlePusherAcceleration.hpp
Labels: bug, component: core

#3844 Add Acceleration pusher to compile-time test suite
  share/picongpu/tests/compileParticlePusher/cmakeFlags
Labels: component: tests

#3848 Add a readthedocs page on debugging
  docs/source/dev/debugging.rst
  docs/source/index.rst
Labels: documentation, CI:no-compile

#3849 Add a link to the domain definitions wiki in the particle global filter workflow
  docs/source/usage/workflows/particleFilters.rst
Labels: documentation, CI:no-compile

#3851 Fix a typo in domain adjuster output
  include/picongpu/simulation/control/DomainAdjuster.hpp
Labels: component: core, refactoring

#3842 Fix inaccuracies in incident field solver
  include/picongpu/fields/incidentField/Solver.hpp
Labels: bug, component: core
