Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2022-03, with the labels that each got.

#4001 change the container URL of the GitLab CI to the new registry
  share/ci/compiler_clang.yml
  share/ci/compiler_clang_cuda.yml
  share/ci/compiler_gcc.yml
  share/ci/compiler_hipcc.yml
  share/ci/compiler_nvcc_cuda.yml
Labels: component: tests

#3987 remove obsolete check in tpl
  etc/picongpu/crusher-ornl/batch.tpl
  etc/picongpu/spock-ornl/caar.tpl
Labels: bug, machine/system, CI:no-compile

#4006 Workaround NVCC 11.6 compile bug
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: bug, backend: cuda

#4010 Update Dependency section in manual
  INSTALL.rst
Labels: documentation, component: third party, CI:no-compile

#3992 Implement phase-coefficients in Gauss-Laguerre laser modes
  include/picongpu/fields/laserProfiles/GaussianBeam.def
  include/picongpu/fields/laserProfiles/GaussianBeam.hpp
  include/picongpu/param/laser.param
  share/picongpu/examples/Bremsstrahlung/include/picongpu/param/laser.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/laser.param
Labels: component: core, component: user input, CI:no-compile

#4008 openPMD plugin: Set default backend depending on available options
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: component: plugin

#4013 Fix fieldBackground constructors to be HINLINE
  include/picongpu/param/fieldBackground.param
  share/picongpu/examples/Bunch/include/picongpu/param/fieldBackground.param
  share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/fieldBackground.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/fieldBackground.param
Labels: component: examples, component: user input

#4014 openPMD-based plugins: choose default backend depending on what is available
  include/picongpu/plugins/PhaseSpace/PhaseSpace.hpp
  include/picongpu/plugins/makroParticleCounter/PerSuperCell.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
  include/picongpu/plugins/xrayScattering/XrayScattering.hpp
Labels: component: plugin, refactoring

#4016 adjust modules for old kepler architecture
  etc/picongpu/hemera-hzdr/k20_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
Labels: machine/system, CI:no-compile

#4017 remove cupla compatibility marco definition
  include/picongpu/plugins/output/WriteSpeciesCommon.hpp
Labels: component: plugin, refactoring

#4018 remove `MappedBufferIntern`
  include/pmacc/memory/buffers/MappedBufferIntern.hpp
Labels: component: PMacc, refactoring

#4022 hemera: update modules for V100
  etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example
Labels: component: tools, machine/system, CI:no-compile

#4021 Extend comments in density.param
  include/picongpu/param/density.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/density.param
  share/picongpu/tests/CollisionsBeamRelaxation/include/picongpu/param/density.param
  share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/density.param
  share/picongpu/tests/XrayScattering/include/picongpu/param/density.param
Labels: documentation, component: user input

#4024 Add doxygen comments to declarations of density profile types
  include/picongpu/particles/densityProfiles/FreeFormulaImpl.def
  include/picongpu/particles/densityProfiles/FromOpenPMDImpl.def
  include/picongpu/particles/densityProfiles/GaussianCloudImpl.def
  include/picongpu/particles/densityProfiles/GaussianImpl.def
  include/picongpu/particles/densityProfiles/HomogenousImpl.def
  include/picongpu/particles/densityProfiles/LinearExponentialImpl.def
  include/picongpu/particles/densityProfiles/SphereFlanksImpl.def
Labels: documentation, component: user input

#4028 openPMD plugin: throw error when neither defining period or toml
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: component: plugin

#4029 Fix copying of cuSTL device buffers
  include/pmacc/cuSTL/container/copier/D2DCopier.hpp
Labels: bug, component: PMacc, affects latest release, backend: cuda

#4027 Clarify an inaccurate exception message in calorimeter plugin
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
Labels: component: plugin

#4026 fix Sphinx documentation
  docs/requirements.txt
Labels: bug, documentation

#4034 fix soft restart
  include/pmacc/simulationControl/SimulationHelper.hpp
Labels: bug, component: PMacc, affects latest release

#4033 Add ARM architecture templates
  include/pmacc/PMaccConfig.cmake
Labels: backend: omp2b
