Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2022-10, with the labels that each got.

#4308 fix wrong memory requirment calculation in .tpl files
  etc/picongpu/hemera-hzdr/fwkt_v100.tpl
  etc/picongpu/hemera-hzdr/gpu.tpl
  etc/picongpu/hemera-hzdr/k20.tpl
  etc/picongpu/hemera-hzdr/k20_restart.tpl
  etc/picongpu/hemera-hzdr/k80.tpl
  etc/picongpu/hemera-hzdr/k80_restart.tpl
  etc/picongpu/jureca-jsc/gpus.tpl
  etc/picongpu/juwels-jsc/booster.tpl
  etc/picongpu/juwels-jsc/gpus.tpl
Labels: bug, component: tools, affects latest release, machine/system

#4307 fix/workaround ROCm 5.2.0 compiler bug
  include/picongpu/particles/debyeLength/Estimate.kernel
  include/picongpu/plugins/IsaacPlugin.hpp
  include/pmacc/particles/algorithm/ForEach.hpp
  include/pmacc/particles/memory/dataTypes/SuperCell.hpp
Labels: bug, backend: hip

#4309 update to latest cupla dev branch
  thirdParty/cupla/alpaka/docs/source/dev/backends.rst
  thirdParty/cupla/alpaka/docs/source/dev/details.rst
  thirdParty/cupla/alpaka/include/alpaka/core/ApiCudaRt.hpp
  thirdParty/cupla/alpaka/include/alpaka/dev/cpu/SysInfo.hpp
  thirdParty/cupla/alpaka/include/alpaka/mem/buf/BufCpu.hpp
  thirdParty/cupla/alpaka/include/alpaka/mem/buf/BufGenericSycl.hpp
  thirdParty/cupla/alpaka/include/alpaka/mem/buf/BufOacc.hpp
  thirdParty/cupla/alpaka/include/alpaka/mem/buf/BufOmp5.hpp
  thirdParty/cupla/alpaka/include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  thirdParty/cupla/alpaka/include/alpaka/mem/buf/Traits.hpp
  thirdParty/cupla/alpaka/include/alpaka/rand/Philox/PhiloxBaseCommon.hpp
  thirdParty/cupla/alpaka/include/alpaka/rand/Philox/PhiloxConstants.hpp
  thirdParty/cupla/alpaka/include/alpaka/rand/Philox/PhiloxSingle.hpp
  thirdParty/cupla/alpaka/include/alpaka/rand/Philox/PhiloxVector.hpp
  thirdParty/cupla/alpaka/include/alpaka/rand/RandPhilox.hpp
  thirdParty/cupla/alpaka/include/alpaka/rand/RandUniformCudaHipRand.hpp
  thirdParty/cupla/alpaka/include/alpaka/rand/Traits.hpp
  thirdParty/cupla/alpaka/test/integ/axpy/src/axpy.cpp
  thirdParty/cupla/alpaka/test/integ/hostOnlyAPI/src/hostOnlyAPI.cpp
  thirdParty/cupla/alpaka/test/integ/mandelbrot/src/mandelbrot.cpp
  thirdParty/cupla/alpaka/test/integ/matMul/src/matMul.cpp
  thirdParty/cupla/alpaka/test/integ/separableCompilation/src/main.cpp
  thirdParty/cupla/alpaka/test/integ/zeroDimBuffer/src/zeroDimBuffer.cpp
  thirdParty/cupla/alpaka/test/unit/math/src/Buffer.hpp
  thirdParty/cupla/alpaka/test/unit/mem/fence/src/FenceTest.cpp
  thirdParty/cupla/alpaka/test/unit/rand/src/RandTest.cpp
  thirdParty/cupla/include/cupla/manager/Memory.hpp
  thirdParty/cupla/src/memory.cpp
Labels: component: third party

#4315 CI: add CUDA 11.3 - 11.4, HIP 4.5, 5.0 - 5.2
  share/ci/n_wise_generator.py
Labels: component: tests, backend: cuda, backend: hip

#4314 fix growth rate test case folder location
  share/picongpu/tests/KHI_growthRate/bin/ci.sh
  share/picongpu/tests/KHI_growthRate/bin/validate.sh
  share/picongpu/tests/KHI_growthRate/include/picongpu/param/dimension.param
  share/picongpu/tests/KHI_growthRate/include/picongpu/param/grid.param
  share/picongpu/tests/KHI_growthRate/include/picongpu/param/particle.param
Labels: bug, component: examples, component: tests

#4325 Remove getGlobalSuperCells
  include/pmacc/mappings/kernel/MappingDescription.hpp
Labels: component: core, refactoring

#4326 move include collision.unitless to the default loader
  include/picongpu/_defaultUnitless.loader
  include/picongpu/particles/collision/binary/RelativisticBinaryCollision.hpp
Labels: component: core, refactoring

#4302 Add DispersiveLaser incident field profile
  include/picongpu/fields/incidentField/profiles/DispersiveLaser.def
  include/picongpu/fields/incidentField/profiles/DispersiveLaser.hpp
  include/picongpu/fields/incidentField/profiles/profiles.def
  include/picongpu/fields/incidentField/profiles/profiles.hpp
  include/picongpu/param/incidentField.param
  share/picongpu/benchmarks/TWEAC-FOM/include/picongpu/param/incidentField.param
  share/picongpu/examples/IncidentField/include/picongpu/param/incidentField.param
Labels: component: core, component: user input

#4328 fix PMacc reduce
  include/pmacc/device/reduce/Kernel.hpp
Labels: bug, component: PMacc, affects latest release

#4320 add new openPMD-api module for hemera kepler
  etc/picongpu/hemera-hzdr/k20_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
Labels: machine/system, CI:no-compile

#4317 PMacc: refactor kernel en-queuing
  include/pmacc/eventSystem/events/kernelEvents.hpp
  include/pmacc/eventSystem/events/kernelEvents.tpp
Labels: component: PMacc, refactoring

#4327 Install dependencies for memoryPerDevice example
  .readthedocs.yaml
  .readthedocs.yml
  docs/source/usage/workflows/memoryPerDevice.rst
Labels: documentation
