Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2022-07, with the labels that each got.

#4183 gpu profile for dev-server
  etc/picongpu/bash-devServer-hzdr/gpu_install.sh
  etc/picongpu/bash-devServer-hzdr/gpu_picongpu.profile.example
Labels: component: PMacc, component: tools, machine/system

#4192 Fix implementation of pmacc::makeDeepCopy() and field background
  include/pmacc/memory/buffers/DeviceBufferIntern.hpp
Labels: bug, component: PMacc, affects latest release

#4187 Update boost and openpmd version in defq hemera profile
  etc/picongpu/hemera-hzdr/defq_picongpu.profile.example
Labels: machine/system

#4186 Output numerical phase velocity for enabled incident field profiles
  include/picongpu/fields/incidentField/profiles/Free.hpp
  include/picongpu/fields/incidentField/profiles/None.hpp
  include/picongpu/initialization/InitialiserController.hpp
Labels: bug, component: core

#4195 Switch to std::void_t
  include/picongpu/particles/Particles.tpp
  include/pmacc/lockstep/ForEach.hpp
Labels: refactoring

#4191 Remove derived attribute/field MomentumComponent
  include/picongpu/param/fileOutput.param
  include/picongpu/particles/particleToGrid/derivedAttributes/DerivedAttributes.def
  include/picongpu/particles/particleToGrid/derivedAttributes/DerivedAttributes.hpp
  include/picongpu/particles/particleToGrid/derivedAttributes/MomentumComponent.def
  include/picongpu/particles/particleToGrid/derivedAttributes/MomentumComponent.hpp
  share/picongpu/examples/FieldAbsorberTest/include/picongpu/param/fileOutput.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/fileOutput.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/fileOutput.param
  share/picongpu/tests/CollisionsBeamRelaxation/include/picongpu/param/fileOutput.param
  share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/fileOutput.param
  share/picongpu/tests/XrayScattering/include/picongpu/param/fileOutput.param
  share/picongpu/tests/compileCombinedAttributes/include/picongpu/param/fileOutput.param
Labels: component: core, component: user input

#4196 Allow componentwise calculation of incident field functors
  include/picongpu/fields/background/templates/twtsfast/BField.hpp
  include/picongpu/fields/background/templates/twtsfast/BField.tpp
  include/picongpu/fields/background/templates/twtsfast/EField.hpp
  include/picongpu/fields/background/templates/twtsfast/EField.tpp
  include/picongpu/fields/incidentField/Functors.hpp
  include/picongpu/fields/incidentField/Solver.hpp
  include/picongpu/fields/incidentField/Solver.kernel
Labels: component: core

#4197 Extend TWEAC-FOM benchmark with incident field option for laser generation
  share/picongpu/benchmarks/TWEAC-FOM/README.md
  share/picongpu/benchmarks/TWEAC-FOM/cmakeFlags
  share/picongpu/benchmarks/TWEAC-FOM/include/picongpu/param/fieldBackground.param
  share/picongpu/benchmarks/TWEAC-FOM/include/picongpu/param/incidentField.param
Labels: component: examples

#4203 Update Hemera gpu_picongpu.profile.example
  etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example
Labels: machine/system, CI:no-compile

#4200 Add componentwise incident field calculation option to TWEAC-FOM benchmark
  share/picongpu/benchmarks/TWEAC-FOM/cmakeFlags
  share/picongpu/benchmarks/TWEAC-FOM/include/picongpu/param/incidentField.param
Labels: component: examples

#4202 Fix index shift in 2d incident field kernel
  include/picongpu/fields/incidentField/Solver.kernel
Labels: bug, component: core, affects latest release

#4173 add device side `ForEachParticle`
  include/picongpu/fields/FieldJ.kernel
  include/picongpu/fields/FieldTmp.kernel
  include/picongpu/particles/Particles.kernel
  include/picongpu/particles/debyeLength/Estimate.kernel
  include/picongpu/particles/flylite/helperFields/LocalEnergyHistogram.kernel
  include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.def
  include/picongpu/particles/particleToGrid/ComputeGridValuePerFrame.hpp
  include/picongpu/plugins/BinEnergyParticles.hpp
  include/picongpu/plugins/Emittance.hpp
  include/picongpu/plugins/EnergyParticles.hpp
  include/picongpu/plugins/PositionsParticles.hpp
  include/picongpu/plugins/makroParticleCounter/PerSuperCell.hpp
  include/picongpu/plugins/output/images/Visualisation.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.kernel
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeterFunctors.hpp
  include/pmacc/particles/ParticlesBase.kernel
  include/pmacc/particles/algorithm/ForEach.hpp
  include/pmacc/particles/algorithm/detail/ForEach.hpp
Labels: component: core, component: PMacc, refactoring

#4215 fix crusher profiles
  etc/picongpu/crusher-ornl/batch.tpl
  etc/picongpu/crusher-ornl/batch_craycc_picongpu.profile.example
  etc/picongpu/crusher-ornl/batch_hipcc_picongpu.profile.example
Labels: component: tools, machine/system, CI:no-compile

#4217 catch cuda_memtest error messages
  bin/cuda_memtest.sh
Labels: component: tools, CI:no-compile

#4216 activate cuda_memtest on crusher
  etc/picongpu/crusher-ornl/batch.tpl
Labels: component: tools, machine/system, CI:no-compile

#4214 update cuda_memtest
  thirdParty/cuda_memtest/cuda_memtest.cpp
Labels: component: third party

#4220 update mallocMC to fix possible out of memory access
  thirdParty/mallocMC/src/include/mallocMC/creationPolicies/Scatter.hpp
Labels: component: third party

#4218 HIP: use compute current strategy `strategy::CachedSupercellsScaled<2>`
  include/picongpu/fields/currentDeposition/Strategy.def
Labels: component: core, backend: hip, performance

#4219 Workaround wrong reported free memory
  include/picongpu/simulation/control/Simulation.hpp
Labels: component: core, refactoring

#4222 Fix check for last updated cell in 2d incident field kernel
  include/picongpu/fields/incidentField/Solver.kernel
Labels: bug, component: core

#4226 Simplify implementation of incident field kernel
  include/picongpu/fields/incidentField/Solver.hpp
  include/picongpu/fields/incidentField/Solver.kernel
Labels: component: core, refactoring

#4225 PNG plugin: fix invalid memory access in 2D
  include/picongpu/plugins/output/images/Visualisation.hpp
Labels: bug, affects latest release

#4223 clang: fix early assert evaluation
  include/picongpu/fields/currentDeposition/EmZ/EmZ.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.hpp
  include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.hpp
Labels: bug

#4227 Fix particle assignment used in EmZ 2d for calculating Jz
  include/picongpu/fields/currentDeposition/EmZ/EmZ.hpp
Labels: bug, component: core

#4230 crusher: add slurm fault tolerance
  etc/picongpu/crusher-ornl/batch.tpl
  etc/picongpu/crusher-ornl/batch_craycc_picongpu.profile.example
  etc/picongpu/crusher-ornl/batch_hipcc_picongpu.profile.example
Labels: component: tools, machine/system, CI:no-compile

#4229 documentation: mention `CMAKE_BUILD_TYPE`
  docs/source/dev/debugging.rst
Labels: documentation, CI:no-compile

#4231 Fix radiation trees.
  include/picongpu/plugins/radiation/Radiation.kernel
Labels: bug, component: plugin, affects latest release

#3804 Add time-substepping versions of existing field solvers
  include/picongpu/fields/LaserPhysics.hpp
  include/picongpu/fields/MaxwellSolver/ArbitraryOrderFDTD/ArbitraryOrderFDTD.hpp
  include/picongpu/fields/MaxwellSolver/DispersionRelation.hpp
  include/picongpu/fields/MaxwellSolver/FDTD/FDTD.def
  include/picongpu/fields/MaxwellSolver/FDTD/FDTD.hpp
  include/picongpu/fields/MaxwellSolver/FDTD/FDTDBase.hpp
  include/picongpu/fields/MaxwellSolver/FDTD/FDTDBase.kernel
  include/picongpu/fields/MaxwellSolver/GetTimeStep.hpp
  include/picongpu/fields/MaxwellSolver/Solvers.def
  include/picongpu/fields/MaxwellSolver/Solvers.hpp
  include/picongpu/fields/MaxwellSolver/Substepping/Substepping.def
  include/picongpu/fields/MaxwellSolver/Substepping/Substepping.hpp
  include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
  include/picongpu/fields/MaxwellSolver/traits/IsSubstepping.hpp
  include/picongpu/fields/absorber/exponential/Exponential.hpp
  include/picongpu/fields/absorber/pml/Pml.hpp
  include/picongpu/fields/absorber/pml/Pml.kernel
  include/picongpu/fields/currentInterpolation/Binomial.hpp
  include/picongpu/fields/currentInterpolation/None.hpp
  include/picongpu/fields/incidentField/Solver.hpp
  include/picongpu/fields/laserProfiles/BaseFunctor.hpp
  include/picongpu/fields/laserProfiles/ExpRampWithPrepulse.hpp
  include/picongpu/fields/laserProfiles/GaussianBeam.hpp
  include/picongpu/fields/laserProfiles/None.hpp
  include/picongpu/fields/laserProfiles/PlaneWave.hpp
  include/picongpu/fields/laserProfiles/Polynom.hpp
  include/picongpu/fields/laserProfiles/PulseFrontTilt.hpp
  include/picongpu/fields/laserProfiles/Wavepacket.hpp
  include/picongpu/param/fieldSolver.param
  include/picongpu/simulation/control/Simulation.hpp
  share/picongpu/tests/compileFieldSolver/cmakeFlags
  share/picongpu/tests/compileFieldSolver/include/picongpu/param/fieldSolver.param
Labels: component: core
