Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2022-05, with the labels that each got.

#3998 Add profiles for A100 GPUs on Taurus
  etc/picongpu/taurus-tud/A100.tpl
  etc/picongpu/taurus-tud/A100_picongpu.profile.example
  etc/picongpu/taurus-tud/A100_restart.tpl
Labels: component: tools, machine/system, CI:no-compile

#4085 fix CUDA container apt keys
  share/ci/compiler_clang.yml
  share/ci/compiler_gcc.yml
  share/ci/n_wise_generator.py
Labels: bug, affects latest release

#4083 Fix comments on axis definitions in incident field profiles
  include/picongpu/fields/incidentField/profiles/ExpRampWithPrepulse.def
  include/picongpu/fields/incidentField/profiles/GaussianBeam.def
  include/picongpu/fields/incidentField/profiles/PlaneWave.def
  include/picongpu/fields/incidentField/profiles/Polynom.def
  include/picongpu/fields/incidentField/profiles/PulseFrontTilt.def
  include/picongpu/fields/incidentField/profiles/Wavepacket.def
Labels: documentation, CI:no-compile

#4095 use `if constexpr` in `lockstep::ForEach`
  include/pmacc/lockstep/ForEach.hpp
Labels: component: PMacc, refactoring

#4098 fix documentation: minimal boost version
  INSTALL.rst
Labels: bug, documentation, CI:no-compile

#4103 Fix a few instances of calling the Taflove-Hagness book just Taflove
  docs/source/models/AOFDTD.rst
  docs/source/models/total_field_scattered_field.rst
  share/picongpu/examples/FieldAbsorberTest/etc/picongpu/1.cfg
  share/picongpu/examples/FieldAbsorberTest/etc/picongpu/4.cfg
Labels: documentation, CI:no-compile

#3968 Add new laser profile: PulseFromSpectrum by @nils-pr
  docs/source/usage/param/laser/profiles.rst
  include/picongpu/fields/laserProfiles/PulseFromSpectrum.def
  include/picongpu/fields/laserProfiles/PulseFromSpectrum.hpp
  include/picongpu/fields/laserProfiles/profiles.def
  include/picongpu/fields/laserProfiles/profiles.hpp
  include/picongpu/param/laser.param
  share/picongpu/examples/Bremsstrahlung/include/picongpu/param/laser.param
  share/picongpu/examples/Bunch/include/picongpu/param/laser.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/laser.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/laser.param
Labels: component: user input, CI:no-compile

#4100 remove example: ThermalTest
  docs/COMMIT.md
  share/picongpu/examples/ThermalTest/etc/picongpu/1.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/32.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/4.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/64.cfg
  share/picongpu/examples/ThermalTest/etc/picongpu/8.cfg
  share/picongpu/examples/ThermalTest/executeOnClone
  share/picongpu/examples/ThermalTest/include/picongpu/ThermalTestSimulation.hpp
  share/picongpu/examples/ThermalTest/include/picongpu/param/components.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/density.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/grid.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/memory.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/particle.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/speciesInitialization.param
  share/picongpu/examples/ThermalTest/include/picongpu/param/starter.param
  share/picongpu/examples/ThermalTest/include/picongpu/unitless/starter.unitless
  share/picongpu/examples/ThermalTest/tools/dispersion.py
Labels: component: examples

#4099 Add Thermal electron benchmark
  share/picongpu/benchmarks/Thermal/README.rst
  share/picongpu/benchmarks/Thermal/cmakeFlags
  share/picongpu/benchmarks/Thermal/etc/picongpu/1.cfg
  share/picongpu/benchmarks/Thermal/etc/picongpu/1_noIO.cfg
  share/picongpu/benchmarks/Thermal/include/picongpu/param/density.param
  share/picongpu/benchmarks/Thermal/include/picongpu/param/dimension.param
  share/picongpu/benchmarks/Thermal/include/picongpu/param/grid.param
  share/picongpu/benchmarks/Thermal/include/picongpu/param/memory.param
  share/picongpu/benchmarks/Thermal/include/picongpu/param/particle.param
  share/picongpu/benchmarks/Thermal/include/picongpu/param/png.param
  share/picongpu/benchmarks/Thermal/include/picongpu/param/species.param
  share/picongpu/benchmarks/Thermal/include/picongpu/param/speciesDefinition.param
  share/picongpu/benchmarks/Thermal/include/picongpu/param/speciesInitialization.param
Labels: component: examples

#4102 Fix incident field math around corners
  include/picongpu/fields/incidentField/Solver.hpp
  include/picongpu/fields/incidentField/Solver.kernel
Labels: bug, component: core, affects latest release

#4082 Expand docs on using incident field
  docs/source/models/total_field_scattered_field.rst
  docs/source/usage/workflows/addLaser.rst
Labels: component: core, documentation, CI:no-compile

#4086 hzdr dev server profile
  etc/picongpu/bash-devServer-hzdr/cpu_picongpu.profile.example
  etc/picongpu/bash-devServer-hzdr/install.sh
  etc/picongpu/bash-devServer-hzdr/mpiexec.tpl
Labels: component: tools, machine/system, CI:no-compile

#4104 update cupla to latest dev
  thirdParty/cupla/include/cupla/device/math/Common.hpp
Labels: bug, component: third party

#4096 OpenPMD plugin data range selection
  docs/TBG_macros.cfg
  docs/source/usage/plugins/openPMD.rst
  include/picongpu/plugins/misc/intersectRangeWithWindow.hpp
  include/picongpu/plugins/misc/misc.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: component: plugin

#4107 use `if constexpr()` to check for simulation/object dimension
  include/picongpu/fields/absorber/pml/Field.tpp
  include/picongpu/plugins/PhaseSpace/DumpHBufferOpenPMD.hpp
  include/picongpu/plugins/PhaseSpace/PhaseSpace.tpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/picongpu/plugins/output/images/Visualisation.hpp
  include/picongpu/simulation/stage/ParticleBoundaries.hpp
  include/pmacc/communication/CommunicatorMPI.hpp
  include/pmacc/cuSTL/container/DeviceBuffer.hpp
  include/pmacc/cuSTL/container/IndexBuffer.hpp
  include/pmacc/cuSTL/container/allocator/DeviceMemAllocator.tpp
  include/pmacc/cuSTL/container/allocator/DeviceMemEvenPitchAllocator.tpp
  include/pmacc/cuSTL/container/allocator/HostMemAllocator.tpp
  include/pmacc/mappings/simulation/GridController.hpp
  include/pmacc/memory/buffers/Buffer.hpp
  include/pmacc/memory/buffers/DeviceBuffer.hpp
  include/pmacc/memory/buffers/DeviceBufferIntern.hpp
  include/pmacc/memory/buffers/ExchangeIntern.hpp
Labels: component: core, component: PMacc, refactoring

#4108 Generalize incident field to support typelists of profiles
  docs/source/usage/workflows/addLaser.rst
  include/picongpu/fields/incidentField/Solver.hpp
  include/picongpu/param/incidentField.param
  share/picongpu/examples/IncidentField/include/picongpu/param/incidentField.param
Labels: component: core, component: examples

#4112 Remove SliceFieldPrinter plugin
  docs/source/usage/plugins.rst
  docs/source/usage/plugins/sliceFieldPrinter.rst
  include/picongpu/plugins/PluginController.hpp
  include/picongpu/plugins/SliceFieldPrinter.hpp
  include/picongpu/plugins/SliceFieldPrinter.tpp
  include/picongpu/plugins/SliceFieldPrinterMulti.hpp
  include/picongpu/plugins/SliceFieldPrinterMulti.tpp
  lib/python/picongpu/plugins/data/sliceFieldReader.py
Labels: component: plugin, component: user input

#4113 CUDA: fix false warning
  include/pmacc/memory/buffers/DeviceBufferIntern.hpp
Labels: warning, backend: cuda

#4116 avoid using macro define `SIMDIM`
  include/picongpu/plugins/SumCurrents.hpp
  include/picongpu/plugins/output/images/Visualisation.hpp
Labels: component: core, refactoring

#4114 Switch to alpaka::Complex<>
  include/picongpu/fields/background/templates/TWTS/BField.tpp
  include/picongpu/fields/background/templates/TWTS/EField.tpp
  include/picongpu/fields/background/templates/twtsfast/BField.tpp
  include/picongpu/fields/background/templates/twtsfast/EField.tpp
  include/picongpu/plugins/radiation/amplitude.hpp
  include/picongpu/plugins/transitionRadiation/Calculator.hpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.hpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.kernel
  include/picongpu/plugins/xrayScattering/XrayScattering.hpp
  include/picongpu/plugins/xrayScattering/XrayScattering.kernel
  include/picongpu/plugins/xrayScattering/xrayScatteringUtilities.hpp
  include/pmacc/math/complex/Bessel.hpp
  include/pmacc/math/complex/Bessel.tpp
  include/pmacc/math/complex/Complex.hpp
  include/pmacc/math/complex/Complex.tpp
Labels: component: core, refactoring

#4118 Fix calculation of total current in the SumCurrents plugin for 2d case
  include/picongpu/plugins/SumCurrents.hpp
Labels: bug, component: plugin, affects latest release

#4117 Fix some typos in the reference doc page
  docs/source/usage/reference.rst
Labels: documentation, CI:no-compile

#4111 Add a new functor to sample macroparticles in a cell
  include/picongpu/particles/InitFunctors.hpp
  include/picongpu/particles/startPosition/RandomBinomialImpl.def
  include/picongpu/particles/startPosition/RandomBinomialImpl.hpp
  include/picongpu/particles/startPosition/functors.def
  include/picongpu/particles/startPosition/functors.hpp
  share/picongpu/tests/compileCurrentSolver/include/picongpu/param/particle.param
  share/picongpu/tests/compileCurrentSolver/include/picongpu/param/speciesInitialization.param
Labels: component: core, component: user input

#4122 Improve reporting of wrong MPI/devices configuration
  include/picongpu/simulation/control/Simulation.hpp
  include/pmacc/communication/CommunicatorMPI.hpp
Labels: component: core, component: PMacc, documentation

#4115 remove pusher `Axel`
  include/picongpu/param/pusher.param
  include/picongpu/particles/pusher/particlePusherAxel.hpp
  include/picongpu/unitless/pusher.unitless
  share/picongpu/examples/SingleParticleTest/cmakeFlags
Labels: refactoring, component: user input

#4119 CI: re-enable ISAAC
  share/ci/install/isaac.sh
  share/ci/run_picongpu_tests.sh
Labels: component: tests

#4120 Enable incident field generation with moving window
  docs/source/models/total_field_scattered_field.rst
  docs/source/usage/workflows/addLaser.rst
  include/picongpu/fields/incidentField/Solver.hpp
  include/picongpu/param/incidentField.param
  share/picongpu/examples/IncidentField/include/picongpu/param/incidentField.param
Labels: component: core, component: user input
