Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2022-02, with the labels that each got.

#3967 Expand documentation on running interactively
  docs/source/install/profile.rst
  docs/source/usage/tbg.rst
  etc/picongpu/bash/bash_picongpu.profile.example
Labels: documentation, machine/system, CI:no-compile

#3970 Fix EnergyHistogram and clarify usage
  docs/source/usage/plugins/energyHistogram.rst
  lib/python/picongpu/plugins/plot_mpl/energy_histogram_visualizer.py
Labels: documentation, component: tools, CI:no-compile

#3944 Cleanup current deposition implementation
  include/picongpu/fields/currentDeposition/EmZ/DepositCurrent.hpp
  include/picongpu/fields/currentDeposition/EmZ/EmZ.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/Base.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp
  include/picongpu/fields/currentDeposition/VillaBune/CurrentVillaBune.hpp
Labels: component: core, refactoring

#3972 Add a runtime option to set particle density file
  docs/TBG_macros.cfg
  include/picongpu/param/density.param
  include/picongpu/particles/densityProfiles/FromOpenPMDImpl.hpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/simulation/stage/RuntimeDensityFile.hpp
Labels: component: core, component: user input

#3878 fix warnings and check for warnings in CI
  include/picongpu/CMakeLists.txt
  include/picongpu/algorithms/AssignedTrilinearInterpolation.hpp
  include/picongpu/fields/FieldJ.kernel
  include/picongpu/fields/absorber/pml/Field.tpp
  include/picongpu/fields/absorber/pml/Pml.kernel
  include/picongpu/fields/background/templates/TWTS/BField.tpp
  include/picongpu/fields/background/templates/TWTS/EField.tpp
  include/picongpu/fields/background/templates/twtsfast/BField.tpp
  include/picongpu/fields/background/templates/twtsfast/EField.tpp
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp
  include/picongpu/fields/laserProfiles/BaseFunctor.hpp
  include/picongpu/particles/ParticlesFunctors.hpp
  include/picongpu/particles/creation/creation.kernel
  include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp
  include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp
  include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp
  include/picongpu/particles/pusher/particlePusherReducedLandauLifshitz.hpp
  include/picongpu/plugins/BinEnergyParticles.hpp
  include/picongpu/plugins/Emittance.hpp
  include/picongpu/plugins/EnergyParticles.hpp
  include/picongpu/plugins/IsaacPlugin.hpp
  include/picongpu/plugins/PhaseSpace/DumpHBufferOpenPMD.hpp
  include/picongpu/plugins/PhaseSpace/PhaseSpace.tpp
  include/picongpu/plugins/PhaseSpace/PhaseSpaceFunctors.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/picongpu/plugins/openPMD/restart/RestartFieldLoader.hpp
  include/picongpu/plugins/output/images/Visualisation.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeterFunctors.hpp
  include/picongpu/plugins/radiation/Radiation.hpp
  include/picongpu/plugins/radiation/Radiation.kernel
  include/picongpu/plugins/radiation/particle.hpp
  include/picongpu/plugins/transitionRadiation/Particle.hpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.hpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.kernel
  include/picongpu/plugins/xrayScattering/XrayScattering.hpp
  include/picongpu/plugins/xrayScattering/XrayScatteringWriter.hpp
  include/picongpu/simulation/stage/FieldBackground.hpp
  include/pmacc/eventSystem/tasks/TaskKernel.hpp
  include/pmacc/fields/tasks/TaskFieldReceiveAndInsertExchange.hpp
  include/pmacc/fields/tasks/TaskFieldSendExchange.hpp
  include/pmacc/lockstep/Idx.hpp
  include/pmacc/memory/buffers/Buffer.hpp
  include/pmacc/memory/buffers/DeviceBufferIntern.hpp
  include/pmacc/memory/buffers/ExchangeIntern.hpp
  include/pmacc/memory/buffers/GridBuffer.hpp
  include/pmacc/particles/ParticlesBase.kernel
  include/pmacc/particles/memory/boxes/ExchangePushDataBox.hpp
  include/pmacc/particles/memory/boxes/PushDataBox.hpp
  include/pmacc/particles/memory/buffers/ParticlesBuffer.hpp
  include/pmacc/particles/memory/dataTypes/Particle.hpp
  include/pmacc/particles/operations/splitIntoListOfFrames.kernel
  include/pmacc/particles/tasks/TaskReceiveParticlesExchange.hpp
  include/pmacc/particles/tasks/TaskSendParticlesExchange.hpp
  include/pmacc/random/RNGProvider.tpp
  share/ci/run_picongpu_tests.sh
  share/picongpu/examples/Bunch/include/picongpu/param/fieldBackground.param
  share/picongpu/tests/XrayScattering/include/picongpu/param/density.param
Labels: component: core, component: plugin, component: PMacc, warning

#3973 crusher hipcc profile
  docs/source/install/profile.rst
  etc/picongpu/crusher-ornl/batch_craycc_picongpu.profile.example
  etc/picongpu/crusher-ornl/batch_hipcc_picongpu.profile.example
Labels: documentation, component: tools, machine/system, CI:no-compile

#3981 Docs: Fix Stale LSF Links
  etc/picongpu/summit-ornl/LSF_Tutorial.rst
Labels: documentation, CI:no-compile

#3994 Fix env variables in install from source docs
  INSTALL.rst
Labels: bug, documentation, install, CI:no-compile

#3993 docs typo in energy histogram
  docs/source/usage/plugins/energyHistogram.rst
Labels: bug, component: plugin, documentation, CI:no-compile

#3999 Fix PICSRC in bash_picongpu.profile
  etc/picongpu/bash/bash_picongpu.profile.example
Labels: component: user input, CI:no-compile

#3986 Don't install toml11 internally shipped library
  include/picongpu/CMakeLists.txt
Labels: component: third party, install
