Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2022-09, with the labels that each got.

#4287 OpenPMD plugin: add IO file version
  include/picongpu/plugins/common/openPMDVersion.def
  include/picongpu/plugins/common/openPMDWriteMeta.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: component: plugin, refactoring

#4285 fix png artefacts in particle density
  include/picongpu/plugins/output/images/Visualisation.hpp
Labels: bug, component: plugin

#4288 Add and enable UCX_RC_TIMEOUT workaround
  etc/picongpu/juwels-jsc/booster.tpl
Labels: machine/system, CI:no-compile

#4283 [breaking change] fix openPMD particles `positionOffset`
  include/picongpu/plugins/common/openPMDVersion.def
  include/picongpu/plugins/openPMD/WriteSpecies.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp
  include/pmacc/particles/operations/splitIntoListOfFrames.kernel
Labels: bug, affects latest release

#4284 Update hemera kepler profiles
  etc/picongpu/hemera-hzdr/k20_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
Labels: machine/system, CI:no-compile

#4106 KHI_growthRate Testsuite
  lib/python/test/KHI_growthRate/CalculateParameter.py
  lib/python/test/KHI_growthRate/DifferenceKHIGrowthRate.py
  lib/python/test/KHI_growthRate/KHIData.py
  lib/python/test/KHI_growthRate/KHIParams.py
  lib/python/test/KHI_growthRate/MainTest.py
  lib/python/test/KHI_growthRate/ParamReader.py
  lib/python/test/KHI_growthRate/TestKHI.py
  lib/python/test/KHI_growthRate/TestKHIManager.py
  lib/python/test/KHI_growthRate/TheoryGrowthRate.py
  lib/python/test/KHI_growthRate/ViewerKHI.py
  lib/python/test/KHI_growthRate/requirements.txt
  lib/python/test/requirements.txt
  test/KHI_growthRate/bin/ci.sh
  test/KHI_growthRate/bin/validate.sh
  test/KHI_growthRate/include/picongpu/param/dimension.param
  test/KHI_growthRate/include/picongpu/param/grid.param
  test/KHI_growthRate/include/picongpu/param/particle.param
Labels: component: tools

#4291 DataBox remove method `reduceZ()`
  include/pmacc/memory/boxes/DataBox.hpp
  include/pmacc/memory/boxes/PitchedBox.hpp
Labels: component: PMacc, refactoring

#4289 remove Cell2Particle
  include/picongpu/particles/access/Cell2Particle.hpp
  include/picongpu/particles/access/Cell2Particle.tpp
  include/picongpu/plugins/PhaseSpace/PhaseSpaceFunctors.hpp
  include/picongpu/plugins/particleMerging/ParticleMerger.kernel
  include/picongpu/plugins/randomizedParticleMerger/RandomizedParticleMerger.kernel
Labels: component: core, refactoring

#4296 Fix calls to makeForEach in particle merger plugins
  include/picongpu/plugins/particleMerging/ParticleMerger.kernel
  include/picongpu/plugins/randomizedParticleMerger/RandomizedParticleMerger.kernel
Labels: bug, component: plugin

#4297 Add compilation of particle merger plugins to compile-time tests
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/speciesDefinition.param
Labels: component: tests

#4298 Fix handling of last updated cell in incident field
  include/picongpu/fields/incidentField/Solver.hpp
  include/picongpu/fields/incidentField/Solver.kernel
Labels: bug, component: core

#4293 Improve treating currents in PML
  docs/source/usage/workflows/boundaryConditions.rst
  include/picongpu/fields/absorber/pml/Parameters.hpp
  include/picongpu/fields/absorber/pml/Pml.hpp
  include/picongpu/fields/absorber/pml/Pml.kernel
  include/picongpu/particles/boundary/Absorbing.hpp
Labels: component: core

#4301 Fix 2D implementation of incident GaussianBeam
  include/picongpu/fields/incidentField/profiles/GaussianBeam.hpp
Labels: bug, component: core

#4306 fix TWTS fast wrong type cast
  include/picongpu/fields/background/templates/twtsfast/BField.tpp
Labels: bug
