Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2023-09, with the labels that each got.

#4648 remove debug output from PR 4644
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: documentation, CI:no-compile

#4665 CI: fix no-compile label detection
  .gitlab-ci.yml
  share/ci/generate_reduced_matrix.sh
  share/ci/pr_has_label.sh
Labels: bug, component: tests, CI:no-compile

#4660 remove env from pinning script
  etc/picongpu/lumi-eurohpc/standard-g.tpl
Labels: machine/system, CI:no-compile

#4664 upgrade to picmi 0.26 and typeguard 4
  lib/python/picongpu/picmi/grid.py
  lib/python/picongpu/picmi/solver.py
  lib/python/picongpu/picmi/species.py
  lib/python/picongpu/pypicongpu/species/initmanager.py
  lib/python/picongpu/requirements.txt
  share/ci/pypicongpu_generator.py
  test/python/picongpu/quick/picmi/grid.py
  test/python/picongpu/quick/picmi/simulation.py
  test/python/picongpu/quick/picmi/species.py
  test/python/picongpu/quick/pypicongpu/grid.py
  test/python/picongpu/quick/pypicongpu/laser.py
  test/python/picongpu/quick/pypicongpu/output/auto.py
  test/python/picongpu/quick/pypicongpu/rendering/renderedobject.py
  test/python/picongpu/quick/pypicongpu/runner.py
  test/python/picongpu/quick/pypicongpu/simulation.py
  test/python/picongpu/quick/pypicongpu/species/constant/charge.py
  test/python/picongpu/quick/pypicongpu/species/constant/densityratio.py
  test/python/picongpu/quick/pypicongpu/species/constant/elementproperties.py
  test/python/picongpu/quick/pypicongpu/species/constant/mass.py
  test/python/picongpu/quick/pypicongpu/species/initmanager.py
  test/python/picongpu/quick/pypicongpu/species/operation/densityprofile/uniform.py
  test/python/picongpu/quick/pypicongpu/species/operation/momentum/drift.py
  test/python/picongpu/quick/pypicongpu/species/operation/momentum/temperature.py
  test/python/picongpu/quick/pypicongpu/species/operation/noboundelectrons.py
  test/python/picongpu/quick/pypicongpu/species/operation/notplaced.py
  test/python/picongpu/quick/pypicongpu/species/operation/setboundelectrons.py
  test/python/picongpu/quick/pypicongpu/species/operation/simpledensity.py
  test/python/picongpu/quick/pypicongpu/species/operation/simplemomentum.py
  test/python/picongpu/quick/pypicongpu/species/species.py
  test/python/picongpu/quick/pypicongpu/species/util/element.py
Labels: refactoring, component: tests, CI:no-compile

#4662 fix compiler install description
  INSTALL.rst
Labels: documentation, CI:no-compile

#4668 fix mismatch devServer install script and example profile dependencies
  etc/picongpu/bash-devServer-hzdr/gpu_v100_picongpu.profile.example
Labels: machine/system, CI:no-compile

#4667 increase required PICMI python version to 3.10+
  lib/python/picongpu/picmi/__init__.py
Labels: CI:no-compile, PICMI

#4673 update cuda memtest
  thirdParty/cuda_memtest/CMakeLists.txt
  thirdParty/cuda_memtest/README.md
  thirdParty/cuda_memtest/cuda_memtest.cpp
Labels: warning, component: third party

#4672 fix `setValue`
  include/pmacc/eventSystem/tasks/Factory.tpp
  include/pmacc/eventSystem/tasks/TaskSetValue.hpp
Labels: bug, component: PMacc

#4670 add support for CMake option `alpaka_DISABLE_VENDOR_RNG`
  include/pmacc/random/distributions/normal/Normal_double.hpp
  include/pmacc/random/distributions/normal/Normal_float.hpp
  include/pmacc/random/methods/methods.hpp
Labels: refactoring, backend: cuda, backend: hip

#4676 PMacc: remove limits file
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/pmacc/math/vector/compile-time/Int.hpp
  include/pmacc/math/vector/compile-time/Size_t.hpp
  include/pmacc/math/vector/compile-time/UInt32.hpp
  include/pmacc/math/vector/compile-time/UInt64.hpp
  include/pmacc/traits/Limits.hpp
  include/pmacc/traits/Limits.tpp
Labels: component: PMacc, refactoring

#4677 Documentation: Release refactorings
  CONTRIBUTING.md
  README.md
Labels: documentation, refactoring, CI:no-compile

#4669 implement foilDistributions in PICMI
  lib/python/picongpu/picmi/__init__.py
  lib/python/picongpu/picmi/distribution.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/__init__.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/densityprofile.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/foil.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/plasmaramp/__init__.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/plasmaramp/exponential.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/plasmaramp/none.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/plasmaramp/plasmaramp.py
  lib/python/picongpu/requirements.txt
  share/picongpu/pypicongpu/schema/species/operation/densityprofile/densityprofile.DensityProfile.json
  share/picongpu/pypicongpu/schema/species/operation/densityprofile/foil.Foil.json
  share/picongpu/pypicongpu/schema/species/operation/densityprofile/plasmaramp/exponential.Exponential.json
  share/picongpu/pypicongpu/schema/species/operation/densityprofile/plasmaramp/none.None.json
  share/picongpu/pypicongpu/schema/species/operation/densityprofile/plasmaramp/plasmaramp.PlasmaRamp.json
  share/picongpu/pypicongpu/template/include/picongpu/param/density.param.mustache
  test/python/picongpu/quick/picmi/distribution.py
  test/python/picongpu/quick/pypicongpu/species/operation/densityprofile/densityprofile.py
Labels: CI:no-compile, PICMI

#4681 refactor particle init kernel
  include/picongpu/particles/ParticlesInit.kernel
Labels: component: core, refactoring

#4679 Add changelog for 0.7.0
  CHANGELOG.md
Labels: documentation, CI:no-compile

#4684 Add sincos to dispersive pulse
  include/picongpu/fields/incidentField/profiles/DispersivePulse.hpp
Labels: refactoring

#4651 Add an optional time delay for incident field pulses
  include/picongpu/fields/incidentField/Functors.hpp
  include/picongpu/fields/incidentField/profiles/BaseParam.def
  include/picongpu/fields/incidentField/profiles/BaseParam.hpp
  include/picongpu/fields/incidentField/profiles/DispersivePulse.def
  include/picongpu/fields/incidentField/profiles/DispersivePulse.hpp
  include/picongpu/fields/incidentField/profiles/ExpRampWithPrepulse.def
  include/picongpu/fields/incidentField/profiles/GaussianPulse.def
  include/picongpu/fields/incidentField/profiles/PlaneWave.def
  include/picongpu/fields/incidentField/profiles/Wavepacket.def
Labels: component: core, refactoring

#4680 change radiation plugin python module to openPMD-api
  docs/source/usage/plugins/radiation.rst
  include/picongpu/plugins/radiation/Radiation.hpp
  lib/python/picongpu/extra/plugins/data/radiation.py
Labels: component: plugin, component: tools, changelog

#4687 remove pulling namespace `pmacc::math::CT` into `pmacc`
  include/pmacc/dimensions/SuperCellDescription.hpp
Labels: component: PMacc, refactoring
