Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2023-10, with the labels that each got.

#4696 add missing euler number in ADK formula
  docs/source/models/field_ionization.rst
  include/picongpu/particles/ionization/byField/ADK/AlgorithmADK.hpp
  lib/python/picongpu/extra/utils/field_ionization.py
Labels: bug, component: core

#4689 rename unit current to unit current density
  include/picongpu/fields/FieldJ.tpp
Labels: component: core, documentation

#4693 fix interactive call in 5min tutorial
  docs/source/tutorials/hemeraIn5min.rst
Labels: documentation, CI:no-compile

#4695 simplify output structure colorimeter plugin
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
Labels: component: plugin, refactoring, changelog

#4690 remove missed references to master branch
  docs/COMMIT.md
  docs/source/dev/repostructure.rst
  docs/source/tutorials/hemeraIn5min.rst
Labels: documentation, CI:no-compile

#4700 Make rad bins pep8
  docs/source/usage/plugins/radiation.rst
  src/tools/bin/plotRadiation.py
  src/tools/bin/radiationSyntheticDetector.py
Labels: documentation, component: tools, CI:no-compile

#4691 fix comment on hdf5 vs adios and update examples
  docs/source/usage/plugins/radiation.rst
Labels: component: plugin, documentation, CI:no-compile

#4701 cherry-pick changes from dev to the release 0.7.0
  docs/source/tutorials/hemeraIn5min.rst
Labels: documentation

#4702 remove warning that particle shape naming changed
  include/picongpu/param/species.param
  share/picongpu/benchmarks/TWEAC-FOM/include/picongpu/param/species.param
  share/picongpu/benchmarks/Thermal/include/picongpu/param/species.param
  share/picongpu/examples/SingleParticleTest/include/picongpu/param/species.param
  share/picongpu/tests/CollisionsBeamRelaxation/include/picongpu/param/species.param
  share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/species.param
  share/picongpu/tests/KHI_growthRate/include/picongpu/param/species.param
  share/picongpu/tests/compileCurrentSolver/include/picongpu/param/species.param
  share/picongpu/tests/compileParticlePusher/include/picongpu/param/species.param
Labels: documentation

#4706 Special handling in mesh writing if getName() contains a slash
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: bug, component: plugin

#4707 add release date for 0.7.0
  CHANGELOG.md
Labels: documentation, CI:no-compile

#4709 Release cherry pick adk bug fix
  CHANGELOG.md
  docs/source/models/field_ionization.rst
  include/picongpu/particles/ionization/byField/ADK/AlgorithmADK.hpp
  lib/python/picongpu/extra/utils/field_ionization.py
Labels: bug, component: core, affects latest release

#4708 fix CI scripts
  share/ci/install/cmake.sh
  share/ci/pr_has_label.sh
Labels: bug, component: tests

#4712 RISC-V support
  cmake/riscv64-clang.toolchain.cmake
  cmake/riscv64-gnu.toolchain.cmake
  docs/source/index.rst
  docs/source/usage/crosscompile.rst
  include/mpiInfo/CMakeLists.txt
  include/picongpu/CMakeLists.txt
  include/pmacc/CMakeLists.txt
  include/pmacc/PMaccConfig.cmake
  share/ci/compiler_hipcc.yml
Labels: documentation, install

#4716 change order of PATH and fix wrong dev server path
  etc/picongpu/aris-grnet/gpu_picongpu.profile.example
  etc/picongpu/ascent-ornl/gpu_picongpu.profile.example
  etc/picongpu/bash-devServer-hzdr/cpu_picongpu.profile.example
  etc/picongpu/bash-devServer-hzdr/gpu_a30_picongpu.profile.example
  etc/picongpu/bash-devServer-hzdr/gpu_v100_picongpu.profile.example
  etc/picongpu/bash/bash_picongpu.profile.example
  etc/picongpu/cori-nersc/a100_picongpu.profile.example
  etc/picongpu/crusher-ornl/batch_craycc_picongpu.profile.example
  etc/picongpu/crusher-ornl/batch_hipcc_picongpu.profile.example
  etc/picongpu/davide-cineca/gpu_picongpu.profile.example
  etc/picongpu/draco-mpcdf/picongpu.profile.example
  etc/picongpu/frontier-ornl/batch_hipcc_picongpu.profile.example
  etc/picongpu/hemera-hzdr/defq_picongpu.profile.example
  etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example
  etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k20_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
  etc/picongpu/jureca-jsc/batch_picongpu.profile.example
  etc/picongpu/jureca-jsc/booster_picongpu.profile.example
  etc/picongpu/jureca-jsc/gpus_picongpu.profile.example
  etc/picongpu/juwels-jsc/batch_picongpu.profile.example
  etc/picongpu/juwels-jsc/booster_picongpu.profile.example
  etc/picongpu/juwels-jsc/gpus_picongpu.profile.example
  etc/picongpu/lumi-eurohpc/lumi-G_hipcc_picongpu.profile.example
  etc/picongpu/pizdaint-cscs/picongpu.profile.example
  etc/picongpu/spock-ornl/caar_picongpu.profile.example
  etc/picongpu/summit-ornl/gpu_picongpu.profile.example
  etc/picongpu/taurus-tud/A100_picongpu.profile.example
  etc/picongpu/taurus-tud/V100_picongpu.profile.example
  etc/picongpu/taurus-tud/k80_picongpu.profile.example
Labels: bug, machine/system, CI:no-compile

#4715 Vector/DataSpace N-dimensional constructor
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov.hpp
  include/picongpu/particles/startPosition/OnePositionImpl.hpp
  include/pmacc/dimensions/DataSpace.hpp
  include/pmacc/math/vector/Vector.hpp
Labels: component: PMacc, refactoring

#4721 remove unsed files, functions and classes
  docs/source/usage/param/plugins.rst
  include/picongpu/_defaultParam.loader
  include/picongpu/param/particleMerger.param
  include/picongpu/plugins/ChargeConservation.tpp
  include/pmacc/cudaSpecs.hpp
  include/pmacc/math/Vector.hpp
  include/pmacc/math/vector/Vector.tpp
  include/pmacc/math/vector/compile-time/Float.hpp
  include/pmacc/memory/IndexPool.hpp
  include/pmacc/traits/GetInitializedInstance.hpp
Labels: component: core, component: PMacc, refactoring

#4722 remove `atomicAddNoRet()`
  include/pmacc/kernel/atomic.hpp
  include/pmacc/kernel/operation/Atomic.hpp
Labels: component: PMacc, refactoring

#4720 restrict constexpr workaround
  include/pmacc/attribute/Constexpr.hpp
Labels: component: PMacc, refactoring

#4674 Non-Gaussian temporal envelope for Gaussian beam
  include/picongpu/fields/incidentField/profiles/ExpRampWithPrepulse.def
  include/picongpu/fields/incidentField/profiles/ExpRampWithPrepulse.hpp
  include/picongpu/fields/incidentField/profiles/GaussianPulse.def
  include/picongpu/fields/incidentField/profiles/GaussianPulse.hpp
  share/picongpu/examples/LaserWakefield/cmakeFlags
  share/picongpu/examples/LaserWakefield/include/picongpu/param/incidentField.param
Labels: component: core, refactoring
