Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2023-08, with the labels that each got.

#4643 fix flake8 complains in dev
  lib/python/picongpu/extra/input/bunchInit_openPMD_bp.py
  lib/python/picongpu/pypicongpu/rendering/renderedobject.py
  lib/python/picongpu/pypicongpu/rendering/renderer.py
  lib/python/picongpu/pypicongpu/runner.py
  lib/python/picongpu/pypicongpu/species/initmanager.py
  src/tools/bin/smooth.py
  test/python/picongpu/quick/picmi/distribution.py
  test/python/picongpu/quick/pypicongpu/species/initmanager.py
Labels: bug, component: tests

#4644 fix openPMD plugin output
  include/picongpu/plugins/openPMD/NDScalars.hpp
  include/picongpu/plugins/openPMD/WriteSpecies.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.def
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp
  include/picongpu/plugins/openPMD/restart/RestartFieldLoader.hpp
Labels: bug, component: plugin

#4655 Deletion of deprecated code in the old KHI test
  lib/python/test/KHI_growthRate/CalculateParameter.py
  lib/python/test/KHI_growthRate/DifferenceKHIGrowthRate.py
  lib/python/test/KHI_growthRate/KHIData.py
  lib/python/test/KHI_growthRate/KHIParams.py
  lib/python/test/KHI_growthRate/MainTest.py
  lib/python/test/KHI_growthRate/ParamReader.py
  lib/python/test/KHI_growthRate/TestKHI.py
  lib/python/test/KHI_growthRate/TestKHIManager.py
  lib/python/test/KHI_growthRate/TheoryGrowthRate.py
  lib/python/test/KHI_growthRate/ViewerKHI.py
  lib/python/test/KHI_growthRate/requirements.txt
Labels: component: examples, component: tests

#4656 Add missing #include <cstdint>
  include/picongpu/plugins/misc/ComponentNames.hpp
  include/pmacc/debug/abortWithError.hpp
Labels: bug

#4658 update LUMI standard-G tpl
  etc/picongpu/lumi-eurohpc/standard-g.tpl
Labels: component: tools, machine/system

#4657 update CMake in profiles to 3.22+
  etc/picongpu/ascent-ornl/gpu_picongpu.profile.example
  etc/picongpu/cori-nersc/a100_picongpu.profile.example
  etc/picongpu/davide-cineca/gpu_picongpu.profile.example
  etc/picongpu/draco-mpcdf/picongpu.profile.example
  etc/picongpu/hemera-hzdr/defq_picongpu.profile.example
  etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example
  etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k20_picongpu.profile.example
  etc/picongpu/hemera-hzdr/k80_picongpu.profile.example
  etc/picongpu/jureca-jsc/batch_picongpu.profile.example
  etc/picongpu/jureca-jsc/booster_picongpu.profile.example
  etc/picongpu/jureca-jsc/gpus_picongpu.profile.example
  etc/picongpu/juwels-jsc/batch_picongpu.profile.example
  etc/picongpu/juwels-jsc/booster_picongpu.profile.example
  etc/picongpu/juwels-jsc/gpus_picongpu.profile.example
  etc/picongpu/pizdaint-cscs/picongpu.profile.example
  etc/picongpu/spock-ornl/caar_picongpu.profile.example
  etc/picongpu/summit-ornl/gpu_picongpu.profile.example
  etc/picongpu/taurus-tud/A100_picongpu.profile.example
  etc/picongpu/taurus-tud/V100_picongpu.profile.example
  etc/picongpu/taurus-tud/k80_picongpu.profile.example
Labels: component: tools, refactoring, CI:no-compile
