Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2023-06, with the labels that each got.

#4586 Use SFINAE for determining if storeChunkRaw should be used
  include/picongpu/plugins/common/openPMDVersion.def
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: bug, machine/system

#4573 openPMD plugin: fix int overflow
  include/picongpu/plugins/openPMD/restart/RestartFieldLoader.hpp
Labels: bug, affects latest release

#4587 remove SPEC benchmark example
  share/picongpu/benchmarks/SPEC/cmakeFlags
  share/picongpu/benchmarks/SPEC/etc/picongpu/1.cfg
  share/picongpu/benchmarks/SPEC/etc/picongpu/1_radiation.cfg
  share/picongpu/benchmarks/SPEC/include/picongpu/param/density.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/fileOutput.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/grid.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/isaac.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/memory.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/particle.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/precision.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/radiation.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/radiationObserver.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/species.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/speciesDefinition.param
  share/picongpu/benchmarks/SPEC/include/picongpu/param/speciesInitialization.param
Labels: refactoring, component: examples

#4585 Range specification from --openPMD.toml
  docs/source/usage/plugins/openPMD.toml
  include/picongpu/plugins/openPMD/Parameters.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.def
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/picongpu/plugins/openPMD/toml.cpp
  include/picongpu/plugins/openPMD/toml.hpp
Labels: component: plugin, refactoring

#4334 Unified testsuite
  docs/images/ESKHI_MI.png
  docs/images/scan_3DKHI.png
  docs/images/vortice_scan.png
  docs/source/testing/examples.rst
  docs/source/testing/examples/MI.rst
  docs/source/testing/general.rst
  docs/source/testing/structure.rst
  docs/source/testing/testbuilding.rst
  docs/source/testing/usage.rst
  lib/python/test/setups/ESKHI/Data.py
  lib/python/test/setups/ESKHI/main.py
  lib/python/test/setups/MI/Data.py
  lib/python/test/setups/MI/main.py
  lib/python/test/testsuite/Math/__init__.py
  lib/python/test/testsuite/Math/_manager.py
  lib/python/test/testsuite/Math/_searchData.py
  lib/python/test/testsuite/Math/deviation.py
  lib/python/test/testsuite/Math/math.py
  lib/python/test/testsuite/Math/physics.py
  lib/python/test/testsuite/Math/requirements.txt
  lib/python/test/testsuite/Output/Log.py
  lib/python/test/testsuite/Output/Viewer.py
  lib/python/test/testsuite/Output/__init__.py
  lib/python/test/testsuite/Output/_manager.py
  lib/python/test/testsuite/Output/requirements.txt
  lib/python/test/testsuite/Reader/__init__.py
  lib/python/test/testsuite/Reader/_manager.py
  lib/python/test/testsuite/Reader/dataReader.py
  lib/python/test/testsuite/Reader/jsonReader.py
  lib/python/test/testsuite/Reader/paramReader.py
  lib/python/test/testsuite/Reader/requirements.txt
  lib/python/test/testsuite/Template/Data.py
  lib/python/test/testsuite/__init__.py
  lib/python/test/testsuite/_checkData.py
  lib/python/test/testsuite/_manager.py
  lib/python/test/testsuite/requirements.txt
  share/picongpu/tests/KHI_growthRate/bin/ci.sh
  share/picongpu/tests/KHI_growthRate/bin/validate.sh
Labels: refactoring, component: tests, CI:no-compile

#4584 fix Esirkepov current deposition 2D
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp
Labels: bug, component: core

#4588 particle collision
  include/picongpu/particles/collision/relativistic/RelativisticCollision.hpp
Labels: component: core, refactoring

#4582 fix 2D current deposition performance
  include/picongpu/fields/currentDeposition/EmZ/DepositCurrent.hpp
  include/picongpu/fields/currentDeposition/Esirkepov/Esirkepov2D.hpp
Labels: component: core, refactoring

#4597 GitLab CI: Fix disabled public runner
  .gitlab-ci.yml
Labels: component: tests

#4595 fix using wrong math functions
  include/picongpu/fields/absorber/pml/Pml.kernel
  include/picongpu/fields/incidentField/Functors.hpp
  include/picongpu/fields/incidentField/Solver.kernel
  include/picongpu/fields/incidentField/profiles/PlaneWave.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeterFunctors.hpp
  include/pmacc/math/complex/Bessel.tpp
Labels: bug, component: core, component: PMacc, warning

#4596 openPMD plugin: Fix TOML parameter for multiplugins
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
Labels: bug, component: plugin

#4602 Docs: Fix Build & HTML5
  .readthedocs.yaml
  docs/requirements.txt
  docs/source/_static/hide_chapter_titles.css
  docs/source/conf.py
  docs/source/install/profile.rst
  docs/source/testing/testbuilding.rst
  docs/source/usage/plugins/openPMD.rst
  share/picongpu/examples/atomicPhysics/README.rst
Labels: bug, documentation, CI:no-compile

#4613 Period syntax for progress ouptut
  docs/TBG_macros.cfg
  include/pmacc/simulationControl/SimulationHelper.cpp
  include/pmacc/simulationControl/SimulationHelper.hpp
Labels: component: PMacc

#4609 fix collision devision by zero
  include/picongpu/particles/collision/relativistic/RelativisticCollision.hpp
Labels: bug, component: core

#4600 PyPIConGPU compile test
  .gitlab-ci.yml
  share/ci/install/pypicongpu.sh
  share/ci/pypicongpu.yml
  test/python/picongpu/compiling/__main__.py
  test/python/picongpu/compiling/simulation.py
Labels: component: tools, component: tests

#4612 fix ionization
  include/picongpu/particles/atomicPhysics/SetChargeState.hpp
  include/picongpu/particles/atomicPhysics/SetToAtomicGroundStateForChargeState.hpp
  include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
  include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp
  include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp
  include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp
  include/picongpu/particles/manipulators/unary/ChargeState.hpp
  share/picongpu/examples/atomicPhysics/include/picongpu/param/particle.param
  share/picongpu/tests/CollisionsBeamRelaxation/include/picongpu/param/particle.param
  share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/particle.param
Labels: bug, component: core

#4615 improved debug bound checks for SetChargeState functor
  include/picongpu/particles/atomicPhysics/SetChargeState.hpp
  include/picongpu/particles/traits/GetAtomicNumbers.hpp
Labels: refactoring

#4616 rename SetToAtomicGroundStateForChargeState functor
  include/picongpu/particles/atomicPhysics/SetChargeState.hpp
  include/picongpu/particles/atomicPhysics/SetToAtomicGroundState.hpp
Labels: component: core, refactoring

#4614 Apply recent workarounds that are needed for Streaming on Frontier to .tpl file
  etc/picongpu/crusher-ornl/batch_pipe.tpl
Labels: component: tools, machine/system
