Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2023-07, with the labels that each got.

#4617 fix ExpRampWithPrepulseBeam
  include/picongpu/fields/incidentField/profiles/ExpRampWithPrepulse.hpp
Labels: bug, component: core

#4623 add lumi template and setup profile
  etc/picongpu/lumi-eurohpc/lumi-G_hipcc_picongpu.profile.example
  etc/picongpu/lumi-eurohpc/standard-g.tpl
Labels: machine/system, CI:no-compile

#4608 derived output particle momentum
  include/picongpu/particles/particleToGrid/derivedAttributes/Momentum.def
Labels: component: plugin, refactoring

#4607 change output naming in `WeightedVelocity`
  include/picongpu/particles/particleToGrid/derivedAttributes/WeightedVelocity.def
Labels: component: plugin, refactoring

#4606 momentum density output
  include/picongpu/particles/particleToGrid/derivedAttributes/MomentumDensity.def
Labels: component: plugin, refactoring

#4625 remove no longer needed info message for frontier profile
  etc/picongpu/frontier-ornl/batch_hipcc_picongpu.profile.example
Labels: machine/system, CI:no-compile

#4628 fixing failing PyPIConGPU CI jobs
  lib/python/picongpu/requirements.txt
  share/ci/pypicongpu_generator.py
Labels: bug, component: tools, component: tests

#4626 mpiInfo set RPath
  include/mpiInfo/CMakeLists.txt
Labels: bug

#4632 collision: reduce memory fragmentation
  docs/source/models/binary_collisions.rst
  include/picongpu/param/collision.param
  include/picongpu/particles/collision/detail/ListEntry.hpp
  share/picongpu/tests/CollisionsBeamRelaxation/include/picongpu/param/collision.param
  share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/collision.param
Labels: component: core, refactoring, component: user input

#4618 Fix units of phase space plugin and in documentation
  docs/source/usage/plugins/phaseSpace.rst
  include/picongpu/plugins/PhaseSpace/DumpHBufferOpenPMD.hpp
  lib/python/picongpu/extra/plugins/data/phase_space.py
Labels: bug, component: plugin, documentation, affects latest release

#4636 plugin openPMD: activate support for ED-PIC extension
  include/picongpu/plugins/common/openPMDWriteMeta.hpp
Labels: bug, component: plugin, affects latest release

#4637 fix broken KHI growth rate test tools
  lib/python/test/testsuite/Reader/readFiles.py
  share/picongpu/tests/KHI_growthRate/bin/ci.sh
  share/picongpu/tests/KHI_growthRate/bin/validate.sh
Labels: bug, component: tests

#4639 register solvers to data connector
  include/picongpu/fields/MaxwellSolver/FDTD/FDTD.hpp
  include/picongpu/fields/MaxwellSolver/None/None.hpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/simulation/stage/CurrentBackground.hpp
  include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp
Labels: component: core, refactoring

#4640 fix possible missed thread notification
  include/pmacc/simulationControl/SimulationHelper.cpp
  include/pmacc/simulationControl/SimulationHelper.hpp
Labels: bug, component: PMacc
