Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2024-02, with the labels that each got.

#4798 update system profiles
  etc/picongpu/bash-devServer-hzdr/cpu_install.sh
  etc/picongpu/bash-devServer-hzdr/cpu_picongpu.profile.example
  etc/picongpu/bash-devServer-hzdr/gpu_a30_install.sh
  etc/picongpu/bash-devServer-hzdr/gpu_a30_picongpu.profile.example
  etc/picongpu/bash-devServer-hzdr/gpu_v100_install.sh
  etc/picongpu/bash-devServer-hzdr/gpu_v100_picongpu.profile.example
  etc/picongpu/crusher-ornl/batch_craycc_picongpu.profile.example
  etc/picongpu/crusher-ornl/batch_hipcc_picongpu.profile.example
  etc/picongpu/frontier-ornl/batch_hipcc_picongpu.profile.example
  etc/picongpu/hemera-hzdr/defq_picongpu.profile.example
  etc/picongpu/hemera-hzdr/fwkt_v100_picongpu.profile.example
  etc/picongpu/lumi-eurohpc/lumi-G_hipcc_picongpu.profile.example
  etc/picongpu/summit-ornl/gpu_picongpu.profile.example
Labels: component: tools, machine/system, CI:no-compile

#4803 update summit profile
  etc/picongpu/summit-ornl/gpu_batch.tpl
  etc/picongpu/summit-ornl/gpu_picongpu.profile.example
Labels: component: tools, machine/system, CI:no-compile

#4804 Make cPow's exponent unsigned
  include/pmacc/algorithms/math/PowerFunction.hpp
  share/pmacc/examples/heatEquation2D/include/StencilFourPoint.hpp
Labels: bug, component: PMacc

#4809 fix and update for dev server profiles
  etc/picongpu/bash-devServer-hzdr/cpu_install.sh
  etc/picongpu/bash-devServer-hzdr/cpu_picongpu.profile.example
  etc/picongpu/bash-devServer-hzdr/gpu_a30_install.sh
  etc/picongpu/bash-devServer-hzdr/gpu_a30_picongpu.profile.example
  etc/picongpu/bash-devServer-hzdr/gpu_v100_install.sh
  etc/picongpu/bash-devServer-hzdr/gpu_v100_picongpu.profile.example
Labels: bug, component: tools, machine/system

#4808 Remove reference to Doxygen
  docs/source/index.rst
Labels: bug, documentation

#4806 fix frontier profile
  etc/picongpu/frontier-ornl/batch_picongpu.profile.example
Labels: bug, component: tools, machine/system, CI:no-compile

#4805 Docs Lockstep
  docs/source/prgpatterns/lockstep.rst
Labels: component: PMacc, documentation, CI:no-compile

#4819 remove mentioning of PoGit
  docs/source/usage/param.rst
Labels: documentation, CI:no-compile

#4824 Improve wording for return value of CFLChecker
  include/picongpu/fields/MaxwellSolver/ArbitraryOrderFDTD/ArbitraryOrderFDTD.hpp
  include/picongpu/fields/MaxwellSolver/CFLChecker.hpp
  include/picongpu/fields/MaxwellSolver/Lehe/Lehe.hpp
  include/picongpu/fields/MaxwellSolver/None/None.hpp
  include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
Labels: documentation

#4825 fix `atomicAllInc()`
  include/pmacc/kernel/atomic.hpp
  include/pmacc/kernel/warp.hpp
Labels: bug, component: PMacc, backend: cuda, changelog

#4661 add CKC Solver
  include/picongpu/fields/MaxwellSolver/CKC/CKC.def
  include/picongpu/fields/MaxwellSolver/CKC/CKC.hpp
  include/picongpu/fields/MaxwellSolver/CKC/Derivative.def
  include/picongpu/fields/MaxwellSolver/CKC/Derivative.hpp
  include/picongpu/fields/MaxwellSolver/Solvers.def
  include/picongpu/fields/MaxwellSolver/Solvers.hpp
  include/picongpu/param/fieldSolver.param
  share/picongpu/examples/IncidentField/include/picongpu/param/fieldSolver.param
  share/picongpu/examples/TransitionRadiation/include/picongpu/param/fieldSolver.param
  share/picongpu/tests/CollisionsBeamRelaxation/include/picongpu/param/fieldSolver.param
  share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/fieldSolver.param
  share/picongpu/tests/FieldAbsorber/include/picongpu/param/fieldSolver.param
  share/picongpu/tests/compileCurrentSolver/include/picongpu/param/fieldSolver.param
  share/picongpu/tests/compileFieldSolver/include/picongpu/param/fieldSolver.param
  share/picongpu/tests/compileLaser/include/picongpu/param/fieldSolver.param
Labels: component: core, feature request, changelog

#4821 remove deactivation of ISAAC with HIP
  share/ci/compiler_hipcc.yml
Labels: component: plugin, documentation, backend: hip

#4828 optimize collision
  include/picongpu/particles/collision/InterCollision.hpp
  include/picongpu/particles/collision/IntraCollision.hpp
Labels: component: core, refactoring

#4811 refactor ListEntry used in collision
  include/picongpu/particles/collision/InterCollision.hpp
  include/picongpu/particles/collision/IntraCollision.hpp
  include/picongpu/particles/collision/detail/ListEntry.hpp
  include/picongpu/particles/collision/detail/cellDensity.hpp
Labels: bug, component: core

#4833 Small fix and cosmetic changes in snakemake files
  share/picongpu/examples/LaserWakefield/lib/python/snakemake/README.md
  share/picongpu/examples/LaserWakefield/lib/python/snakemake/Snakefile
Labels: component: tools, refactoring, CI:no-compile
