Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2024-09, with the labels that each got.

#5059 refactor `pmacc::math::Vector`
  include/picongpu/fields/MaxwellSolver/DispersionRelation.hpp
  include/picongpu/fields/incidentField/Functors.hpp
  include/picongpu/particles/densityProfiles/EveryNthCellImpl.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.x.cpp
  include/picongpu/traits/GetMetadata.hpp
  include/pmacc/dimensions/DataSpace.hpp
  include/pmacc/kernel/operation/Atomic.hpp
  include/pmacc/math/ConstVector.hpp
  include/pmacc/math/vector/TwistComponents.hpp
  include/pmacc/math/vector/Vector.hpp
  include/pmacc/math/vector/Vector.tpp
  include/pmacc/math/vector/compile-time/TwistComponents.hpp
  include/pmacc/math/vector/compile-time/Vector.hpp
  include/pmacc/math/vector/navigator/IdentityNavigator.hpp
  include/pmacc/math/vector/navigator/PermutedNavigator.hpp
  include/pmacc/math/vector/navigator/StackedNavigator.hpp
  include/pmacc/test/vector/vectorUT.cpp
  share/picongpu/examples/IncidentField/include/picongpu/param/incidentField.param
Labels: component: PMacc, refactoring

#5073 CI: reduce number of compile combinations
  .gitlab-ci.yml
  share/ci/generate_reduced_matrix.sh
  share/ci/n_wise_generator.py
  share/picongpu/benchmarks/TWEAC-FOM/cmakeFlags
  share/picongpu/examples/Bunch/cmakeFlags
  share/picongpu/examples/FoilLCT/cmakeFlags
  share/picongpu/examples/IncidentField/cmakeFlags
  share/picongpu/examples/KelvinHelmholtz/cmakeFlags
  share/picongpu/examples/LaserWakefield/cmakeFlags
  share/picongpu/tests/CollisionsBeamRelaxation/cmakeFlags
  share/picongpu/tests/CurrentDeposition/cmakeFlags
  share/picongpu/tests/FieldAbsorber/cmakeFlags
  share/picongpu/tests/Pusher/cmakeFlags
  share/picongpu/tests/SingleParticle/cmakeFlags
  share/picongpu/tests/SingleParticle/etc/picongpu/1.cfg
  share/picongpu/tests/SingleParticle/include/picongpu/param/density.param
  share/picongpu/tests/SingleParticle/include/picongpu/param/dimension.param
  share/picongpu/tests/SingleParticle/include/picongpu/param/fieldBackground.param
  share/picongpu/tests/SingleParticle/include/picongpu/param/fileOutput.param
  share/picongpu/tests/SingleParticle/include/picongpu/param/particle.param
  share/picongpu/tests/SingleParticle/include/picongpu/param/simulation.param
  share/picongpu/tests/SingleParticle/include/picongpu/param/species.param
  share/picongpu/tests/SingleParticle/include/picongpu/param/speciesDefinition.param
  share/picongpu/tests/SingleParticle/include/picongpu/param/speciesInitialization.param
  share/picongpu/tests/compile/cmakeFlags
  share/picongpu/tests/compileLaser/cmakeFlags
Labels: component: tests

#5068 PMacc: fix `constexpr math::Vector`
  include/pmacc/math/vector/Vector.hpp
  include/pmacc/test/vector/vectorUT.cpp
Labels: bug, component: PMacc

#5074 CI: control via commit message
  .gitlab-ci.yml
  docs/source/dev/ci.rst
  docs/source/index.rst
  share/ci/generate_reduced_matrix.sh
Labels: documentation, component: tests

#5076 fix in code comment Counter shape
  include/picongpu/particles/shapes/Counter.hpp
Labels: bug, component: core, documentation

#5051 raditation unit tests
  include/picongpu/plugins/radiation/VectorTypes.hpp
  share/picongpu/unit/radiationFormFactor.cpp
  share/picongpu/unit/radiationWindowFunction.cpp
Labels: refactoring, component: examples, component: tests

#5077 CI:: fix download micro mamba
  share/ci/install/pypicongpu.sh
Labels: bug, component: tests

#5075 unit test: fix warning
  share/picongpu/unit/MoveParticle.cpp
Labels: warning, component: tests

#5067 Topic switch to static cast short hands in atomic physics
  include/picongpu/particles/atomicPhysics/atomicData/AtomicData.hpp
  include/picongpu/particles/atomicPhysics/atomicData/ChargeStateData.hpp
  include/picongpu/particles/atomicPhysics/atomicData/ChargeStateOrgaData.hpp
  include/picongpu/particles/atomicPhysics/debug/TestRateCalculation.hpp
  include/picongpu/particles/atomicPhysics/electronDistribution/LogSpaceHistogram.hpp
  include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
  include/picongpu/particles/atomicPhysics/enums/IsProcess.hpp
  include/picongpu/particles/atomicPhysics/enums/LastResortProcessClass.hpp
  include/picongpu/particles/atomicPhysics/enums/ProcessClass.hpp
  include/picongpu/particles/atomicPhysics/enums/ProcessClassGroup.hpp
  include/picongpu/particles/atomicPhysics/enums/TransitionDirection.hpp
  include/picongpu/particles/atomicPhysics/enums/TransitionOrdering.hpp
  include/picongpu/particles/atomicPhysics/enums/TransitionType.hpp
  include/picongpu/particles/atomicPhysics/initElectrons/Inelastic2BodyCollisionFromCoMoving.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/ApplyPressureIonization.kernel
  include/picongpu/particles/atomicPhysics/kernel/CheckForOverSubscription.kernel
  include/picongpu/particles/atomicPhysics/kernel/FillLocalRateCache_Autonomous.kernel
  include/picongpu/particles/atomicPhysics/kernel/FillLocalRateCache_BoundBound.kernel
  include/picongpu/particles/atomicPhysics/kernel/FillLocalRateCache_BoundFree.kernel
  include/picongpu/particles/atomicPhysics/kernel/FixAtomicState.kernel
  include/picongpu/particles/atomicPhysics/kernel/RecordChanges.kernel
  include/picongpu/particles/atomicPhysics/kernel/SpawnIonizationMacroElectrons.kernel
  include/picongpu/particles/atomicPhysics/rateCalculation/BinomialCoefficient.hpp
  include/picongpu/particles/atomicPhysics/rateCalculation/BoundBoundTransitionRates.hpp
  include/picongpu/particles/atomicPhysics/rateCalculation/BoundFreeTransitionRates.hpp
  include/picongpu/particles/atomicPhysics/rateCalculation/Multiplicities.hpp
  include/picongpu/particles/atomicPhysics/stateRepresentation/DebugHelperConfigNumber.hpp
Labels: component: core, refactoring

#5069 fix synchrotron radiation floating point overflow warning
  include/picongpu/particles/synchrotron/AlgorithmSynchrotron.hpp
Labels: component: core, warning

#5070 reduce CI compile time for atomicPhysics compile test
  share/picongpu/tests/compileAtomicPhysics/include/picongpu/param/density.param
  share/picongpu/tests/compileAtomicPhysics/include/picongpu/param/fileOutput.param
  share/picongpu/tests/compileAtomicPhysics/include/picongpu/param/particle.param
  share/picongpu/tests/compileAtomicPhysics/include/picongpu/param/species.param
Labels: component: tests

#5071 Topic update atomic physics todos
  include/picongpu/param/physicalConstants.param
  include/picongpu/particles/atomicPhysics/SuperCellField.hpp
  include/picongpu/particles/atomicPhysics/atomicData/AtomicData.hpp
  include/picongpu/particles/atomicPhysics/debug/TestRateCalculation.hpp
  include/picongpu/particles/atomicPhysics/kernel/CheckPresence.kernel
  include/picongpu/particles/atomicPhysics/kernel/RollForOverSubscription.kernel
Labels: documentation

#5090 move stages, plugins into own compile unit
  include/picongpu/particles/ParticlesFunctors.hpp
  include/picongpu/particles/debyeLength/Check.hpp
  include/picongpu/particles/debyeLength/Check.x.cpp
  include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp
  include/picongpu/particles/ionization/byField/IonizationCurrent/IonizationCurrent.hpp
  include/picongpu/particles/ionization/byField/IonizationCurrent/JIonizationAssignment.hpp
  include/picongpu/plugins/PluginController.hpp
  include/picongpu/plugins/PngPlugin.x.cpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/simulation/stage/AtomicPhysics.x.cpp
  include/picongpu/simulation/stage/ParticleBoundaries.hpp
  include/picongpu/simulation/stage/ParticleBoundaries.x.cpp
  include/picongpu/simulation/stage/ParticleInit.x.cpp
  include/picongpu/simulation/stage/ParticleIonization.x.cpp
  include/picongpu/simulation/stage/ParticlePush.hpp
  include/picongpu/simulation/stage/ParticlePush.x.cpp
Labels: component: core

#5079 change atomic physics particle attributes
  include/picongpu/param/speciesAttributes.param
  include/picongpu/particles/atomicPhysics/SetChargeState.hpp
Labels: component: core, refactoring

#5091 make precisionCast `constexpr`
  include/pmacc/algorithms/TypeCast.hpp
  include/pmacc/dimensions/DataSpace.tpp
  include/pmacc/math/vector/Vector.tpp
  include/pmacc/test/vector/vectorUT.cpp
Labels: component: PMacc

#5080 refactor `value_identifier_func`
  include/picongpu/param/speciesAttributes.param
  include/picongpu/particles/ParticlesInit.kernel
  include/pmacc/identifier/value_identifier.hpp
  include/pmacc/particles/memory/dataTypes/Particle.hpp
  include/pmacc/particles/operations/SetAttributeToDefault.hpp
Labels: component: PMacc, refactoring

#5092 remove duplicated comments
  include/picongpu/particles/debyeLength/Check.x.cpp
  include/picongpu/simulation/stage/ParticleInit.x.cpp
Labels: component: core, documentation, CI:no-compile

#5096 Adjust openPMD alias in python
  docs/source/usage/plugins/radiation.rst
  docs/source/usage/plugins/shadowgraphy.rst
  lib/python/picongpu/extra/input/bunchInit_openPMD_bp.py
  lib/python/picongpu/extra/plugins/data/calorimeter.py
  lib/python/picongpu/extra/plugins/data/phase_space.py
  lib/python/picongpu/extra/plugins/data/radiation.py
  share/picongpu/tests/CurrentDeposition/lib/python/test/CurrentDeposition/MainTest.py
  share/picongpu/tests/FieldAbsorber/lib/python/test/FieldAbsorber/validate.py
  share/picongpu/tests/Pusher/lib/python/test/Pusher/MainTest.py
  share/picongpu/tests/PusherScaling/lib/python/test/Pusher/MainTest.py
  share/picongpu/tests/Shadowgraphy/lib/python/test/Shadowgraphy/validate.py
  share/picongpu/tests/Synchrotron_plugin/lib/validate.py
  src/tools/bin/plot_chargeConservation.py
  src/tools/bin/plot_chargeConservation_overTime.py
Labels: documentation, component: tests

#5094 PMacc: refactor `FileSystem.hpp`
  include/picongpu/plugins/PhaseSpace/PhaseSpace.x.cpp
  include/picongpu/plugins/makroParticleCounter/PerSuperCell.x.cpp
  include/picongpu/plugins/openPMD/openPMDWriter.x.cpp
  include/picongpu/plugins/output/images/PngCreator.tpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.x.cpp
  include/picongpu/plugins/radiation/Radiation.x.cpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.x.cpp
  include/pmacc/Environment.hpp
  include/pmacc/Environment.tpp
  include/pmacc/mappings/simulation/Filesystem.cpp
  include/pmacc/mappings/simulation/Filesystem.hpp
  include/pmacc/simulationControl/SimulationHelper.cpp
Labels: component: PMacc, refactoring

#5097 Add automatic adjustment docs
  docs/source/usage/tbg.rst
  include/picongpu/simulation/control/DomainAdjuster.hpp
Labels: documentation, CI:no-compile

#5106 Remove instructions from docs
  docs/source/install/instructions.rst
  docs/source/install/instructions/source.rst
Labels: documentation, CI:no-compile

#5109 Add Lenz to zenodo
  .zenodo.json
Labels: CI:no-compile

#5105 fix case insensitive bug
  include/picongpu/fields/MaxwellSolver/FDTD/FDTDBase.hpp
  include/picongpu/fields/absorber.hpp
  include/picongpu/particles/boundary/Absorbing.hpp
  include/picongpu/plugins/common/openPMDWriteMeta.hpp
  include/picongpu/simulation/control/DomainAdjuster.hpp
  include/picongpu/simulation/stage/FieldAbsorber.hpp
Labels: bug

#5102 add missing getMargin includes
  include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
  include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp
  include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp
  include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp
Labels: bug, component: core

#5108 fix `ci: picongpu` command
  share/ci/generate_reduced_matrix.sh
Labels: bug, component: tests

#5101 remove cell type `centered`
  include/picongpu/fields/FieldJ.x.cpp
  include/picongpu/fields/MaxwellSolver/FDTD/FDTD.hpp
  include/picongpu/fields/MaxwellSolver/FDTD/FDTDBase.hpp
  include/picongpu/fields/MaxwellSolver/FDTD/FDTDBase.kernel
  include/picongpu/fields/MaxwellSolver/None/None.hpp
  include/picongpu/fields/YeeCell.hpp
  include/picongpu/fields/absorber/pml/Field.hpp
  include/picongpu/fields/background/templates/TWTS/BField.tpp
  include/picongpu/fields/background/templates/TWTS/EField.tpp
  include/picongpu/fields/background/templates/TWTS/getFieldPositions_SI.tpp
  include/picongpu/fields/background/templates/twtsfast/BField.tpp
  include/picongpu/fields/background/templates/twtsfast/EField.tpp
  include/picongpu/fields/background/templates/twtsfast/getFieldPositions_SI.tpp
  include/picongpu/fields/cellType/Centered.hpp
  include/picongpu/fields/incidentField/EnabledProfiles.hpp
  include/picongpu/fields/incidentField/Functors.hpp
  include/picongpu/fields/incidentField/Solver.hpp
  include/picongpu/fields/incidentField/Traits.hpp
  include/picongpu/fields/incidentField/ZeroFunctor.hpp
  include/picongpu/fields/incidentField/calculatePhaseVelocity.hpp
  include/picongpu/fields/incidentField/profiles/DispersivePulse.hpp
  include/picongpu/fields/incidentField/profiles/ExpRampWithPrepulse.hpp
  include/picongpu/fields/incidentField/profiles/Free.hpp
  include/picongpu/fields/incidentField/profiles/GaussianPulse.hpp
  include/picongpu/fields/incidentField/profiles/None.hpp
  include/picongpu/fields/incidentField/profiles/PlaneWave.hpp
  include/picongpu/fields/incidentField/profiles/Polynom.hpp
  include/picongpu/fields/incidentField/profiles/Wavepacket.hpp
  include/picongpu/fields/incidentField/traits/GetAmplitude.hpp
  include/picongpu/fields/incidentField/traits/GetFunctor.hpp
  include/picongpu/fields/incidentField/traits/GetPhaseVelocity.hpp
  include/picongpu/initialization/InitialiserController.hpp
  include/picongpu/particles/Particles.kernel
  include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
  include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp
  include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp
  include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp
  include/picongpu/particles/synchrotron/AlgorithmSynchrotron.hpp
  include/picongpu/plugins/common/openPMDWriteMeta.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.x.cpp
  include/picongpu/plugins/output/images/Visualisation.hpp
  include/picongpu/plugins/radiation/amplitude.hpp
  include/picongpu/traits/FieldPosition.hpp
  include/picongpu/traits/GetCellType.hpp
  include/picongpu/traits/GetMargin.hpp
Labels: component: core, refactoring

#4649 TransitionRadiation plugin openPMD output
  docs/source/usage/plugins/transitionRadiation.rst
  include/picongpu/param/transitionRadiation.param
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.kernel
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.x.cpp
  include/picongpu/unitless/transitionRadiation.unitless
  lib/python/picongpu/extra/plugins/data/transitionradiation.py
  share/picongpu/examples/TransitionRadiation/etc/picongpu/1.cfg
  share/picongpu/examples/TransitionRadiation/etc/picongpu/16.cfg
  share/picongpu/examples/TransitionRadiation/include/picongpu/param/transitionRadiation.param
Labels: component: plugin, refactoring, changelog

#5093 precision selection for PIConGPU quantities
  include/picongpu/unitless/simulation.unitless
Labels: component: core, refactoring

#5107 CI: add PIConGPU header check
  .gitlab-ci.yml
  include/picongpu/MetadataRegisteredAtCT.hpp
  include/picongpu/algorithms/AssignedTrilinearInterpolation.hpp
  include/picongpu/algorithms/FieldToParticleInterpolation.hpp
  include/picongpu/algorithms/Gamma.hpp
  include/picongpu/algorithms/KinEnergy.hpp
  include/picongpu/algorithms/ShiftCoordinateSystem.hpp
  include/picongpu/algorithms/Velocity.hpp
  include/picongpu/fields/MaxwellSolver/ArbitraryOrderFDTD/Derivative.hpp
  include/picongpu/param/speciesAttributes.param
  include/picongpu/particles/shapes/ShapeSelector.hpp
  include/picongpu/traits/FieldPosition.hpp
  include/picongpu/traits/IsFieldDomainBound.hpp
  include/picongpu/traits/PICToOpenPMD.hpp
  include/picongpu/traits/PICToOpenPMD.tpp
  include/picongpu/traits/SIBaseUnits.hpp
  include/picongpu/traits/Unit.hpp
  include/picongpu/traits/UnitDimension.hpp
  share/ci/generate_reduced_matrix.sh
  share/ci/run_header_tests.sh
  share/ci/run_tests.sh
  test/picongpuHeaderCheck/CMakeLists.txt
  test/picongpuHeaderCheck/src/main.cpp
Labels: component: tests

#5113 set minimum CMake version back to 3.22
  .gitlab-ci.yml
  INSTALL.rst
  include/picongpu/CMakeLists.txt
  include/pmacc/CMakeLists.txt
  include/pmacc/PMaccConfig.cmake
  include/pmacc/test/random/CMakeLists.txt
  share/ci/install/cmake.sh
  share/picongpu/unit/CMakeLists.txt
  test/picongpuHeaderCheck/CMakeLists.txt
  test/pmaccHeaderCheck/CMakeLists.txt
Labels: refactoring, install

#5116 fix FixAtomicState Kernel
  include/picongpu/particles/atomicPhysics/kernel/FixAtomicState.kernel
  include/picongpu/particles/atomicPhysics/stage/FixAtomicState.hpp
Labels: bug, component: core

#5117 Fix cmake prefix path for mpiInfo
  include/mpiInfo/CMakeLists.txt
Labels: bug, component: tools

#5098 Add ADK field ionization to FLYonPIC
  include/picongpu/param/atomicPhysics.param
  include/picongpu/particles/atomicPhysics/atomicData/AtomicData.hpp
  include/picongpu/particles/atomicPhysics/debug/TestRateCalculation.hpp
  include/picongpu/particles/atomicPhysics/electronDistribution/LogSpaceHistogram.hpp
  include/picongpu/particles/atomicPhysics/enums/ADKLaserPolarization.hpp
  include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroup.hpp
  include/picongpu/particles/atomicPhysics/enums/ChooseTransitionGroupFor.hpp
  include/picongpu/particles/atomicPhysics/enums/LastResortProcessClass.hpp
  include/picongpu/particles/atomicPhysics/initElectrons/InitIonizationElectrons.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/StewartPyattIPD.hpp
  include/picongpu/particles/atomicPhysics/kernel/CalculateStepLength.kernel
  include/picongpu/particles/atomicPhysics/kernel/ChooseTransitionGroup.kernel
  include/picongpu/particles/atomicPhysics/kernel/ChooseTransition_CollisionalBoundFree.kernel
  include/picongpu/particles/atomicPhysics/kernel/ChooseTransition_FieldBoundFree.kernel
  include/picongpu/particles/atomicPhysics/kernel/FillLocalRateCache_BoundFree.kernel
  include/picongpu/particles/atomicPhysics/kernel/RecordUsedElectronHistogramWeight.kernel
  include/picongpu/particles/atomicPhysics/kernel/SpawnIonizationMacroElectrons.kernel
  include/picongpu/particles/atomicPhysics/localHelperFields/RateCache.hpp
  include/picongpu/particles/atomicPhysics/rateCalculation/AtomicRateCalculation.hpp
  include/picongpu/particles/atomicPhysics/rateCalculation/BoundFreeCollisionalTransitionRates.hpp
  include/picongpu/particles/atomicPhysics/rateCalculation/BoundFreeFieldTransitionRates.hpp
  include/picongpu/particles/atomicPhysics/stage/ChooseTransition.hpp
  include/picongpu/particles/atomicPhysics/stage/DecelerateElectrons.hpp
  include/picongpu/particles/atomicPhysics/stage/FillLocalRateCache.hpp
  include/picongpu/particles/atomicPhysics/stage/RecordSuggestedChanges.hpp
  include/picongpu/particles/atomicPhysics/stage/SpawnIonizationElectrons.hpp
  share/picongpu/tests/compileAtomicPhysics/include/picongpu/param/atomicPhysics.param
Labels: component: core, refactoring

#5121 Updating alpha centauri profiles at TUD-ZIH
  etc/picongpu/taurus-tud/A100.tpl
  etc/picongpu/taurus-tud/A100_picongpu.profile.example
  etc/picongpu/taurus-tud/A100_restart.tpl
Labels: component: tools, machine/system

#5110 Update frontier-olcf profiles
  etc/picongpu/frontier-ornl/batch.tpl
  etc/picongpu/frontier-ornl/batch_picongpu.profile.example
  etc/picongpu/frontier-ornl/batch_pipe.tpl
Labels: machine/system, CI:no-compile

#5118 refactor fix atomic state kernel
  include/picongpu/particles/atomicPhysics/kernel/FixAtomicState.kernel
Labels: component: core, refactoring

#5125 Update hemeraIn5min.rst
  docs/source/tutorials/hemeraIn5min.rst
Labels: documentation, CI:no-compile

#5128 fix unit electric field definition
  include/picongpu/unitless/simulation.unitless
Labels: bug, component: core

#5099 fix warning in PyPIConGPU version tests
  share/ci/install/pypicongpu.sh
  share/ci/install/requirements_txt_modifier.py
Labels: component: tests, CI:no-compile, PICMI

#5122 fix out of bounds memory access in RollForOverSubscription
  include/picongpu/particles/atomicPhysics/kernel/RollForOverSubscription.kernel
Labels: bug, component: core

#5120 update default param comments
  include/picongpu/param/atomicPhysics_Debug.param
  include/picongpu/param/species.param
Labels: documentation, component: user input

#5100 seperate atomic data box checks
  include/picongpu/particles/atomicPhysics/kernel/ChooseTransition_Autonomous.kernel
  include/picongpu/particles/atomicPhysics/kernel/ChooseTransition_BoundBound.kernel
  include/picongpu/particles/atomicPhysics/kernel/FillLocalRateCache_BoundBound.kernel
  include/picongpu/particles/atomicPhysics/kernel/SpawnIonizationMacroElectrons.kernel
Labels: component: core, refactoring

#5126 replace EPS0,Z0,MUE0
  include/picongpu/algorithms/Velocity.hpp
  include/picongpu/fields/MaxwellSolver/FDTD/FDTD.hpp
  include/picongpu/fields/MaxwellSolver/Substepping/Substepping.hpp
  include/picongpu/fields/absorber/pml/Pml.kernel
  include/picongpu/initialization/InitialiserController.hpp
  include/picongpu/param/fieldAbsorber.param
  include/picongpu/param/physicalConstants.param
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/StewartPyattIPD.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
  include/picongpu/particles/atomicPhysics/rateCalculation/BoundBoundTransitionRates.hpp
  include/picongpu/particles/collision/relativistic/RelativisticCollisionDynamicLog.hpp
  include/picongpu/particles/debyeLength/Estimate.kernel
  include/picongpu/particles/particleToGrid/combinedAttributes/ScreeningInvSquared.hpp
  include/picongpu/particles/particleToGrid/derivedAttributes/LarmorPower.hpp
  include/picongpu/particles/pusher/particlePusherReducedLandauLifshitz.hpp
  include/picongpu/particles/synchrotron/AlgorithmSynchrotron.hpp
  include/picongpu/plugins/ChargeConservation.tpp
  include/picongpu/plugins/EnergyFields.x.cpp
  include/picongpu/plugins/common/openPMDWriteMeta.hpp
  include/picongpu/plugins/output/images/Visualisation.hpp
  include/picongpu/plugins/radiation/amplitude.hpp
  include/picongpu/plugins/shadowgraphy/ShadowgraphyHelper.hpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.x.cpp
  include/picongpu/unitless/collision.unitless
  include/picongpu/unitless/fieldAbsorber.unitless
  include/picongpu/unitless/physicalConstants.unitless
  include/picongpu/unitless/simulation.unitless
  share/picongpu/benchmarks/TWEAC-FOM/include/picongpu/param/fieldBackground.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/fieldAbsorber.param
  share/picongpu/tests/FieldAbsorber/include/picongpu/param/fieldAbsorber.param
Labels: component: core, refactoring

#5124 remove clang extension usage
  include/picongpu/plugins/openPMD/WriteSpecies.hpp
Labels: component: plugin, warning

#5123 update cuda_memtest
  thirdParty/cuda_memtest/CMakeLists.txt
Labels: bug, component: third party

#5104 Clarify use of snakemake params in scripts
  docs/source/usage/parameter_scans.rst
Labels: documentation, component: tools, CI:no-compile

#5131 refactor: `HBAR`, `RYDBERG_ENERGY` and `BOHR_RADIOUS`
  docs/source/usage/workflows/synchrotronExtensionDocumentation.rst
  include/picongpu/param/ionizer.param
  include/picongpu/param/physicalConstants.param
  include/picongpu/param/synchrotron.param
  include/picongpu/particles/atomicPhysics/GetPhysicalEnergy.hpp
  include/picongpu/particles/atomicPhysics/initElectrons/Inelastic2BodyCollisionFromCoMoving.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/StewartPyattIPD.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
  include/picongpu/particles/atomicPhysics/kernel/DecelerateElectrons.kernel
  include/picongpu/particles/atomicPhysics/rateCalculation/BoundBoundTransitionRates.hpp
  include/picongpu/particles/atomicPhysics/rateCalculation/BoundFreeCollisionalTransitionRates.hpp
  include/picongpu/particles/atomicPhysics/rateCalculation/CollisionalRate.hpp
  include/picongpu/particles/boundary/Thermal.hpp
  include/picongpu/particles/collision/relativistic/RelativisticCollisionDynamicLog.hpp
  include/picongpu/particles/debyeLength/Estimate.kernel
  include/picongpu/particles/ionization/byCollision/ThomasFermi/AlgorithmThomasFermi.hpp
  include/picongpu/particles/manipulators/unary/Temperature.hpp
  include/picongpu/particles/synchrotron/AlgorithmSynchrotron.hpp
  include/picongpu/plugins/BinEnergyParticles.x.cpp
  include/picongpu/plugins/binning/UnitConversion.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.x.cpp
  include/picongpu/unitless/physicalConstants.unitless
  include/picongpu/unitless/simulation.unitless
  share/picongpu/tests/CollisionsBeamRelaxation/include/picongpu/param/particle.param
  share/picongpu/tests/CollisionsThermalisation/include/picongpu/param/particle.param
  share/picongpu/tests/Synchrotron_plugin/include/picongpu/param/synchrotron.param
  share/picongpu/tests/compileAtomicPhysics/include/picongpu/param/ionizer.param
Labels: component: core, refactoring, component: user input

#5114 CI: update compile matrix
  include/pmacc/dataManagement/AbstractInitialiser.hpp
  include/pmacc/type/Exchange.hpp
  share/ci/compiler_hipcc.yml
  share/ci/install/clang.sh
  share/ci/n_wise_generator.py
Labels: component: tests

#5134 Add new CI Variable PIC_CI_MAINLINE
  .gitlab-ci.yml
  share/picongpu/benchmarks/TWEAC-FOM/cmakeFlags
  share/picongpu/benchmarks/Thermal/cmakeFlags
  share/picongpu/examples/Bunch/cmakeFlags
  share/picongpu/examples/FoilLCT/cmakeFlags
  share/picongpu/examples/IncidentField/cmakeFlags
  share/picongpu/examples/KelvinHelmholtz/cmakeFlags
  share/picongpu/examples/LaserWakefield/cmakeFlags
  share/picongpu/tests/CollisionsBeamRelaxation/cmakeFlags
  share/picongpu/tests/CollisionsThermalisation/cmakeFlags
  share/picongpu/tests/CurrentDeposition/cmakeFlags
  share/picongpu/tests/FieldAbsorber/cmakeFlags
  share/picongpu/tests/KHI_growthRate/cmakeFlags
  share/picongpu/tests/Pusher/cmakeFlags
  share/picongpu/tests/PusherScaling/cmakeFlags
  share/picongpu/tests/SingleParticle/cmakeFlags
  share/picongpu/tests/compile/cmakeFlags
  share/picongpu/tests/compileLaser/cmakeFlags
Labels: refactoring, component: tests

#4752 add method to radiation python module to load distributed amplitudes
  docs/source/usage/plugins/radiation.rst
  lib/python/picongpu/extra/plugins/data/radiation.py
Labels: component: plugin, component: tools, CI:no-compile, changelog

#5119 Rename pressure ionization to IPD ionization
  include/picongpu/param/atomicPhysics_Debug.param
  include/picongpu/particles/atomicPhysics/ParticleType.hpp
  include/picongpu/particles/atomicPhysics/atomicData/AtomicData.hpp
  include/picongpu/particles/atomicPhysics/atomicData/AtomicTuples.def
  include/picongpu/particles/atomicPhysics/atomicData/IPDIonizationStateData.hpp
  include/picongpu/particles/atomicPhysics/debug/PrintAtomicDataToConsole.hpp
  include/picongpu/particles/atomicPhysics/enums/ProcessClass.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/IPDModel.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/NoIPD.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/StewartPyattIPD.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/TemperatureFunctor.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/ApplyIPDIonization.kernel
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/stage/ApplyIPDIonization.hpp
  include/picongpu/particles/atomicPhysics/stage/LoadAtomicInputData.hpp
  include/picongpu/particles/atomicPhysics/stateRepresentation/ConfigNumber.hpp
  include/picongpu/simulation/stage/AtomicPhysics.x.cpp
  share/picongpu/tests/compileAtomicPhysics/include/picongpu/param/atomicPhysics_Debug.param
  share/picongpu/tests/compileAtomicPhysics/include/picongpu/param/speciesDefinition.param
Labels: component: core, refactoring, component: user input

#5130 refactor `value_identifier`
  include/picongpu/param/speciesAttributes.param
  include/picongpu/particles/Particles.kernel
  include/picongpu/particles/ParticlesInit.kernel
  include/picongpu/particles/atomicPhysics/initElectrons/CloneAdditionalAttributes.hpp
  include/picongpu/particles/ionization/byCollision/ThomasFermi/ThomasFermi_Impl.hpp
  include/picongpu/particles/ionization/byField/ADK/ADK_Impl.hpp
  include/picongpu/particles/ionization/byField/BSI/BSI_Impl.hpp
  include/picongpu/particles/ionization/byField/Keldysh/Keldysh_Impl.hpp
  include/picongpu/particles/manipulators/binary/Copy.def
  include/picongpu/particles/manipulators/binary/Derive.def
  include/picongpu/particles/manipulators/manipulators.def
  include/picongpu/particles/synchrotron/AlgorithmSynchrotron.hpp
  include/pmacc/identifier/value_identifier.hpp
  include/pmacc/particles/memory/dataTypes/Particle.hpp
  include/pmacc/particles/operations/CopyValueIdentifier.hpp
  include/pmacc/particles/operations/DeriveValueIdentifier.hpp
  include/pmacc/particles/operations/InitValueIdentifier.hpp
  include/pmacc/ppFunctions.hpp
Labels: component: core, component: PMacc, refactoring, component: user input

#5136 fix gcc 13 compile issue
  include/picongpu/particles/Particles.hpp
  include/picongpu/particles/boundary/Absorbing.hpp
  include/picongpu/particles/boundary/Apply.hpp
  include/picongpu/particles/boundary/Reflecting.hpp
  include/picongpu/particles/boundary/Utility.hpp
Labels: bug

#5141 add check for valid typical ppc
  lib/python/picongpu/pypicongpu/simulation.py
Labels: PICMI

#4826 Implementation of Maxwell Juettner distribution
  include/picongpu/particles/manipulators/manipulators.def
  include/picongpu/particles/manipulators/manipulators.hpp
  include/picongpu/particles/manipulators/unary/MaxwellJuettner.def
  include/picongpu/particles/manipulators/unary/MaxwellJuettner.hpp
Labels: component: core, changelog

#5140 update gamma boost unsupported error message
  lib/python/picongpu/picmi/simulation.py
Labels: PICMI

#5146 fix MaxwellJuettner functor
  include/picongpu/particles/manipulators/unary/MaxwellJuettner.def
  include/picongpu/particles/manipulators/unary/MaxwellJuettner.hpp
Labels: bug

#5143 Add a helper to get particle position
  include/picongpu/param/binningSetup.param
  include/picongpu/plugins/binning/DomainInfo.hpp
  include/picongpu/plugins/binning/binnerPlugin.hpp
Labels: component: plugin

#5111 Restructure post-processing advise for Snakemake
  docs/source/usage/parameter_scans.rst
Labels: documentation, component: tools, CI:no-compile

#5112 Implement TWTS-laser twtstight to replace twtsfast
  include/picongpu/fields/background/templates/twtsfast/BField.tpp
  include/picongpu/fields/background/templates/twtsfast/EField.tpp
  include/picongpu/fields/background/templates/twtsfast/RotateField.tpp
  include/picongpu/fields/background/templates/twtsfast/twtsfast.hpp
  include/picongpu/fields/background/templates/twtstight/BField.hpp
  include/picongpu/fields/background/templates/twtstight/BField.tpp
  include/picongpu/fields/background/templates/twtstight/EField.hpp
  include/picongpu/fields/background/templates/twtstight/EField.tpp
  include/picongpu/fields/background/templates/twtstight/GetInitialTimeDelay_SI.tpp
  include/picongpu/fields/background/templates/twtstight/getFieldPositions_SI.tpp
  include/picongpu/fields/background/templates/twtstight/numComponents.hpp
  include/picongpu/fields/background/templates/twtstight/twtstight.hpp
  include/picongpu/fields/background/templates/twtstight/twtstight.tpp
  include/picongpu/unitless/fieldBackground.unitless
  share/picongpu/benchmarks/TWEAC-FOM/include/picongpu/param/TwtsBackgroundLaser.param
  share/picongpu/benchmarks/TWEAC-FOM/include/picongpu/param/fieldBackground.param
  share/picongpu/benchmarks/TWEAC-FOM/include/picongpu/param/incidentField.param
  share/picongpu/examples/Bunch/cmakeFlags
  share/picongpu/examples/Bunch/include/picongpu/param/fieldBackground.param
Labels: component: core, refactoring
