Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2024-03, with the labels that each got.

#4835 optimize CI runtime
  .gitlab-ci.yml
  share/ci/generate_reduced_matrix.sh
  share/ci/pmacc_env.sh
  share/ci/run_pmacc_header_tests.sh
  share/ci/run_pmacc_tests.sh
  share/ci/run_tests.sh
Labels: component: PMacc, component: tests

#4836 Add diffs to CI
  .gitlab-ci.yml
Labels: component: tools, component: tests, CI:no-compile

#4837 optimize CI performance
  share/ci/install/isaac.sh
  share/ci/install/openPMD.sh
  share/ci/n_wise_generator.py
Labels: refactoring, component: tests

#4844 openPMD plugin: Set particle record attributes as early as possible
  include/picongpu/plugins/openPMD/writer/ParticleAttribute.hpp
Labels: bug, component: plugin

#4842 fix copyright notice
  include/picongpu/plugins/openPMD/GetComponentsType.hpp
Labels: component: core, documentation, refactoring

#4846 updated gpu.profile modules (adapted to fwkt_v100.profile)
  etc/picongpu/hemera-hzdr/gpu_picongpu.profile.example
Labels: machine/system, CI:no-compile

#4848 fix lockstep documentation
  include/pmacc/test/lockstep/lockstepUT.cpp
Labels: component: PMacc, documentation, CI:no-compile

#4850 Run `pre-commit` also pre-push
  .pre-commit-config.yaml
Labels: component: tools, refactoring

#4812 Add feature `--dump-metadata`
  docs/source/index.rst
  docs/source/usage/metadata.rst
  docs/source/usage/picmi/index.rst
  include/picongpu/ArgsParser.hpp
  include/picongpu/CMakeLists.txt
  include/picongpu/MetadataAggregator.hpp
  include/picongpu/MetadataRegisteredAtCT.hpp
  include/picongpu/fields/incidentField/profiles/BaseParam.def
  include/picongpu/fields/incidentField/profiles/Free.hpp
  include/picongpu/fields/incidentField/profiles/GaussianPulse.def
  include/picongpu/fields/incidentField/profiles/GaussianPulse.hpp
  include/picongpu/fields/incidentField/profiles/None.hpp
  include/picongpu/fields/incidentField/profiles/PlaneWave.def
  include/picongpu/fields/incidentField/profiles/PlaneWave.hpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/simulation/control/SimulationStarter.hpp
  include/picongpu/simulation_defines.hpp
  include/picongpu/traits/GetMetadata.hpp
  include/pmacc/simulationControl/SimulationHelper.hpp
  share/picongpu/examples/Bunch/include/picongpu/param/incidentField.param
  share/picongpu/examples/FoilLCT/include/picongpu/param/incidentField.param
  share/picongpu/examples/LaserWakefield/include/picongpu/param/incidentField.param
  share/picongpu/tests/metadataFromLaserWakefield/README.rst
  share/picongpu/tests/metadataFromLaserWakefield/bin/ci.sh
  share/picongpu/tests/metadataFromLaserWakefield/include
  share/picongpu/tests/metadataFromLaserWakefield/picongpu-metadata.json.reference
  share/picongpu/unit/CMakeLists.txt
  share/picongpu/unit/metadata/metadataCLI.cpp
  share/picongpu/unit/metadata/metadataDescription.cpp
  share/picongpu/unit/metadata/metadataPolicies.cpp
Labels: component: core, changelog

#4852 Fix default value for `--no-start-simulation`
  include/picongpu/simulation/control/Simulation.hpp
Labels: bug, component: core

#4839 Add rudimentary zsh profile
  etc/picongpu/zsh/mpiexec.tpl
  etc/picongpu/zsh/mpirun.tpl
  etc/picongpu/zsh/zsh_picongpu.profile.example
Labels: component: tools

#4855 fix CI pypicongpu tests
  lib/python/picongpu/requirements.txt
  share/ci/pypicongpu_generator.py
Labels: component: tests

#4860 fix gcc version in documentation
  INSTALL.rst
Labels: documentation, component: tools

#4856 fix wrong lockstep kernel call
  include/picongpu/particles/collision/InterCollision.hpp
Labels: bug, component: core

#4851 rename `getDataSpace` to `capacityND`
  include/picongpu/fields/FieldJ.tpp
  include/picongpu/fields/FieldTmp.tpp
  include/picongpu/fields/absorber/pml/Field.tpp
  include/picongpu/initialization/InitialiserController.hpp
  include/picongpu/particles/densityProfiles/FromOpenPMDImpl.hpp
  include/picongpu/plugins/ChargeConservation.tpp
  include/picongpu/plugins/Emittance.hpp
  include/picongpu/plugins/EnergyFields.hpp
  include/picongpu/plugins/IsaacPlugin.hpp
  include/picongpu/plugins/PhaseSpace/DumpHBufferOpenPMD.hpp
  include/picongpu/plugins/PhaseSpace/PhaseSpace.tpp
  include/picongpu/plugins/binning/Binner.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/picongpu/plugins/openPMD/restart/RestartFieldLoader.hpp
  include/picongpu/plugins/output/images/Visualisation.hpp
  include/picongpu/plugins/particleCalorimeter/ParticleCalorimeter.hpp
  include/picongpu/plugins/radiation/Radiation.hpp
  include/picongpu/plugins/transitionRadiation/TransitionRadiation.hpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/simulation/stage/Collision.hpp
  include/pmacc/dimensions/GridLayout.hpp
  include/pmacc/fields/operations/AddExchangeToBorder.hpp
  include/pmacc/fields/operations/CopyGuardToExchange.hpp
  include/pmacc/memory/buffers/Buffer.hpp
  include/pmacc/memory/buffers/DeviceBuffer.hpp
  include/pmacc/memory/buffers/Exchange.hpp
  include/pmacc/memory/buffers/GridBuffer.hpp
  include/pmacc/memory/buffers/HostBuffer.hpp
  include/pmacc/mpi/GatherSlice.hpp
  include/pmacc/particles/ParticlesBase.hpp
  include/pmacc/particles/memory/buffers/ParticlesBuffer.hpp
  include/pmacc/particles/memory/buffers/StackExchangeBuffer.hpp
  include/pmacc/test/random/2DDistribution.cpp
  share/pmacc/examples/gameOfLife2D/include/Simulation.hpp
  share/pmacc/examples/heatEquation2D/main.cpp
Labels: component: PMacc, refactoring

#4861 Unification of thrown errors in PyPIConGPU runner interface
  lib/python/picongpu/pypicongpu/runner.py
  lib/python/picongpu/requirements.txt
  share/ci/pypicongpu_generator.py
  test/python/picongpu/quick/picmi/simulation.py
  test/python/picongpu/quick/pypicongpu/runner.py
Labels: component: tools, refactoring
