Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2024-06, with the labels that each got.

#4920 fix RiscV CMakeSupport
  include/pmacc/PMaccConfig.cmake
Labels: backend: omp2b, install, backend: tbb, backend: serial, backend: C++ threads

#4923 fix SynchrotronRadiation
  include/picongpu/simulation/stage/SynchrotronRadiation.hpp
Labels: bug, component: core

#4908 New version of propose_changelog.py
  docs/propose_changelog.py
Labels: component: tools, CI:no-compile

#4917 improved documentation
  include/picongpu/_defaultParam.loader
  include/picongpu/param/dimension.param
  include/picongpu/param/grid.param
  include/picongpu/param/particle.param
  include/pmacc/device/Reduce.hpp
  include/pmacc/particles/memory/dataTypes/SuperCell.hpp
Labels: component: core, component: PMacc, documentation

#4919 improve physicalConstants.param
  include/picongpu/param/physicalConstants.param
Labels: documentation, component: user input

#4761 add README to KHI test and include it in documentation
  docs/source/index.rst
  docs/source/tests
  docs/source/usage/tests.rst
  share/picongpu/tests/KHI_growthRate/README.rst
Labels: documentation, component: tests, CI:no-compile

#4914 matrix multiplication for pmacc
  include/pmacc/math/Matrix.hpp
Labels: component: PMacc, changelog

#4915 add logical-and and logial-or Operations
  include/pmacc/math/operation/And.hpp
  include/pmacc/math/operation/Or.hpp
Labels: component: PMacc, changelog

#4932 remove broken B field implementation of dispersive laser
  include/picongpu/fields/incidentField/profiles/DispersivePulse.hpp
Labels: component: core, changelog

#4916 add particle sparser manipulator
  include/picongpu/particles/manipulators/manipulators.def
  include/picongpu/particles/manipulators/manipulators.hpp
  include/picongpu/particles/manipulators/unary/SparserMacroParticlesPerSuperCell.def
  include/picongpu/particles/manipulators/unary/SparserMacroParticlesPerSuperCell.hpp
Labels: component: core, changelog

#4926 Changes to Synchrotron Radiation from issue #4921. Part 1.
  share/picongpu/tests/Synchrotron_plugin/lib/change_parameters_randomly.py
  share/picongpu/tests/Synchrotron_plugin/lib/requirements.txt
  share/picongpu/tests/Synchrotron_plugin/lib/validate.py
Labels: component: tools, refactoring, CI:no-compile

#4933 refactor flexible binning
  include/picongpu/param/binningSetup.param
  include/picongpu/plugins/binning/Binner.hpp
  include/picongpu/plugins/binning/BinningFunctors.hpp
  include/picongpu/plugins/binning/DomainInfo.hpp
Labels: component: plugin, refactoring

#4930 Increase performance of DispersivePulse
  include/picongpu/fields/incidentField/profiles/DispersivePulse.def
  include/picongpu/fields/incidentField/profiles/DispersivePulse.hpp
Labels: component: core, refactoring, performance

#4931 constructor for `math::Vector` with generator
  include/pmacc/math/vector/Vector.hpp
  include/pmacc/test/vector/vectorUT.cpp
Labels: component: PMacc

#4936 refactor `pic-build` and `pic-configure`
  bin/pic-build
  bin/pic-configure
Labels: component: tools, refactoring, install, changelog

#4937 PMacc: fix wrong queue CMake usage
  bin/pic-configure
  docs/source/dev/debugging.rst
Labels: bug, component: tools, install, CI:no-compile

#4940 OpenPMD plugin: dump time in wrong precision
  include/picongpu/plugins/openPMD/toml.cpp
Labels: bug, component: plugin

#4934 time-step dependent init functor execution
  include/picongpu/particles/InitFunctors.hpp
Labels: component: core

#4918 new flexible kernel for particle creation
  include/picongpu/particles/atomicPhysics/ConvertEnum.hpp
  include/picongpu/particles/creation/ModuleConfig.hpp
  include/picongpu/particles/creation/SpawnFromSourceSpecies.kernel
  include/picongpu/particles/creation/SpawnFromSourceSpeciesModuleInterfaces.hpp
  include/picongpu/particles/creation/moduleInterfaces/AdditionalDataIndexFunctor.hpp
  include/picongpu/particles/creation/moduleInterfaces/InitKernelStateFunctor.hpp
  include/picongpu/particles/creation/moduleInterfaces/ParticlePairUpdateFunctor.hpp
  include/picongpu/particles/creation/moduleInterfaces/PredictorFunctor.hpp
  include/picongpu/particles/creation/moduleInterfaces/SanityCheckInputs.hpp
  include/picongpu/particles/creation/moduleInterfaces/SuperCellFilterFunctor.hpp
  include/picongpu/particles/creation/moduleInterfaces/WriteOutKernelStateFunctor.hpp
Labels: component: core, changelog

#4924 Fixing important issues with synchrotron extension
  include/picongpu/simulation/stage/SynchrotronRadiation.hpp
  share/picongpu/tests/Synchrotron_plugin/include/picongpu/param/synchrotron.param
  share/picongpu/tests/Synchrotron_plugin/lib/change_parameters_randomly.py
Labels: bug, component: core

#4929 Improved checkpoint editing tool
  lib/python/picongpu/extra/input/bunchInit_openPMD_bp.py
  lib/python/picongpu/extra/input/createBunch_example.ipynb
Labels: component: tools

#4944 improve ionization documentation
  docs/source/models/collisional_ionization.rst
  docs/source/models/field_ionization.rst
  docs/source/usage/param.rst
  docs/source/usage/workflows.rst
  docs/source/usage/workflows/ionization.rst
Labels: documentation, CI:no-compile

#4947 dispersive pulse reduce number of calcualtions
  include/picongpu/fields/incidentField/profiles/DispersivePulse.hpp
Labels: component: core, refactoring

#4945 fix custom input rendering
  lib/python/picongpu/picmi/simulation.py
  lib/python/picongpu/pypicongpu/rendering/renderer.py
  lib/python/picongpu/pypicongpu/simulation.py
  test/python/picongpu/quick/picmi/simulation.py
Labels: component: tests, CI:no-compile, PICMI

#4942 update profile and tpl for JURECA
  etc/picongpu/jureca-jsc/gpus.tpl
  etc/picongpu/jureca-jsc/gpus_picongpu.profile.example
Labels: machine/system, CI:no-compile

#4956 fix broken requirements.txt
  lib/python/picongpu/extra/plugins/data/requirements.txt
Labels: component: tools, CI:no-compile

#4955 Minor change to snakemake readme
  share/picongpu/examples/LaserWakefield/lib/python/snakemake/README.rst
Labels: component: tools, component: examples, CI:no-compile

#4957 fix import statements for plugins
  docs/source/usage/plugins/energyHistogram.rst
  docs/source/usage/plugins/phaseSpace.rst
  docs/source/usage/plugins/png.rst
  docs/source/usage/plugins/radiation.rst
Labels: documentation, component: tools, CI:no-compile

#4953 fix `pic-build -c`
  bin/pic-build
Labels: bug, component: tools, CI:no-compile

#4951 Update JURECA profile
  etc/picongpu/jureca-jsc/gpus.tpl
  etc/picongpu/jureca-jsc/gpus_picongpu.profile.example
Labels: machine/system, CI:no-compile

#4952 add warning timestep mismatch snakemake and adjust cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/1.cfg
  share/picongpu/examples/LaserWakefield/lib/python/snakemake/README.rst
Labels: documentation, component: tools, component: examples, CI:no-compile

#4961 plugin: phaseSpace add pair implementation
  include/picongpu/plugins/PhaseSpace/DumpHBufferOpenPMD.hpp
  include/picongpu/plugins/PhaseSpace/Pair.hpp
  include/picongpu/plugins/PhaseSpace/PhaseSpace.hpp
  include/picongpu/plugins/PhaseSpace/PhaseSpaceFunctors.hpp
Labels: bug, component: plugin

#4960 fix C++20 compiler
  include/picongpu/particles/functor/User.hpp
  include/picongpu/plugins/misc/concatenateToString.hpp
Labels: bug, component: core

#4962 add mpiexec to picongpu call of metadata test
  share/picongpu/tests/metadataFromLaserWakefield/bin/ci.sh
Labels: component: tests

#4950 remove python from snakemake requirements.txt
  share/picongpu/examples/LaserWakefield/lib/python/snakemake/requirements.txt
Labels: component: tools, component: examples, CI:no-compile

#4969 fix missing include
  include/picongpu/particles/traits/GetAtomicNumbers.hpp
Labels: bug, component: core

#4968 drop HIP 5.2/5.3 and CUDA 11.0 support
  INSTALL.rst
  share/ci/n_wise_generator.py
Labels: component: tests, install

#4965 PMacc:: Vector add `size()` method
  include/pmacc/math/vector/Vector.hpp
Labels: component: PMacc
