Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2024-05, with the labels that each got.

#4894 fix Shadowgraphy compile
  include/picongpu/plugins/shadowgraphy/Shadowgraphy.hpp
Labels: bug, component: plugin

#4557 Add CurrentDeposition test
  share/picongpu/tests/CurrentDeposition/README.rst
  share/picongpu/tests/CurrentDeposition/bin/ci.sh
  share/picongpu/tests/CurrentDeposition/bin/validate.sh
  share/picongpu/tests/CurrentDeposition/cmakeFlags
  share/picongpu/tests/CurrentDeposition/etc/picongpu/1.cfg
  share/picongpu/tests/CurrentDeposition/include/picongpu/param/density.param
  share/picongpu/tests/CurrentDeposition/include/picongpu/param/fileOutput.param
  share/picongpu/tests/CurrentDeposition/include/picongpu/param/grid.param
  share/picongpu/tests/CurrentDeposition/include/picongpu/param/particle.param
  share/picongpu/tests/CurrentDeposition/include/picongpu/param/species.param
  share/picongpu/tests/CurrentDeposition/include/picongpu/param/speciesDefinition.param
  share/picongpu/tests/CurrentDeposition/include/picongpu/param/speciesInitialization.param
  share/picongpu/tests/CurrentDeposition/lib/python/test/CurrentDeposition/MainTest.py
  share/picongpu/tests/CurrentDeposition/lib/python/test/CurrentDeposition/assignment_and_W_func.py
  share/picongpu/tests/CurrentDeposition/lib/python/test/CurrentDeposition/grid_class.py
  share/picongpu/tests/CurrentDeposition/lib/python/test/CurrentDeposition/requirements.txt
Labels: component: tests, changelog

#4900 update setup juwels booster JSC
  etc/picongpu/juwels-jsc/booster_picongpu.profile.example
Labels: machine/system, CI:no-compile

#4898 fix include guard Shadowgraphy plugin
  include/picongpu/plugins/PluginController.hpp
Labels: bug, component: plugin

#4896 separate setting and configuring in libpng build documentation
  INSTALL.rst
Labels: documentation, component: third party, CI:no-compile

#4889 fix Gaussian and Dispersive pulse
  include/picongpu/fields/incidentField/profiles/DispersivePulse.hpp
  include/picongpu/fields/incidentField/profiles/GaussianPulse.hpp
Labels: bug, component: core, affects latest release

#4902 remove second #pragma once
  include/pmacc/math/functions/Log.hpp
Labels: component: PMacc

#4878 custom user input in PyPIConGPU
  lib/python/picongpu/picmi/simulation.py
  lib/python/picongpu/pypicongpu/__init__.py
  lib/python/picongpu/pypicongpu/customuserinput.py
  lib/python/picongpu/pypicongpu/simulation.py
  share/picongpu/pypicongpu/schema/customrenderingcontext.CustomRenderingContext.json
  share/picongpu/pypicongpu/schema/customuserinput.CustomUserInput.json
  share/picongpu/pypicongpu/schema/simulation.Simulation.json
  test/python/picongpu/compiling/simulation.py
  test/python/picongpu/quick/picmi/simulation.py
  test/python/picongpu/quick/pypicongpu/__init__.py
  test/python/picongpu/quick/pypicongpu/customuserinput.py
  test/python/picongpu/quick/pypicongpu/simulation.py
Labels: component: tools

#4895 CI: add FFTW and enforce usage
  include/picongpu/plugins/shadowgraphy/Shadowgraphy.hpp
  include/picongpu/plugins/shadowgraphy/ShadowgraphyHelper.hpp
  share/ci/compiler_clang.yml
  share/ci/compiler_clang_cuda.yml
  share/ci/compiler_gcc.yml
  share/ci/compiler_hipcc.yml
  share/ci/compiler_nvcc_cuda.yml
  share/ci/install/fftw.sh
  share/ci/pypicongpu.yml
  share/ci/run_picongpu_tests.sh
Labels: bug, component: tests

#4903 CI: test latest ISAAC
  share/ci/install/isaac.sh
Labels: component: tests

#4905 fix slow tbg substitution
  bin/tbg
Labels: bug, affects latest release, CI:no-compile

#4907 remove atomic physics
  docs/source/models/atomicPhysics/AtomicPhysicsIntroduction.rst
  docs/source/models/atomicPhysics/AtomicRateSolver.rst
  docs/source/models/atomicPhysics/processIonFunctorExport.svg
  include/picongpu/_defaultParam.loader
  include/picongpu/param/atomicPhysics.param
  include/picongpu/param/speciesAttributes.param
  include/picongpu/particles/atomicPhysics/AtomicData.hpp
  include/picongpu/particles/atomicPhysics/AtomicPhysics.kernel
  include/picongpu/particles/atomicPhysics/AtomicRate.hpp
  include/picongpu/particles/atomicPhysics/CallAtomicPhysics.hpp
  include/picongpu/particles/atomicPhysics/DecelerateElectrons.hpp
  include/picongpu/particles/atomicPhysics/FillHistogram.hpp
  include/picongpu/particles/atomicPhysics/GetRealKineticEnergy.hpp
  include/picongpu/particles/atomicPhysics/SolveRateEquation.hpp
  include/picongpu/particles/atomicPhysics/electronDistribution/histogram/AdaptiveHistogram.hpp
  include/picongpu/particles/atomicPhysics/electronDistribution/histogram/Histogram.hpp
  include/picongpu/particles/atomicPhysics/stateRepresentation/ConfigNumber.hpp
  include/picongpu/particles/atomicPhysics/stateRepresentation/LevelVector.hpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/simulation/stage/AtomicPhysics.hpp
  include/picongpu/unitless/speciesAttributes.unitless
  share/picongpu/examples/atomicPhysics/README.rst
  share/picongpu/examples/atomicPhysics/etc/picongpu/1.cfg
  share/picongpu/examples/atomicPhysics/include/picongpu/param/atomicPhysics.param
  share/picongpu/examples/atomicPhysics/include/picongpu/param/density.param
  share/picongpu/examples/atomicPhysics/include/picongpu/param/grid.param
  share/picongpu/examples/atomicPhysics/include/picongpu/param/ionizationEnergies.param
  share/picongpu/examples/atomicPhysics/include/picongpu/param/ionizer.param
  share/picongpu/examples/atomicPhysics/include/picongpu/param/memory.param
  share/picongpu/examples/atomicPhysics/include/picongpu/param/particle.param
  share/picongpu/examples/atomicPhysics/include/picongpu/param/species.param
  share/picongpu/examples/atomicPhysics/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/atomicPhysics/include/picongpu/param/speciesInitialization.param
Labels: component: core, refactoring

#4863 Implement Log Axes for the binning plugin
  docs/source/usage/plugins/binningPlugin.rst
  include/picongpu/param/binningSetup.param
  include/picongpu/plugins/binning/Axis.hpp
  include/picongpu/plugins/binning/Binner.hpp
  include/picongpu/plugins/binning/BinningFunctors.hpp
  include/picongpu/plugins/binning/FunctorDescription.hpp
  include/picongpu/plugins/binning/UnitConversion.hpp
  include/picongpu/plugins/binning/WriteHist.hpp
  include/picongpu/plugins/binning/axis/LinearAxis.hpp
  include/picongpu/plugins/binning/axis/LogAxis.hpp
  include/picongpu/plugins/binning/binnerPlugin.hpp
Labels: component: plugin

#4906 modernize `tbg`
  bin/tbg
Labels: component: tools, refactoring, CI:no-compile

#4904 add warning for AOFD solver
  docs/source/models/AOFDTD.rst
Labels: documentation, CI:no-compile

#4911 fix checkpoint restart
  include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp
Labels: bug, component: plugin

#4827 Addition of Synchrotron radiation
  docs/source/usage/workflows.rst
  docs/source/usage/workflows/synchrotronExtensionDocumentation.rst
  include/picongpu/param/speciesAttributes.param
  include/picongpu/param/synchrotron.param
  include/picongpu/particles/ParticlesFunctors.hpp
  include/picongpu/particles/synchrotron/AlgorithmSynchrotron.hpp
  include/picongpu/simulation/control/Simulation.hpp
  include/picongpu/simulation/stage/SynchrotronRadiation.hpp
  lib/python/synchrotronRadiationExtension/synchrotronRequirements.py
  share/picongpu/tests/Synchrotron_plugin/bin/ci.sh
  share/picongpu/tests/Synchrotron_plugin/bin/validate.sh
  share/picongpu/tests/Synchrotron_plugin/include/picongpu/param/density.param
  share/picongpu/tests/Synchrotron_plugin/include/picongpu/param/dimension.param
  share/picongpu/tests/Synchrotron_plugin/include/picongpu/param/fieldBackground.param
  share/picongpu/tests/Synchrotron_plugin/include/picongpu/param/grid.param
  share/picongpu/tests/Synchrotron_plugin/include/picongpu/param/particle.param
  share/picongpu/tests/Synchrotron_plugin/include/picongpu/param/speciesDefinition.param
  share/picongpu/tests/Synchrotron_plugin/include/picongpu/param/speciesInitialization.param
  share/picongpu/tests/Synchrotron_plugin/include/picongpu/param/synchrotron.param
  share/picongpu/tests/Synchrotron_plugin/lib/change_parameters_randomly.py
  share/picongpu/tests/Synchrotron_plugin/lib/requirements.txt
  share/picongpu/tests/Synchrotron_plugin/lib/synchrotron_lib.py
  share/picongpu/tests/Synchrotron_plugin/lib/validate.py
Labels: component: core, feature request

#4909 Time tracing for the openPMD plugin
  include/picongpu/CMakeLists.txt
  include/picongpu/plugins/common/DumpTimes.hpp
  include/picongpu/plugins/openPMD/WriteSpecies.hpp
  include/picongpu/plugins/openPMD/openPMDWriter.def
  include/picongpu/plugins/openPMD/openPMDWriter.hpp
  include/picongpu/plugins/openPMD/writer/ParticleAttribute.hpp
Labels: component: plugin, changelog
