Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2025-02, with the labels that each got.

#5259 Short circuit axis binning if any previous axis is invalid
  include/picongpu/plugins/binning/Axis.hpp
  include/picongpu/plugins/binning/BinningFunctors.hpp
  include/picongpu/plugins/binning/axis/LinearAxis.hpp
  include/picongpu/plugins/binning/axis/LogAxis.hpp
Labels: component: plugin

#5267 update gitignore for clangd and zed
  .gitignore
Labels: CI:no-compile

#5266 CI: fix filter rules
  include/picongpu/particles/Particles.tpp
  include/pmacc/particles/ParticlesBase.hpp
  share/ci/n_wise_generator.py
  share/ci/run_picongpu_tests.sh
  thirdParty/mallocMC/src/include/mallocMC/creationPolicies/Scatter.hpp
Labels: bug, component: tests

#5268 Modernize trivial tuple
  include/pmacc/memory/STLTuple.hpp
Labels: component: PMacc, refactoring

#5264 Update the pmacc tuple utilities and their use in the binning plugin
  include/picongpu/plugins/binning/Binner.hpp
  include/picongpu/plugins/binning/BinningCreator.hpp
  include/picongpu/plugins/binning/BinningData.hpp
  include/picongpu/plugins/binning/BinningFunctors.hpp
  include/picongpu/plugins/binning/FilteredSpecies.hpp
  include/picongpu/plugins/binning/WriteHist.hpp
  include/picongpu/plugins/binning/axis/LinearAxis.hpp
  include/picongpu/plugins/binning/axis/LogAxis.hpp
  include/picongpu/plugins/binning/utility.hpp
Labels: bug, component: plugin

#5273 Allow double precision in TWTSTight unit test
  share/picongpu/unit/TWTSTight.cpp
Labels: component: tests

#5277 Enable complex input for FromOpenPMDPulse profile
  include/picongpu/fields/incidentField/profiles/FromOpenPMDPulse.def
  include/picongpu/fields/incidentField/profiles/FromOpenPMDPulse.hpp
  lib/python/picongpu/extra/input/preparingInsightData.py
  lib/python/picongpu/extra/input/preparingInsightData_example.ipynb
Labels: component: core

#5284 refactor field energy calculation
  include/picongpu/particles/atomicPhysics/FieldEnergy.hpp
  include/picongpu/particles/atomicPhysics/kernel/CalculateRejectionProbability.hpp
Labels: refactoring

#5291 Updates Frontier profile after software update
  etc/picongpu/frontier-ornl/batch_picongpu.profile.example
Labels: component: tools

#5290 Fix variable-length-array warning clang18
  include/picongpu/plugins/openPMD/WriteSpecies.hpp
Labels: component: plugin

#5281 Use flatter scatter per default
  include/picongpu/param/mallocMC.param
Labels: component: core, component: third party, backend: cuda, backend: hip
