Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2025-09, with the labels that each got.

#5465 Removed unit.param reference in docs
  docs/source/usage/param/core.rst
Labels: bug, documentation

#5447 Binning plugin dump improvements
  docs/source/usage/plugins/binningPlugin.rst
  include/picongpu/plugins/binning/BinningCreator.hpp
  include/picongpu/plugins/binning/BinningData.hpp
  include/picongpu/plugins/binning/BinningDispatcher.x.cpp
  include/picongpu/plugins/binning/WriteHist.hpp
  include/picongpu/plugins/binning/binners/Binner.hpp
  include/picongpu/plugins/binning/binners/FieldBinner.hpp
  include/picongpu/plugins/binning/binners/ParticleBinner.hpp
  include/picongpu/plugins/binning/functors/helpers.hpp
  lib/python/picongpu/picmi/diagnostics/binning.py
  lib/python/picongpu/pypicongpu/output/binning.py
  share/picongpu/examples/AtomicPhysics/include/picongpu/param/binningSetup.param
  share/picongpu/pypicongpu/schema/output/binning.Binning.json
  share/picongpu/pypicongpu/template/include/picongpu/param/binningSetup.param.mustache
Labels: component: plugin, component: user input

#5454 Add tests for SelfRegisteringRenderedObject
  lib/python/picongpu/pypicongpu/rendering/renderedobject.py
  test/python/picongpu/quick/pypicongpu/rendering/renderedobject.py
Labels: component: tests, CI:no-compile, PICMI

#5450 Add a table in the binning documentation describing config options
  docs/source/usage/plugins/binningPlugin.rst
  include/picongpu/plugins/binning/BinningCreator.hpp
Labels: documentation, CI:no-compile

#5469 read the docs: change webpage rendering
  docs/source/_static/custom.css
  docs/source/conf.py
Labels: documentation, CI:no-compile

#5471 Fix picmi a0/E0 logic check
  lib/python/picongpu/picmi/lasers/base_laser.py
  lib/python/picongpu/picmi/lasers/gaussian_laser.py
  test/python/picongpu/quick/picmi/gaussian_laser.py
Labels: bug, CI:no-compile, PICMI

#5472 Allow multiple custom templates
  lib/python/picongpu/picmi/simulation.py
  lib/python/picongpu/pypicongpu/runner.py
  test/python/picongpu/compiling/simulation.py
  test/python/picongpu/quick/picmi/__init__.py
  test/python/picongpu/quick/picmi/normalise_template_dir.py
  test/python/picongpu/quick/picmi/simulation.py
  test/python/picongpu/quick/pypicongpu/runner.py
Labels: CI:no-compile, PICMI

#5458 fix max memory per device for capella/zih
  etc/picongpu/taurus-tud/V100.tpl
  etc/picongpu/taurus-tud/V100_restart.tpl
  etc/picongpu/taurus-tud/capella.tpl
  etc/picongpu/taurus-tud/capella_picongpu.profile.example
  etc/picongpu/taurus-tud/k80_picongpu.profile.example
  etc/picongpu/zih-tud/A100.tpl
  etc/picongpu/zih-tud/A100_picongpu.profile.example
  etc/picongpu/zih-tud/A100_restart.tpl
  etc/picongpu/zih-tud/Slurm_Tutorial.rst
  etc/picongpu/zih-tud/capella.tpl
  etc/picongpu/zih-tud/capella_picongpu.profile.example
Labels: machine/system, CI:no-compile
