Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2025-08, with the labels that each got.

#5418 Update Juwels Booster profile
  etc/picongpu/juwels-jsc/booster_picongpu.profile.example
Labels: machine/system, CI:no-compile

#5419 Fix free-formula expression handling and call operator
  lib/python/picongpu/picmi/distribution/AnalyticDistribution.py
Labels: bug, CI:no-compile, PICMI

#5424 fix bug in PICMI ionization configuration for some elements
  lib/python/picongpu/pypicongpu/species/util/element.py
  test/python/picongpu/quick/pypicongpu/species/util/element.py
Labels: bug, PICMI, changelog

#5431 bugfix wrong unit of laser centroid
  share/picongpu/pypicongpu/examples/laser_wakefield/main.py
Labels: bug, CI:no-compile, PICMI

#5429 separate picmi default and yee solver into two files
  lib/python/picongpu/picmi/solver.py
  lib/python/picongpu/pypicongpu/__init__.py
  lib/python/picongpu/pypicongpu/field_solver/DefaultSolver.py
  lib/python/picongpu/pypicongpu/field_solver/Yee.py
  lib/python/picongpu/pypicongpu/field_solver/__init__.py
  lib/python/picongpu/pypicongpu/simulation.py
  share/picongpu/pypicongpu/schema/field_solver/Yee.YeeSolver.json
  share/picongpu/pypicongpu/schema/simulation.Simulation.json
  test/python/picongpu/compiling/simulation.py
  test/python/picongpu/quick/pypicongpu/rendering/renderedobject.py
  test/python/picongpu/quick/pypicongpu/simulation.py
  test/python/picongpu/quick/pypicongpu/solver.py
Labels: refactoring, CI:no-compile, PICMI

#5414 binning plugin examples
  share/picongpu/examples/BinningExamples/README.rst
  share/picongpu/examples/BinningExamples/cmakeFlags
  share/picongpu/examples/BinningExamples/etc/picongpu/8.cfg
  share/picongpu/examples/BinningExamples/include/picongpu/param/binningSetup.param
  share/picongpu/examples/BinningExamples/include/picongpu/param/density.param
  share/picongpu/examples/BinningExamples/include/picongpu/param/incidentField.param
  share/picongpu/examples/BinningExamples/include/picongpu/param/simulation.param
  share/picongpu/examples/BinningExamples/include/picongpu/param/speciesDefinition.param
  share/picongpu/examples/BinningExamples/include/picongpu/param/speciesInitialization.param
Labels: component: plugin, documentation

#5440 add missing exit codes pic-create
  bin/pic-create
Labels: bug, component: tools, CI:no-compile

#5434 Cleanly define the co-moving origin and add moving window tests
  include/picongpu/simulation/control/MovingWindow.hpp
  include/pmacc/test/PMaccFixture.hpp
  share/picongpu/unit/CMakeLists.txt
  share/picongpu/unit/dimensional_tests/CMakeLists.txt
  share/picongpu/unit/dimensional_tests/MovingWindow.cpp
  share/picongpu/unit/dimensional_tests/TWTSTight.cpp
  share/picongpu/unit/dimensional_tests/radiationFormFactor.cpp
  share/picongpu/unit/dimensional_tests/radiationWindowFunction.cpp
  share/picongpu/unit/dimensional_tests/shape.cpp
  share/picongpu/unit/non_dimensional_tests/CMakeLists.txt
Labels: component: tests

#5448 Update moving window tests with variable for distance traveled by light
  share/picongpu/unit/dimensional_tests/MovingWindow.cpp
Labels: component: tests

#5423 Add range checks for parameters in atomicPhysics/IPD
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/StewartPyattIPD.hpp
  include/picongpu/particles/atomicPhysics/ionizationPotentialDepression/kernel/CalculateIPDInput.kernel
  include/pmacc/math/isApprox.hpp
Labels: bug, refactoring, component: examples, changelog
