Repository ComputationalRadiationPhysics/picongpu, pull requests merged in 2025-05, with the labels that each got.

#5359 make kernel struct public in binning plugin LinearAxis
  include/picongpu/plugins/binning/axis/LinearAxis.hpp
Labels: bug

#5357 Remove self referential include
  include/picongpu/fields/incidentField/profiles/BaseParam.def
  include/picongpu/fields/incidentField/traits/GetPhaseVelocity.hpp
Labels: bug

#5361 Fix typos in cfg files in LWFA example
  share/picongpu/examples/LaserWakefield/etc/picongpu/1.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/4.cfg
  share/picongpu/examples/LaserWakefield/etc/picongpu/8.cfg
Labels: bug, component: tools, CI:no-compile

#5363 Fix in cell position of binning
  include/picongpu/plugins/binning/WriteHist.hpp
Labels: bug, component: plugin

#5358 Moving window bugfix
  include/picongpu/simulation/control/MovingWindow.hpp
Labels: bug

#5364 Update mallocMC to the latest dev
  thirdParty/mallocMC/CHANGELOG.md
  thirdParty/mallocMC/CMakeLists.txt
  thirdParty/mallocMC/cmake/Config.cmake.in
  thirdParty/mallocMC/cmake/PackageProject.cmake
  thirdParty/mallocMC/cmake/package-lock.cmake
  thirdParty/mallocMC/cmake/version.h.in
  thirdParty/mallocMC/include/mallocMC/creationPolicies/Scatter.hpp
Labels: component: third party

#5365 Fix CFL condition assert messages
  include/picongpu/fields/MaxwellSolver/CKC/CKC.hpp
  include/picongpu/fields/MaxwellSolver/Lehe/Lehe.hpp
  include/picongpu/fields/MaxwellSolver/Yee/Yee.hpp
  include/picongpu/particles/Particles.tpp
  include/picongpu/simulation/stage/CurrentDeposition.x.cpp
Labels: bug, documentation

#5360 Add reference to paper from Eitan Y. Levine
  docs/source/usage/reference.rst
Labels: documentation, CI:no-compile

#5368 control simulation lifetime
  include/picongpu/main.x.cpp
Labels: bug, component: core, affects latest release

#5372 Update misc picmi stuff
  lib/python/picongpu/picmi/grid.py
  lib/python/picongpu/picmi/simulation.py
  lib/python/picongpu/pypicongpu/output/auto.py
  lib/python/picongpu/pypicongpu/output/energy_histogram.py
  lib/python/picongpu/pypicongpu/output/macro_particle_count.py
  lib/python/picongpu/pypicongpu/output/phase_space.py
  lib/python/picongpu/pypicongpu/rendering/renderedobject.py
  lib/python/picongpu/pypicongpu/simulation.py
  lib/python/picongpu/pypicongpu/species/initmanager.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/__init__.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/densityprofile.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/foil.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/gaussian.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/plasmaramp/exponential.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/plasmaramp/none.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/plasmaramp/plasmaramp.py
  lib/python/picongpu/pypicongpu/species/operation/densityprofile/uniform.py
  lib/python/picongpu/pypicongpu/species/operation/simpledensity.py
  share/picongpu/pypicongpu/schema/simulation.Simulation.json
  share/picongpu/pypicongpu/template/include/picongpu/param/simulation.param.mustache
  test/python/picongpu/compiling/simulation.py
  test/python/picongpu/quick/pypicongpu/output/auto.py
  test/python/picongpu/quick/pypicongpu/simulation.py
  test/python/picongpu/quick/pypicongpu/species/operation/densityprofile/foil.py
Labels: CI:no-compile, PICMI

#5374 Automate compileexamples.py
  test/python/picongpu/compiling/compileexamples.py
Labels: component: tests, CI:no-compile, PICMI

#5373 Fix picmi png plugin
  share/picongpu/pypicongpu/template/include/picongpu/param/png.param.mustache
Labels: bug, CI:no-compile, PICMI

#5371 Add GriddedLayout to PICMI
  lib/python/picongpu/picmi/__init__.py
  lib/python/picongpu/picmi/layout.py
  lib/python/picongpu/picmi/simulation.py
  lib/python/picongpu/pypicongpu/species/operation/layout/__init__.py
  lib/python/picongpu/pypicongpu/species/operation/layout/layout.py
  lib/python/picongpu/pypicongpu/species/operation/layout/one_position.py
  lib/python/picongpu/pypicongpu/species/operation/layout/random.py
  lib/python/picongpu/pypicongpu/species/operation/simpledensity.py
  share/picongpu/pypicongpu/schema/species/operation/layout/layout.Layout.json
  share/picongpu/pypicongpu/schema/species/operation/layout/one_position.OnePosition.json
  share/picongpu/pypicongpu/schema/species/operation/layout/random.Random.json
  share/picongpu/pypicongpu/schema/species/operation/simpledensity.SimpleDensity.json
  share/picongpu/pypicongpu/template/include/picongpu/param/particle.param.mustache
  test/python/picongpu/quick/picmi/layout.py
  test/python/picongpu/quick/pypicongpu/simulation.py
  test/python/picongpu/quick/pypicongpu/species/initmanager.py
  test/python/picongpu/quick/pypicongpu/species/operation/simpledensity.py
Labels: CI:no-compile, PICMI
